BEGIN TRANSACTION;
-- CRIA CHAVE DO SISTEMA PARA INTEGRAÇÃO DO RODOPAR - HORIZONTE
INSERT INTO INTEGRACAO(COD_EMPRESA, CHAVE_SISTEMA, RECURSO_INTEGRADO) VALUES (5, 'RODOPAR_HORIZONTE', 'AFERICAO');

END TRANSACTION;