-- Essa migração deve ser executada quando o WS versão 41 for publicado.

BEGIN TRANSACTION;
    -- ADICIONA CAMPO CÓDIGO AUTO INCREMENT NA TABELA AFERICAO_MANUTENCAO E TORNA ELE PARTE DA CHAVE PRIMÁRIA.
    -- ########################################################################################################
    -- ADICIONA O CAMPO CÓDIGO E FAZ COM QUE AS LINHAS QUE JÁ EXISTAM TENHAM SEU CAMPO CÓDIGO INCREMENTADO CORRETAMENTE.
    ALTER TABLE PUBLIC.AFERICAO_MANUTENCAO ADD COLUMN CODIGO BIGSERIAL;
    -- REMOVE A PRIMARY KEY ATUAL DA TABELA.
    ALTER TABLE PUBLIC.AFERICAO_MANUTENCAO DROP CONSTRAINT PK_AFERICAO_MANUTENCAO;
    -- ADICIONA A NOVA PRIMARY KEY LEVANDO EM CONTA O CÓDIGO ÚNICO DO SERVIÇO.
    ALTER TABLE PUBLIC.AFERICAO_MANUTENCAO
        ADD CONSTRAINT PK_AFERICAO_MANUTENCAO
    PRIMARY KEY (CODIGO, COD_AFERICAO, COD_PNEU, COD_UNIDADE, TIPO_SERVICO);
    -- ########################################################################################################

    -- REMOVE COLUNA NÃO MAIS UTILIZADA.
    -- ########################################################################################################
    ALTER TABLE PUBLIC.AFERICAO_MANUTENCAO DROP COLUMN COD_PNEU_INCONSISTENCIA;
    -- ########################################################################################################

    -- ADICIONA O COD_PROCESSO_MOVIMENTACAO. ISSO PORQUE QUANDO UM SERVIÇO DE
    -- MOVIMENTAÇÃO É FECHADO O PROLOG CRIA AUTOMATICAMENTE UM PROCESSO DE MOVIMENTAÇÃO PARA ESSE PNEU.
    -- ########################################################################################################
    ALTER TABLE PUBLIC.AFERICAO_MANUTENCAO ADD COLUMN COD_PROCESSO_MOVIMENTACAO BIGINT;
    ALTER TABLE PUBLIC.AFERICAO_MANUTENCAO ADD CONSTRAINT
        FK_AFERICAO_MANUTENCAO_MOVIMENTACAO_PROCESSO FOREIGN KEY (COD_UNIDADE, COD_PROCESSO_MOVIMENTACAO)
    REFERENCES PUBLIC.MOVIMENTACAO_PROCESSO(COD_UNIDADE, CODIGO);
    -- ########################################################################################################

    -- ADICIONA COLUNA TEMPO_REALIZACAO_MILLIS PARAR ARMAZENAR QUANTO TEMPO LEVOU O CONSERTO DE UM SERVIÇO.
    -- ########################################################################################################
    ALTER TABLE PUBLIC.AFERICAO_MANUTENCAO ADD COLUMN TEMPO_REALIZACAO_MILLIS BIGINT;
    -- ########################################################################################################

    -- ADICIONA COLUNA PARA INFORMAR SE O SERVIÇO FOI FECHADO AUTOMATICAMENTE ATRAVÉS DE UMA MOVIMENTAÇÃO.
    -- ########################################################################################################
    ALTER TABLE PUBLIC.AFERICAO_MANUTENCAO ADD COLUMN FECHADO_AUTOMATICAMENTE_MOVIMENTACAO BOOLEAN;
    -- ########################################################################################################

    -- DELETA ENTRADAS QUE NÃO POSSUAM CÓDIGO DE BANDA SETADO E FAZ COLUNA SER NOT NULL.
    -- ########################################################################################################
    DELETE FROM PUBLIC.PNEU_VALOR_VIDA WHERE COD_MODELO_BANDA IS NULL;
    ALTER TABLE PUBLIC.PNEU_VALOR_VIDA ALTER COLUMN COD_MODELO_BANDA SET NOT NULL;
    -- ########################################################################################################

    -- ATUALIZA SERVIÇOS DE MOVIMENTAÇÃO FECHADOS ANTIGAMENTE. VINCULANDO A ELES O CÓDIGO DE PROCESSO DE
    -- MOVIMENTAÇÃO CORRETO. TAMBÉM SÃO REMOVIDOS 2 SERVIÇOS QUE ESTAVAM COM INCOSISTÊNCIA. SEUS SERVIÇOS FORAM
    -- AUTOMATICAMENTE FECHADOS QUANDO MOVIDOS DO ESTOQUE PARA O VEÍCULO. PORÉM, SE ESTAVAM EM ESTOQUE, NEM
    -- DEVERIAM TER SERVIÇOS EM ABERTO
    -- ########################################################################################################
    -- 1900225
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 59,
      COD_PNEU_INSERIDO = '1900368',
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_AFERICAO = 1243
      AND COD_UNIDADE = 1
      AND COD_PNEU = '1900225'
      AND TIPO_SERVICO = 'movimentacao'
      AND DATA_HORA_RESOLUCAO IS NOT NULL;

    -- 1900242 MOVIMENTAÇÃO
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 35,
      COD_PNEU_INSERIDO = '1900280',
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_AFERICAO = 1242
      AND COD_UNIDADE = 1
      AND COD_PNEU = '1900242'
      AND TIPO_SERVICO = 'movimentacao'
      AND DATA_HORA_RESOLUCAO IS NOT NULL;

      -- 1900242 CALIBRAGEM
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 35,
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_PNEU = '1900242'
      AND COD_UNIDADE = 1
      AND TIPO_SERVICO = 'calibragem'
      AND PSI_APOS_CONSERTO IS NULL
      AND DATA_HORA_RESOLUCAO IS NOT NULL;

    -- 1900226
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 59,
      COD_PNEU_INSERIDO = '1900271',
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_AFERICAO = 1243
      AND COD_UNIDADE = 1
      AND COD_PNEU = '1900226'
      AND TIPO_SERVICO = 'movimentacao'
      AND DATA_HORA_RESOLUCAO IS NOT NULL;

    -- 1900237
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 38,
      COD_PNEU_INSERIDO = '1900030',
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_AFERICAO = 1244
      AND COD_UNIDADE = 1
      AND COD_PNEU = '1900237'
      AND TIPO_SERVICO = 'movimentacao'
      AND DATA_HORA_RESOLUCAO IS NOT NULL;

    -- 1900178
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 42,
      COD_PNEU_INSERIDO = '1900223',
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_AFERICAO = 1247
      AND COD_UNIDADE = 1
      AND COD_PNEU = '1900178'
      AND TIPO_SERVICO = 'movimentacao'
      AND DATA_HORA_RESOLUCAO IS NOT NULL;

    -- 1900241
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 50,
      COD_PNEU_INSERIDO = '1900047',
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_AFERICAO = 1242
      AND COD_UNIDADE = 1
      AND COD_PNEU = '1900241'
      AND TIPO_SERVICO = 'movimentacao'
      AND DATA_HORA_RESOLUCAO IS NOT NULL;

    -- 1900207
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 54,
      COD_PNEU_INSERIDO = '1900187',
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_AFERICAO = 1245
      AND COD_UNIDADE = 1
      AND COD_PNEU = '1900207'
      AND TIPO_SERVICO = 'movimentacao'
      AND DATA_HORA_RESOLUCAO IS NOT NULL;

    -- 1900068
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 44,
      COD_PNEU_INSERIDO = '1900675',
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_AFERICAO = 1248
      AND COD_UNIDADE = 1
      AND COD_PNEU = '1900068'
      AND TIPO_SERVICO = 'movimentacao'
      AND DATA_HORA_RESOLUCAO IS NOT NULL;

    -- 1900170 MOVIMENTAÇÃO
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 47,
      COD_PNEU_INSERIDO = '1900687',
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_AFERICAO = 1264
      AND COD_UNIDADE = 1
      AND COD_PNEU = '1900170'
      AND TIPO_SERVICO = 'movimentacao'
      AND DATA_HORA_RESOLUCAO IS NOT NULL;

      -- 1900170 CALIBRAGEM
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 47,
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_PNEU = '1900170'
      AND COD_UNIDADE = 1
      AND TIPO_SERVICO = 'calibragem'
      AND PSI_APOS_CONSERTO IS NULL
      AND DATA_HORA_RESOLUCAO IS NOT NULL;

    -- 1900234 MOVIMENTAÇÃO
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 59,
      COD_PNEU_INSERIDO = '1900048',
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_AFERICAO = 1269
      AND COD_UNIDADE = 1
      AND COD_PNEU = '1900234'
      AND TIPO_SERVICO = 'movimentacao'
      AND DATA_HORA_RESOLUCAO IS NOT NULL;

    -- 1900234 CALIBRAGEM
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 59,
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_PNEU = '1900234'
      AND COD_UNIDADE = 1
      AND TIPO_SERVICO = 'calibragem'
      AND PSI_APOS_CONSERTO IS NULL
      AND DATA_HORA_RESOLUCAO IS NOT NULL;

    -- 1900061
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 38,
      COD_PNEU_INSERIDO = '1900029',
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_AFERICAO = 1244
      AND COD_UNIDADE = 1
      AND COD_PNEU = '1900061'
      AND TIPO_SERVICO = 'movimentacao'
      AND DATA_HORA_RESOLUCAO IS NOT NULL;

    -- 1900228
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 50,
      COD_PNEU_INSERIDO = '1900272',
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_AFERICAO = 1243
      AND COD_UNIDADE = 1
      AND COD_PNEU = '1900228'
      AND TIPO_SERVICO = 'movimentacao'
      AND DATA_HORA_RESOLUCAO IS NOT NULL;

    -- 1900210
    DELETE FROM AFERICAO_MANUTENCAO
    WHERE COD_AFERICAO = 1290
      AND COD_UNIDADE = 1
      AND COD_PNEU = '1900210'
      AND DATA_HORA_RESOLUCAO IS NOT NULL;

    -- 1900232
    DELETE FROM AFERICAO_MANUTENCAO
    WHERE COD_AFERICAO = 1241
      AND COD_UNIDADE = 1
      AND COD_PNEU = '1900232'
      AND TIPO_SERVICO = 'movimentacao'
      AND DATA_HORA_RESOLUCAO IS NOT NULL;
    -- ########################################################################################################

    -- ATUALIZA SERVIÇOS DE CALIBRAGEM E INSPEÇÃO FECHADOS ANTIGAMENTE. VINCULANDO A ELES O CÓDIGO DE PROCESSO DE
    -- MOVIMENTAÇÃO CORRETO.
    -- ########################################################################################################
    -- 1900358
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 24,
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_PNEU = '1900358'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1056
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900157
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 24,
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_PNEU = '1900157'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 842
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900047
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 35,
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_PNEU = '1900047'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1291
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900277
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 35,
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_PNEU = '1900277'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1291
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900247
    DELETE FROM AFERICAO_MANUTENCAO
    WHERE COD_PNEU = '1900247'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1291
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900043
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 37,
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_PNEU = '1900043'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1249
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900007
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 37,
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_PNEU = '1900007'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1249
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900027
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 38,
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_PNEU = '1900027'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1292
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900048
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 39,
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_PNEU = '1900048'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1287
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900052
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 39,
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_PNEU = '1900052'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1287
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900269
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 40,
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_PNEU = '1900269'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1288
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900502
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 50,
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_PNEU = '1900502'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1231
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900198
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 50,
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_PNEU = '1900198'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1231
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900224
    UPDATE AFERICAO_MANUTENCAO SET
      COD_PROCESSO_MOVIMENTACAO = 53,
      FECHADO_AUTOMATICAMENTE_MOVIMENTACAO = TRUE
    WHERE COD_PNEU = '1900224'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1230
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900194
    DELETE FROM AFERICAO_MANUTENCAO
    WHERE COD_PNEU = '1900194'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1231
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900235
    DELETE FROM AFERICAO_MANUTENCAO
    WHERE COD_PNEU = '1900235'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1229
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900236
    DELETE FROM AFERICAO_MANUTENCAO
    WHERE COD_PNEU = '1900236'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1229
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900188
    DELETE FROM AFERICAO_MANUTENCAO
    WHERE COD_PNEU = '1900188'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1254
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900169
    DELETE FROM AFERICAO_MANUTENCAO
    WHERE COD_PNEU = '1900169'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1296
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;

    -- 1900208
    DELETE FROM AFERICAO_MANUTENCAO
    WHERE COD_PNEU = '1900208'
          AND COD_UNIDADE = 1
          AND COD_AFERICAO = 1290
          AND PSI_APOS_CONSERTO IS NULL
          AND DATA_HORA_RESOLUCAO IS NOT NULL
          AND COD_PROCESSO_MOVIMENTACAO IS NULL;
    -- ########################################################################################################

    -- CRIA TABELA PARA PODERMOS ADICIONAR IMAGENS AOS CHECKLISTS REALIZADOS PELA AVILAN, QUE POSSUEM
    -- INTEGRAÇÃO COM O LATROMI.
    -- ########################################################################################################
    create table avilan.checklist_pergunta_url_imagem(
      cod_questionario bigint not null,
      cod_pergunta bigint not null,
      descricao_pergunta text not null,
      url_imagem text not null,
      constraint pk_checklist_pergunta_url_imagem PRIMARY KEY (cod_questionario, cod_pergunta)
    );
    comment on table avilan.checklist_pergunta_url_imagem is 'Mapeia uma url de imagem para cada pergunta de um questionário';
    -- ########################################################################################################
END TRANSACTION;