CREATE OR REPLACE FUNCTION FUNC_MARCACAO_GET_INCONSISTENCIAS_TIPO_FIM_ANTES_INICIO(
  F_COD_COLABORADOR BIGINT,
  F_DIA             DATE)
  RETURNS TABLE(
    COD_MARCACAO_INICIO       BIGINT,
    DATA_HORA_MARCACAO_INICIO TIMESTAMP WITHOUT TIME ZONE,
    COD_MARCACAO_FIM          BIGINT,
    DATA_HORA_MARCACAO_FIM    TIMESTAMP WITHOUT TIME ZONE,
    NOME_COLABORADOR          TEXT
  )
LANGUAGE PLPGSQL
AS $$
DECLARE
  CPF_COLABORADOR_FILTRO BIGINT := (SELECT C.CPF
                                    FROM COLABORADOR C
                                    WHERE C.CODIGO = F_COD_COLABORADOR);
BEGIN
  RETURN QUERY
  SELECT
    F.COD_MARCACAO_INICIO                                     AS COD_MARCACAO_INICIO,
    F.DATA_HORA_INICIO AT TIME ZONE TZ_UNIDADE(F.COD_UNIDADE) AS DATA_HORA_INICIO,
    F.COD_MARCACAO_FIM                                        AS COD_MARCACAO_FIM,
    F.DATA_HORA_FIM AT TIME ZONE TZ_UNIDADE(F.COD_UNIDADE)    AS DATA_HORA_FIM,
    C.NOME :: TEXT                                            AS NOME_COLABORADOR
  FROM FUNC_INTERVALOS_AGRUPADOS(NULL, CPF_COLABORADOR_FILTRO, NULL) F
    JOIN COLABORADOR C ON F.CPF_COLABORADOR = C.CPF
  WHERE F.DATA_HORA_FIM < F.DATA_HORA_INICIO
        AND F.DATA_HORA_INICIO IS NOT NULL
        AND F.DATA_HORA_FIM IS NOT NULL
        AND ((DATA_HORA_INICIO AT TIME ZONE TZ_UNIDADE(F.COD_UNIDADE)) :: DATE = F_DIA
             OR (DATA_HORA_FIM AT TIME ZONE TZ_UNIDADE(F.COD_UNIDADE)) :: DATE = F_DIA);
END;
$$;