CREATE OR REPLACE FUNCTION FUNC_MARCACAO_GET_HISTORICO_AJUSTES(F_COD_MARCACOES BIGINT [])
  RETURNS TABLE(
    COD_MARCACAO            BIGINT,
    NOME_RESPONSAVEL_AJUSTE TEXT,
    DATA_HORA_AJUSTE        TIMESTAMP WITHOUT TIME ZONE,
    JUSTIFICATIVA_AJUSTE    TEXT,
    OBSERVACAO_AJUSTE       TEXT,
    ACAO_AJUSTE             TEXT,
    TIPO_MARCACAO           TEXT,
    DATA_HORA_ANTIGA        TIMESTAMP WITHOUT TIME ZONE,
    DATA_HORA_NOVA          TIMESTAMP WITHOUT TIME ZONE
  )
LANGUAGE SQL
AS $$
SELECT
  MH.COD_MARCACAO                                                           AS COD_MARCACAO,
  C.NOME                                                                    AS NOME_RESPONSAVEL_AJUSTE,
  MA.DATA_HORA_AJUSTE AT TIME ZONE (TZ_UNIDADE(MA.COD_UNIDADE_AJUSTE))      AS DATA_HORA_AJUSTE,
  MJA.NOME                                                                  AS JUSTIFICATIVA_AJUSTE,
  MA.OBSERVACAO_AJUSTE                                                      AS OBSERVACAO_AJUSTE,
  MA.ACAO_AJUSTE                                                            AS ACAO_AJUSTE,
  I.TIPO_MARCACAO                                                           AS TIPO_MARCACAO,
  MH.DATA_HORA_ANTIGA AT TIME ZONE (TZ_UNIDADE(I.COD_UNIDADE))              AS DATA_HORA_ANTIGA,
  -- Esse select interno provavelmente atrasa a query, mas é uma solução muito simples.
  LEAD(MH.DATA_HORA_ANTIGA, 1, (SELECT DATA_HORA
                                FROM INTERVALO
                                WHERE CODIGO = MH.COD_MARCACAO))
  OVER (
    PARTITION BY MH.COD_MARCACAO ) AT TIME ZONE (TZ_UNIDADE(I.COD_UNIDADE)) AS DATA_HORA_NOVA
FROM MARCACAO_HISTORICO MH
  JOIN MARCACAO_AJUSTE MA ON MH.COD_AJUSTE = MA.CODIGO
  JOIN MARCACAO_JUSTIFICATIVA_AJUSTE MJA ON MA.COD_JUSTIFICATIVA_AJUSTE = MJA.CODIGO
  JOIN INTERVALO I ON MH.COD_MARCACAO = I.CODIGO
  JOIN COLABORADOR C ON MA.COD_COLABORADOR_AJUSTE = C.CODIGO
WHERE MH.COD_MARCACAO = ANY (F_COD_MARCACOES)
ORDER BY MA.DATA_HORA_AJUSTE ASC;
$$;