CREATE OR REPLACE FUNCTION FUNC_MARCACAO_GET_INCONSISTENCIAS_TIPO_SEM_VINCULO(
  F_COD_COLABORADOR BIGINT,
  F_DIA             DATE)
  RETURNS TABLE(
    COD_MARCACAO_SEM_VINCULO BIGINT,
    TIPO_INICIO_FIM            TEXT,
    NOME_COLABORADOR         TEXT,
    DATA_HORA_MARCACAO       TIMESTAMP WITHOUT TIME ZONE
  )
LANGUAGE PLPGSQL
AS $$
DECLARE
  CPF_COLABORADOR_FILTRO BIGINT := (SELECT C.CPF
                                    FROM COLABORADOR C
                                    WHERE C.CODIGO = F_COD_COLABORADOR);
  TIPO_MARCACAO_INICIO   TEXT := 'MARCACAO_INICIO';
  TIPO_MARCACAO_FIM      TEXT := 'MARCACAO_FIM';
BEGIN
  RETURN QUERY
  WITH MARCACOES_DIA AS (
      SELECT
        I.CODIGO        AS COD_MARCACAO,
        I.TIPO_MARCACAO AS TIPO_MARCACAO,
        I.DATA_HORA     AS DATA_HORA_MARCACAO,
        I.COD_UNIDADE   AS COD_UNIDADE_MARCACAO,
        C.NOME          AS NOME_COLABORADOR
      FROM INTERVALO I
        JOIN COLABORADOR C ON I.CPF_COLABORADOR = C.CPF
      WHERE
        (I.DATA_HORA AT TIME ZONE TZ_UNIDADE(I.COD_UNIDADE)) :: DATE = F_DIA
        AND I.CPF_COLABORADOR = CPF_COLABORADOR_FILTRO
        AND I.STATUS_ATIVO = TRUE
  ),

      INICIOS AS (
        SELECT *
        FROM MARCACOES_DIA MD
        WHERE MD.TIPO_MARCACAO = TIPO_MARCACAO_INICIO
    ),

      FINS AS (
        SELECT *
        FROM MARCACOES_DIA MD
        WHERE MD.TIPO_MARCACAO = TIPO_MARCACAO_FIM
    )


  SELECT
    I.COD_MARCACAO                                                         AS COD_MARCACAO_SEM_VINCULO,
    I.TIPO_MARCACAO :: TEXT                                                AS TIPO_INICIO_FIM,
    I.NOME_COLABORADOR :: TEXT                                             AS NOME_COLABORADOR,
    (I.DATA_HORA_MARCACAO AT TIME ZONE TZ_UNIDADE(I.COD_UNIDADE_MARCACAO)) AS DATA_HORA_MARCACAO
  FROM INICIOS I
    LEFT JOIN MARCACAO_VINCULO_INICIO_FIM MV
      ON I.COD_MARCACAO = MV.COD_MARCACAO_INICIO
  WHERE MV.CODIGO IS NULL
  UNION ALL
  SELECT
    F.COD_MARCACAO                                                         AS COD_MARCACAO_SEM_VINCULO,
    F.TIPO_MARCACAO :: TEXT                                                AS TIPO_INICIO_FIM,
    F.NOME_COLABORADOR :: TEXT                                             AS NOME_COLABORADOR,
    (F.DATA_HORA_MARCACAO AT TIME ZONE TZ_UNIDADE(F.COD_UNIDADE_MARCACAO)) AS DATA_HORA_MARCACAO
  FROM FINS F
    LEFT JOIN MARCACAO_VINCULO_INICIO_FIM MV
      ON F.COD_MARCACAO = MV.COD_MARCACAO_FIM
  WHERE MV.CODIGO IS NULL;
END;
$$;