
package br.com.zalf.prolog.webservice.integracao.avacorpavilan.deprecated.cadastro.service;

import br.com.zalf.prolog.webservice.integracao.avacorpavilan.deprecated.AvaCorpAvilanConstants;
import jakarta.xml.ws.*;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * Web Service para integracao do Avacorp com o ProLog
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Cadastro", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, wsdlLocation = AvaCorpAvilanConstants.BASE_URL + "Cadastro.asmx?WSDL")
public class CadastroAvaCorpAvilanService
    extends Service
{

    private final static URL CADASTRO_WSDL_LOCATION;
    private final static WebServiceException CADASTRO_EXCEPTION;
    private final static QName CADASTRO_QNAME = new QName(AvaCorpAvilanConstants.NAMESPACE, "Cadastro");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(AvaCorpAvilanConstants.BASE_URL + "Cadastro.asmx?WSDL");
        } catch (final MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CADASTRO_WSDL_LOCATION = url;
        CADASTRO_EXCEPTION = e;
    }

    public CadastroAvaCorpAvilanService() {
        super(__getWsdlLocation(), CADASTRO_QNAME);
    }

    public CadastroAvaCorpAvilanService(final WebServiceFeature... features) {
        super(__getWsdlLocation(), CADASTRO_QNAME, features);
    }

    public CadastroAvaCorpAvilanService(final URL wsdlLocation) {
        super(wsdlLocation, CADASTRO_QNAME);
    }

    public CadastroAvaCorpAvilanService(final URL wsdlLocation, final WebServiceFeature... features) {
        super(wsdlLocation, CADASTRO_QNAME, features);
    }

    public CadastroAvaCorpAvilanService(final URL wsdlLocation, final QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CadastroAvaCorpAvilanService(final URL wsdlLocation, final QName serviceName, final WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (CADASTRO_EXCEPTION!= null) {
            throw CADASTRO_EXCEPTION;
        }
        return CADASTRO_WSDL_LOCATION;
    }

    /**
     *
     * @return
     *     returns CadastroSoap
     */
    @WebEndpoint(name = "CadastroSoap")
    public CadastroAvaCorpAvilanSoap getCadastroSoap() {
        return super.getPort(new QName(AvaCorpAvilanConstants.NAMESPACE, "CadastroSoap"), CadastroAvaCorpAvilanSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CadastroSoap
     */
    @WebEndpoint(name = "CadastroSoap")
    public CadastroAvaCorpAvilanSoap getCadastroSoap(final WebServiceFeature... features) {
        return super.getPort(new QName(AvaCorpAvilanConstants.NAMESPACE, "CadastroSoap"), CadastroAvaCorpAvilanSoap.class, features);
    }

}
