-- Sobre:
--
-- Function que retorna a listagem de modelos de checklist na versão atual.
--
-- Histórico:
-- 2020-03-03 -> Atualização de arquivo e documentação (wvinim - PL-2494).
CREATE OR REPLACE FUNCTION FUNC_CHECKLIST_GET_LISTAGEM_MODELOS_CHECKLIST(F_COD_UNIDADE BIGINT)
    RETURNS TABLE
            (
                MODELO          TEXT,
                COD_MODELO      BIGINT,
                COD_UNIDADE     BIGINT,
                NOME_CARGO      TEXT,
                TIPO_VEICULO    TEXT,
                TOTAL_PERGUNTAS BIGINT,
                STATUS_ATIVO    BOOLEAN
            )
    LANGUAGE SQL
AS
$$
SELECT CM.NOME          AS MODELO,
       CM.CODIGO        AS COD_MODELO,
       CM.COD_UNIDADE   AS COD_UNIDADE,
       F.NOME           AS NOME_CARGO,
       VT.NOME          AS TIPO_VEICULO,
       COUNT(CP.CODIGO) AS TOTAL_PERGUNTAS,
       CM.STATUS_ATIVO  AS STATUS_ATIVO
FROM CHECKLIST_MODELO CM
         JOIN CHECKLIST_PERGUNTAS CP ON CM.COD_UNIDADE = CP.COD_UNIDADE
    AND CM.CODIGO = CP.COD_CHECKLIST_MODELO
    AND CM.COD_VERSAO_ATUAL = CP.COD_VERSAO_CHECKLIST_MODELO
         LEFT JOIN CHECKLIST_MODELO_FUNCAO CMF ON CM.COD_UNIDADE = CMF.COD_UNIDADE
    AND CM.CODIGO = CMF.COD_CHECKLIST_MODELO
         LEFT JOIN FUNCAO F ON CMF.COD_FUNCAO = F.CODIGO
         LEFT JOIN CHECKLIST_MODELO_VEICULO_TIPO CMVT ON CM.COD_UNIDADE = CMVT.COD_UNIDADE
    AND CM.CODIGO = CMVT.COD_MODELO
         LEFT JOIN VEICULO_TIPO VT ON CMVT.COD_TIPO_VEICULO = VT.CODIGO
WHERE CM.COD_UNIDADE = F_COD_UNIDADE
GROUP BY CM.NOME, CM.CODIGO, CM.COD_UNIDADE, F.NOME, VT.CODIGO, CM.STATUS_ATIVO
ORDER BY CM.STATUS_ATIVO DESC, CM.CODIGO ASC;
$$;