CREATE OR REPLACE VIEW COLABORADOR AS
  SELECT
    C.CPF,
    C.MATRICULA_AMBEV,
    C.MATRICULA_TRANS,
    C.DATA_NASCIMENTO,
    C.DATA_ADMISSAO,
    C.DATA_DEMISSAO,
    C.STATUS_ATIVO,
    C.NOME,
    C.COD_EQUIPE,
    C.COD_FUNCAO,
    C.COD_UNIDADE,
    C.COD_PERMISSAO,
    C.COD_EMPRESA,
    C.COD_SETOR,
    C.PIS,
    C.DATA_HORA_CADASTRO,
    C.CODIGO,
    C.COD_UNIDADE_CADASTRO
  FROM COLABORADOR_DATA C
  WHERE C.DELETADO = FALSE;