SELECT U.NOME                       AS NOME_UNIDADE,
       CM.NOME                      AS NOME_MODELO,
       CP.PERGUNTA                  AS PERGUNTA,
       CAP.ALTERNATIVA              AS ALTERNATIVA,
       CASE
           WHEN CP.SINGLE_CHOICE
               THEN 'ÚNICA'
           ELSE 'MÚLTIPLA' END      AS TIPO_DE_RESPOSTA,
       CAP.PRIORIDADE               AS PRIORIDADE,
       CAP.DEVE_ABRIR_ORDEM_SERVICO AS DEVE_ABRIR_OS,
       CM.CODIGO                    AS CODIGO_CHECKLIST,
       CP.CODIGO                    AS CODIGO_PERGUNTA,
       CAP.CODIGO                   AS CODIGO_ALTERNATIVA,
       CP.CODIGO_CONTEXTO           AS NOVO_CODIGO_PERGUNTA,
       CAP.CODIGO_CONTEXTO          AS NOVO_CODIGO_ALTERNATIVA
FROM CHECKLIST_MODELO CM
         JOIN CHECKLIST_PERGUNTAS CP
              ON CM.CODIGO = CP.COD_CHECKLIST_MODELO
                  AND CM.COD_VERSAO_ATUAL = CP.COD_VERSAO_CHECKLIST_MODELO
         JOIN CHECKLIST_ALTERNATIVA_PERGUNTA CAP
              ON CP.COD_UNIDADE = CAP.COD_UNIDADE
                  AND CP.COD_CHECKLIST_MODELO = CAP.COD_CHECKLIST_MODELO
                  AND CM.COD_VERSAO_ATUAL = CAP.COD_VERSAO_CHECKLIST_MODELO
                  AND CP.CODIGO = CAP.COD_PERGUNTA
         JOIN UNIDADE U
              ON CM.COD_UNIDADE = U.CODIGO
WHERE CM.COD_UNIDADE IN (SELECT U.CODIGO FROM UNIDADE U WHERE U.COD_EMPRESA = 4)
ORDER BY U.NOME, CM.NOME, CP.PERGUNTA, CAP.ALTERNATIVA;