
package br.com.zalf.prolog.webservice.integracao.avacorpavilan.afericao.service;

import br.com.zalf.prolog.webservice.integracao.avacorpavilan.AvaCorpAvilanConstants;
import br.com.zalf.prolog.webservice.integracao.avacorpavilan.afericao.IncluirMedida2;
import br.com.zalf.prolog.webservice.integracao.avacorpavilan.afericao.IncluirRegistroVeiculo;
import br.com.zalf.prolog.webservice.integracao.avacorpavilan.afericao.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AfericaoSoap", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AfericaoAvaCorpAvilanSoap {


    /**
     * 
     * @param medida
     * @return
     *     returns br.com.avacorp.integracaoprolog.IncluirRegistroVeiculo
     */
    @WebMethod(action = AvaCorpAvilanConstants.NAMESPACE + "/incluirMedida")
    @WebResult(name = "incluirMedidaResult", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
    @RequestWrapper(localName = "incluirMedida", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.IncluirMedida")
    @ResponseWrapper(localName = "incluirMedidaResponse", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.IncluirMedidaResponse")
    public IncluirRegistroVeiculo incluirMedida(
            @WebParam(name = "medida", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    IncluirMedida2 medida);

}
