
package br.com.zalf.prolog.webservice.integracao.praxio.ordensservicos.soap;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(
        name = "ManutencaoWSTerceiros",
        targetNamespace = "http://bgmrodotec.com.br/globus5/ManutencaoWsTerceiros",
        wsdlLocation = "http://sp.bgmrodotec.com.br:8184/vanderlei.junior/ManutencaoWSTerceiros.asmx?wsdl")
public class ManutencaoWSTerceiros extends Service {

    private final static URL MANUTENCAOWSTERCEIROS_WSDL_LOCATION;
    private final static WebServiceException MANUTENCAOWSTERCEIROS_EXCEPTION;
    private final static QName MANUTENCAOWSTERCEIROS_QNAME =
            new QName(
                    "http://bgmrodotec.com.br/globus5/ManutencaoWsTerceiros",
                    "ManutencaoWSTerceiros");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sp.bgmrodotec.com.br:8184/vanderlei.junior/ManutencaoWSTerceiros.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MANUTENCAOWSTERCEIROS_WSDL_LOCATION = url;
        MANUTENCAOWSTERCEIROS_EXCEPTION = e;
    }

    public ManutencaoWSTerceiros() {
        super(__getWsdlLocation(), MANUTENCAOWSTERCEIROS_QNAME);
    }

    public ManutencaoWSTerceiros(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANUTENCAOWSTERCEIROS_QNAME, features);
    }

    public ManutencaoWSTerceiros(URL wsdlLocation) {
        super(wsdlLocation, MANUTENCAOWSTERCEIROS_QNAME);
    }

    public ManutencaoWSTerceiros(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANUTENCAOWSTERCEIROS_QNAME, features);
    }

    public ManutencaoWSTerceiros(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManutencaoWSTerceiros(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns ManutencaoWSTerceirosSoap
     */
    @WebEndpoint(name = "ManutencaoWSTerceirosSoap")
    public ManutencaoWSTerceirosSoap getManutencaoWSTerceirosSoap() {
        return super.getPort(
                new QName(
                        "http://bgmrodotec.com.br/globus5/ManutencaoWsTerceiros",
                        "ManutencaoWSTerceirosSoap"),
                ManutencaoWSTerceirosSoap.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
     *                 Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ManutencaoWSTerceirosSoap
     */
    @WebEndpoint(name = "ManutencaoWSTerceirosSoap")
    public ManutencaoWSTerceirosSoap getManutencaoWSTerceirosSoap(WebServiceFeature... features) {
        return super.getPort(
                new QName(
                        "http://bgmrodotec.com.br/globus5/ManutencaoWsTerceiros",
                        "ManutencaoWSTerceirosSoap"),
                ManutencaoWSTerceirosSoap.class,
                features);
    }

    /**
     * @return returns ManutencaoWSTerceirosSoap
     */
    @WebEndpoint(name = "ManutencaoWSTerceirosSoap12")
    public ManutencaoWSTerceirosSoap getManutencaoWSTerceirosSoap12() {
        return super.getPort(
                new QName(
                        "http://bgmrodotec.com.br/globus5/ManutencaoWsTerceiros",
                        "ManutencaoWSTerceirosSoap12"),
                ManutencaoWSTerceirosSoap.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
     *                 Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ManutencaoWSTerceirosSoap
     */
    @WebEndpoint(name = "ManutencaoWSTerceirosSoap12")
    public ManutencaoWSTerceirosSoap getManutencaoWSTerceirosSoap12(WebServiceFeature... features) {
        return super.getPort(
                new QName(
                        "http://bgmrodotec.com.br/globus5/ManutencaoWsTerceiros",
                        "ManutencaoWSTerceirosSoap12"),
                ManutencaoWSTerceirosSoap.class,
                features);
    }

    private static URL __getWsdlLocation() {
        if (MANUTENCAOWSTERCEIROS_EXCEPTION != null) {
            throw MANUTENCAOWSTERCEIROS_EXCEPTION;
        }
        return MANUTENCAOWSTERCEIROS_WSDL_LOCATION;
    }
}
