-- Impede que um servico inserido não esteja vinculado a nenhuma das tabelas de mapeamento
-- Deve estar mapeado em MOVIMENTACAO_SERVICO_REALIZADO ou PNEU_SERVICO_CADASTRO;
CREATE OR REPLACE FUNCTION TG_FUNC_MAPEAMENTO_SERVICO_REALIZADO()
  RETURNS TRIGGER AS $MAPEAMENTO_SERVICO_REALIZADO_TRIGGER$
BEGIN
  IF ((NEW.CODIGO NOT IN (SELECT COD_SERVICO_REALIZADO
                          FROM MOVIMENTACAO_SERVICO_REALIZADO))
      AND (NEW.CODIGO NOT IN (SELECT COD_SERVICO
                              FROM PNEU_SERVICO_CADASTRO)))
  THEN
    RAISE EXCEPTION 'É necessário vincular o Serviço Realizado à uma tabela intermediária';
  END IF;
  RETURN NEW;
END;
$MAPEAMENTO_SERVICO_REALIZADO_TRIGGER$
LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER MAPEAMENTO_SERVICO_REALIZADO_TRIGGER
  AFTER INSERT OR UPDATE ON SERVICO_REALIZADO
  DEFERRABLE
  FOR EACH ROW
EXECUTE PROCEDURE TG_FUNC_MAPEAMENTO_SERVICO_REALIZADO();