--Mapeia histórico de alteração na tabela SUPORTE.FECHAMENTO_OS
CREATE TRIGGER TG_FUNC_AUDIT_FECHAMENTO_OS
    AFTER INSERT OR UPDATE
    ON SUPORTE.FECHAMENTO_OS
    FOR EACH ROW
EXECUTE PROCEDURE AUDIT.FUNC_AUDIT();