-- Cria tabela.
CREATE TABLE PICCOLOTUR.MODELO_CHECKLIST_INTEGRADO
(
    CODIGO               BIGSERIAL NOT NULL,
    COD_UNIDADE          BIGINT,
    COD_MODELO_CHECKLIST BIGINT,
    CONSTRAINT PK_MODELO_CHECKLIST_INTEGRADO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_COD_UNIDADE_COD_MODELO_CHECKLIST FOREIGN KEY (COD_UNIDADE, COD_MODELO_CHECKLIST)
        REFERENCES CHECKLIST_MODELO_DATA (COD_UNIDADE, CODIGO)
);