-- Corrige falta de acentos nos cabeçalhos do relatório.
DROP FUNCTION FUNC_CARGOS_RELATORIO_PERMISSOES_DETALHADAS(BIGINT[]);
CREATE OR REPLACE FUNCTION FUNC_CARGOS_RELATORIO_PERMISSOES_DETALHADAS(F_COD_UNIDADES BIGINT[])
    RETURNS TABLE
            (
                UNIDADE                 TEXT,
                CARGO                   TEXT,
                PILAR                   TEXT,
                "FUNCIONALIDADE PROLOG" TEXT,
                "PERMISSÃO PROLOG"      TEXT,
                "IMPACTO PERMISSÃO"     TEXT,
                "DESCRIÇÃO PERMISSÃO"   TEXT
            )
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    RETURN QUERY
        SELECT U.NOME ::TEXT       AS NOME_UNIDADE,
               F.NOME :: TEXT      AS NOME_CARGO,
               PP.PILAR ::TEXT     AS NOME_PILAR,
               FPA.NOME ::TEXT     AS NOME_FUNCIONALIDADE,
               FP.FUNCAO ::TEXT    AS NOME_PERMISSAO,
               FP.IMPACTO ::TEXT   AS IMPACTO_PERMISSAO,
               FP.DESCRICAO ::TEXT AS DESCRICAO_PERMISSAO
        FROM UNIDADE U
                 JOIN CARGO_FUNCAO_PROLOG_V11 CFP ON U.CODIGO = CFP.COD_UNIDADE
                 JOIN FUNCAO_PROLOG_V11 FP ON FP.CODIGO = CFP.COD_FUNCAO_PROLOG
                 JOIN PILAR_PROLOG PP ON CFP.COD_PILAR_PROLOG = PP.CODIGO
                 JOIN FUNCAO_PROLOG_AGRUPAMENTO FPA ON FPA.CODIGO = FP.COD_AGRUPAMENTO
                 JOIN FUNCAO F ON F.CODIGO = CFP.COD_FUNCAO_COLABORADOR
        WHERE U.CODIGO = ANY (F_COD_UNIDADES)
        ORDER BY NOME_UNIDADE ASC, NOME_CARGO ASC, FP.IMPACTO DESC;
END;
$$;