-- 2020-06-22 -> Adiciona data de import. (thaisksf - PL-2723).
DROP FUNCTION FUNC_RELATORIO_MAPA_ESTRATIFICADO(F_COD_UNIDADE BIGINT, F_DATA_INICIAL DATE, F_DATA_FINAL DATE);
CREATE FUNCTION FUNC_RELATORIO_MAPA_ESTRATIFICADO(F_COD_UNIDADE BIGINT, F_DATA_INICIAL DATE, F_DATA_FINAL DATE)
    RETURNS TABLE
            (
                DATA                           CHARACTER VARYING,
                PLACA                          CHARACTER VARYING,
                MAPA                           INTEGER,
                "MATRIC MOTORISTA"             INTEGER,
                "NOME MOTORISTA"               TEXT,
                "MATRIC AJUDANTE 1"            INTEGER,
                "NOME AJUDANTE 1"              TEXT,
                "MATRIC AJUDANTE 2"            INTEGER,
                "NOME AJUDANTE 2"              TEXT,
                ENTREGAS                       INTEGER,
                CXCARREG                       REAL,
                CXENTREG                       REAL,
                TRANSP                         INTEGER,
                ENTREGA                        CHARACTER VARYING,
                CARGAATUAL                     TEXT,
                FROTA                          TEXT,
                CUSTOSPOT                      REAL,
                REGIAO                         INTEGER,
                VEICULO                        INTEGER,
                VEICULOINDISP                  REAL,
                PLACAINDISP                    REAL,
                FROTAINDISP                    REAL,
                TIPOINDISP                     INTEGER,
                OCUPACAO                       REAL,
                CXROTA                         REAL,
                CXAS                           REAL,
                VEICBM                         REAL,
                RSHOW                          INTEGER,
                ENTRVOL                        CHARACTER VARYING,
                HRSAI                          TIMESTAMP WITHOUT TIME ZONE,
                HRENTR                         TIMESTAMP WITHOUT TIME ZONE,
                KMSAI                          INTEGER,
                KMENTR                         INTEGER,
                CUSTOVARIAVEL                  REAL,
                LUCRO                          REAL,
                LUCROUNIT                      REAL,
                VALORFRETE                     REAL,
                TIPOIMPOSTO                    CHARACTER VARYING,
                PERCIMPOSTO                    REAL,
                VALORIMPOSTO                   REAL,
                VALORFATURADO                  REAL,
                VALORUNITCXENTREGUE            REAL,
                VALORPGCXENTREGSEMIMP          REAL,
                VALORPGCXENTREGCOMIMP          REAL,
                TEMPOPREVISTOROAD              TIME WITHOUT TIME ZONE,
                KMPREVISTOROAD                 REAL,
                VALORUNITPONTOMOT              REAL,
                VALORUNITPONTOAJD              REAL,
                VALOREQUIPEENTRMOT             REAL,
                VALOREQUIPEENTRAJD             REAL,
                CUSTOVARIAVELCEDBZ             REAL,
                LUCROUNITCEDBZ                 REAL,
                LUCROVARIAVELCXENTREGUEFFCEDBZ REAL,
                TEMPOINTERNO                   TIME WITHOUT TIME ZONE,
                VALORDROPDOWN                  REAL,
                VEICCADDD                      CHARACTER VARYING,
                KMLACO                         REAL,
                KMDESLOCAMENTO                 REAL,
                TEMPOLACO                      TIME WITHOUT TIME ZONE,
                TEMPODESLOCAMENTO              TIME WITHOUT TIME ZONE,
                SITMULTICDD                    REAL,
                UNBORIGEM                      INTEGER,
                VALORCTEDIFERE                 CHARACTER VARYING,
                QTNFCARREGADAS                 INTEGER,
                QTNFENTREGUES                  INTEGER,
                INDDEVCX                       REAL,
                INDDEVNF                       REAL,
                FATOR                          REAL,
                RECARGA                        CHARACTER VARYING,
                HRMATINAL                      TIME WITHOUT TIME ZONE,
                HRJORNADALIQ                   TIME WITHOUT TIME ZONE,
                HRMETAJORNADA                  TIME WITHOUT TIME ZONE,
                VLBATEUJORNMOT                 REAL,
                VLNAOBATEUJORNMOT              REAL,
                VLRECARGAMOT                   REAL,
                VLBATEUJORNAJU                 REAL,
                VLNAOBATEUJORNAJU              REAL,
                VLRECARGAAJU                   REAL,
                VLTOTALMAPA                    REAL,
                QTHLCARREGADOS                 REAL,
                QTHLENTREGUES                  REAL,
                INDICEDEVHL                    REAL,
                REGIAO2                        CHARACTER VARYING,
                QTNFCARREGGERAL                INTEGER,
                QTNFENTREGGERAL                INTEGER,
                CAPACIDADEVEICULOKG            REAL,
                PESOCARGAKG                    REAL,
                CAPACVEICULOCX                 INTEGER,
                ENTREGASCOMPLETAS              INTEGER,
                ENTREGASPARCIAIS               INTEGER,
                ENTREGASNAOREALIZADAS          INTEGER,
                CODFILIAL                      INTEGER,
                NOMEFILIAL                     CHARACTER VARYING,
                CODSUPERVTRS                   INTEGER,
                NOMESUPERVTRS                  CHARACTER VARYING,
                CODSPOT                        INTEGER,
                NOMESPOT                       TEXT,
                EQUIPCARREGADOS                INTEGER,
                EQUIPDEVOLVIDOS                INTEGER,
                EQUIPRECOLHIDOS                INTEGER,
                CXENTREGTRACKING               REAL,
                HRCARREG                       TIMESTAMP WITHOUT TIME ZONE,
                HRPCFISICA                     TIMESTAMP WITHOUT TIME ZONE,
                HRPCFINANCEIRA                 TIMESTAMP WITHOUT TIME ZONE,
                STMAPA                         CHARACTER VARYING,
                TOTALAPONTAMENTOSTRACKING      BIGINT,
                APONTAMENTOSOK                 BIGINT,
                APONTAMENTOSNOK                BIGINT,
                ADERENCIA                      DOUBLE PRECISION,
                DATA_HORA_IMPORT               CHARACTER VARYING
            )
    LANGUAGE SQL
AS
$$
SELECT to_char(M.DATA, 'DD/MM/YYYY'),
       PLACA,
       MAPA,
       MATRICMOTORISTA,
       coalesce(MOTORISTA.NOME, '-')                          AS NOME_MOTORISTA,
       MATRICAJUD1,
       coalesce(AJUDANTE1.NOME, '-')                          AS NOME_AJUDANTE1,
       MATRICAJUD2,
       coalesce(AJUDANTE2.NOME, '-')                          AS NOME_AJUDANTE2,
       ENTREGAS,
       CXCARREG,
       CXENTREG,
       TRANSP,
       ENTREGA,
       CARGAATUAL,
       FROTA,
       CUSTOSPOT,
       REGIAO,
       VEICULO,
       VEICULOINDISP,
       PLACAINDISP,
       FROTAINDISP,
       TIPOINDISP,
       OCUPACAO,
       CXROTA,
       CXAS,
       VEICBM,
       RSHOW,
       ENTRVOL,
       HRSAI,
       HRENTR,
       KMSAI,
       KMENTR,
       CUSTOVARIAVEL,
       LUCRO,
       LUCROUNIT,
       VALORFRETE,
       TIPOIMPOSTO,
       PERCIMPOSTO,
       VALORIMPOSTO,
       VALORFATURADO,
       VALORUNITCXENTREGUE,
       VALORPGCXENTREGSEMIMP,
       VALORPGCXENTREGCOMIMP,
       TEMPOPREVISTOROAD,
       KMPREVISTOROAD,
       VALORUNITPONTOMOT,
       VALORUNITPONTOAJD,
       VALOREQUIPEENTRMOT,
       VALOREQUIPEENTRAJD,
       CUSTOVARIAVELCEDBZ,
       LUCROUNITCEDBZ,
       LUCROVARIAVELCXENTREGUEFFCEDBZ,
       TEMPOINTERNO,
       VALORDROPDOWN,
       VEICCADDD,
       KMLACO,
       KMDESLOCAMENTO,
       TEMPOLACO,
       TEMPODESLOCAMENTO,
       SITMULTICDD,
       UNBORIGEM,
       VALORCTEDIFERE,
       QTNFCARREGADAS,
       QTNFENTREGUES,
       INDDEVCX,
       INDDEVNF,
       FATOR,
       RECARGA,
       HRMATINAL,
       HRJORNADALIQ,
       HRMETAJORNADA,
       VLBATEUJORNMOT,
       VLNAOBATEUJORNMOT,
       VLRECARGAMOT,
       VLBATEUJORNAJU,
       VLNAOBATEUJORNAJU,
       VLRECARGAAJU,
       VLTOTALMAPA,
       QTHLCARREGADOS,
       QTHLENTREGUES,
       INDICEDEVHL,
       REGIAO2,
       QTNFCARREGGERAL,
       QTNFENTREGGERAL,
       CAPACIDADEVEICULOKG,
       PESOCARGAKG,
       CAPACVEICULOCX,
       ENTREGASCOMPLETAS,
       ENTREGASPARCIAIS,
       ENTREGASNAOREALIZADAS,
       CODFILIAL,
       NOMEFILIAL,
       CODSUPERVTRS,
       NOMESUPERVTRS,
       CODSPOT,
       NOMESPOT,
       EQUIPCARREGADOS,
       EQUIPDEVOLVIDOS,
       EQUIPRECOLHIDOS,
       CXENTREGTRACKING,
       HRCARREG,
       HRPCFISICA,
       HRPCFINANCEIRA,
       STMAPA,
       TRACKING.TOTAL_APONTAMENTOS,
       TRACKING.APONTAMENTOS_OK,
       TRACKING.TOTAL_APONTAMENTOS - TRACKING.APONTAMENTOS_OK AS APONTAMENTOS_NOK,
       TRUNC((TRACKING.APONTAMENTOS_OK :: FLOAT / TRACKING.TOTAL_APONTAMENTOS) * 100),
       TO_CHAR(M.DATA_HORA_IMPORT, 'DD/MM/YYYY HH24:MI')
FROM MAPA M
         JOIN UNIDADE_FUNCAO_PRODUTIVIDADE UFP ON UFP.COD_UNIDADE = M.COD_UNIDADE
         LEFT JOIN COLABORADOR MOTORISTA
                   ON MOTORISTA.COD_UNIDADE = M.COD_UNIDADE AND MOTORISTA.COD_FUNCAO = UFP.COD_FUNCAO_MOTORISTA
                       AND MOTORISTA.MATRICULA_AMBEV = M.MATRICMOTORISTA
         LEFT JOIN COLABORADOR AJUDANTE1
                   ON AJUDANTE1.COD_UNIDADE = M.COD_UNIDADE AND AJUDANTE1.COD_FUNCAO = UFP.COD_FUNCAO_AJUDANTE
                       AND AJUDANTE1.MATRICULA_AMBEV = M.MATRICAJUD1
         LEFT JOIN COLABORADOR AJUDANTE2
                   ON AJUDANTE2.COD_UNIDADE = M.COD_UNIDADE AND AJUDANTE2.COD_FUNCAO = UFP.COD_FUNCAO_AJUDANTE
                       AND AJUDANTE2.MATRICULA_AMBEV = M.MATRICAJUD2
         LEFT JOIN (SELECT T.MAPA                         AS TRACKING_MAPA,
                           T.código_transportadora           TRACKING_UNIDADE,
                           COUNT(T.DISP_APONT_CADASTRADO) AS TOTAL_APONTAMENTOS,
                           SUM(CASE
                                   WHEN T.DISP_APONT_CADASTRADO <= UM.META_RAIO_TRACKING
                                       THEN 1
                                   ELSE 0 END)            AS APONTAMENTOS_OK
                    FROM TRACKING T
                             JOIN UNIDADE_METAS UM ON UM.COD_UNIDADE = T.código_transportadora
                    GROUP BY 1, 2) AS TRACKING ON TRACKING_MAPA = M.MAPA AND TRACKING_UNIDADE = M.COD_UNIDADE
WHERE M.COD_UNIDADE = F_COD_UNIDADE
  AND M.DATA BETWEEN (F_DATA_INICIAL AT TIME ZONE (SELECT TIMEZONE FROM func_get_time_zone_unidade(F_COD_UNIDADE)))
    AND (F_DATA_FINAL AT TIME ZONE (SELECT TIMEZONE FROM func_get_time_zone_unidade(F_COD_UNIDADE)))
ORDER BY M.MAPA
$$;