-- Deleta serviços em aberto e que possuem pneus em unidade diferente dos serviços.
WITH CTE AS (
    SELECT AMD.CODIGO AS COD_SERVICO
    FROM AFERICAO_MANUTENCAO_DATA AMD
             JOIN
         PNEU_DATA PD ON AMD.COD_PNEU = PD.CODIGO
    WHERE AMD.DELETADO IS FALSE
      AND PD.COD_UNIDADE <> AMD.COD_UNIDADE
      AND AMD.DATA_HORA_RESOLUCAO IS NULL
      AND AMD.FECHADO_AUTOMATICAMENTE_INTEGRACAO IS FALSE
      AND AMD.FECHADO_AUTOMATICAMENTE_MOVIMENTACAO IS FALSE
      AND PD.COD_EMPRESA NOT IN (SELECT VTBDO.COD_EMPRESA
                                FROM VEICULO_TRANSFERENCIA_BLOQUEIO_DELECAO_OS VTBDO
                                WHERE VTBDO.BLOQUEAR_DELECAO_SERVICOS_PNEU IS TRUE)
)
UPDATE AFERICAO_MANUTENCAO_DATA
SET DELETADO            = TRUE,
    DATA_HORA_DELETADO  = NOW(),
    MOTIVO_DELECAO      = 'PL-2661',
    PG_USERNAME_DELECAO = SESSION_USER
FROM CTE
WHERE CODIGO = CTE.COD_SERVICO;

-- Deleta itens de OS de checklist que estavam em aberto e que possuem veículos em unidade diferente das OSs.
WITH CTE AS (
    SELECT CD.CODIGO AS COD_CHECKLIST, COSD.CODIGO AS COD_ORDEM_SERVICO, COSID.CODIGO AS COD_ITENS_OS
    FROM CHECKLIST_ORDEM_SERVICO_DATA COSD
             JOIN CHECKLIST_DATA CD ON COSD.COD_CHECKLIST = CD.CODIGO
             JOIN CHECKLIST_ORDEM_SERVICO_ITENS_DATA COSID
                  ON COSD.CODIGO = COSID.COD_OS AND COSD.COD_UNIDADE = COSID.COD_UNIDADE
             JOIN VEICULO_DATA VD ON CD.PLACA_VEICULO = VD.PLACA
    WHERE COSID.DATA_HORA_INICIO_RESOLUCAO IS NULL
      AND COSID.DELETADO IS FALSE
      AND COSD.DATA_HORA_FECHAMENTO IS NULL
      AND COSD.DELETADO IS FALSE
      AND CD.COD_UNIDADE <> VD.COD_UNIDADE
      AND VD.COD_EMPRESA NOT IN (SELECT VTBDO.COD_EMPRESA
                                 FROM VEICULO_TRANSFERENCIA_BLOQUEIO_DELECAO_OS VTBDO
                                 WHERE VTBDO.BLOQUEAR_DELECAO_OS_CHECKLIST IS TRUE)
)
UPDATE CHECKLIST_ORDEM_SERVICO_ITENS_DATA
SET DELETADO            = TRUE,
    DATA_HORA_DELETADO  = NOW(),
    MOTIVO_DELECAO      = 'PL-2661',
    PG_USERNAME_DELECAO = SESSION_USER
FROM CTE
WHERE CODIGO = CTE.COD_ITENS_OS
  AND COD_OS = CTE.COD_ORDEM_SERVICO;

-- Deleta as OS de checklist que estavam em aberto e que possuem veículos em unidade diferente das OSs.
WITH CTE AS (
    SELECT DISTINCT ON (COSD.COD_UNIDADE, COSD.CODIGO, COSD.COD_CHECKLIST) COSD.COD_UNIDADE   AS COD_UNIDADE_OS,
                                                                           COSD.CODIGO        AS COD_OS,
                                                                           COSD.COD_CHECKLIST AS COD_CHECK
    FROM CHECKLIST_DATA CD
             JOIN VEICULO_DATA VD
                  ON CD.PLACA_VEICULO = VD.PLACA
             JOIN CHECKLIST_ORDEM_SERVICO_DATA COSD
                  ON COSD.COD_CHECKLIST = CD.CODIGO
    WHERE COSD.DATA_HORA_FECHAMENTO IS NULL
      AND COSD.DELETADO IS FALSE
      AND CD.COD_UNIDADE <> VD.COD_UNIDADE
      AND VD.COD_EMPRESA NOT IN (SELECT VTBDO.COD_EMPRESA
                                 FROM VEICULO_TRANSFERENCIA_BLOQUEIO_DELECAO_OS VTBDO
                                 WHERE VTBDO.BLOQUEAR_DELECAO_OS_CHECKLIST IS TRUE)
)
UPDATE CHECKLIST_ORDEM_SERVICO_DATA
SET DELETADO            = TRUE,
    DATA_HORA_DELETADO  = NOW(),
    MOTIVO_DELECAO      = 'PL-2661',
    PG_USERNAME_DELECAO = SESSION_USER
FROM CTE
WHERE CODIGO = CTE.COD_OS
  AND COD_CHECKLIST = CTE.COD_CHECK;

-- DESDELETA AS OS JÁ POSSUÍAM ITENS FECHADOS ANTES DE DELETAR OS ITENS ABERTOS
UPDATE CHECKLIST_ORDEM_SERVICO_DATA COSD
SET DELETADO             = FALSE,
    DATA_HORA_DELETADO   = NULL,
    MOTIVO_DELECAO       = NULL,
    PG_USERNAME_DELECAO  = NULL,
    STATUS               = 'F',
    DATA_HORA_FECHAMENTO = (SELECT MAX(COSI.DATA_HORA_CONSERTO)
                            FROM CHECKLIST_ORDEM_SERVICO_ITENS_DATA COSI
                            WHERE COSI.COD_OS = CODIGO
                              AND COSI.COD_UNIDADE = COD_UNIDADE
                              AND COSI.DELETADO = FALSE)
WHERE COSD.MOTIVO_DELECAO = 'PL-2661'
  AND COSD.DELETADO = TRUE
  AND (COSD.CODIGO, COSD.COD_UNIDADE) IN (SELECT COSID.COD_OS, COSID.COD_UNIDADE
                                          FROM CHECKLIST_ORDEM_SERVICO_ITENS_DATA COSID
                                          WHERE COSID.DELETADO IS FALSE
                                            AND COSID.DATA_HORA_CONSERTO IS NOT NULL);