CREATE OR REPLACE FUNCTION FUNC_PNEU_RELATORIO_STATUS_PLACAS_AFERICAO(
  F_COD_UNIDADES        BIGINT [],
  F_DATA_HORA_ATUAL_UTC TIMESTAMP WITH TIME ZONE)
  RETURNS TABLE(
    TOTAL_VENCIDAS BIGINT,
    TOTAL_NO_PRAZO BIGINT)
LANGUAGE PLPGSQL
AS $$
DECLARE
  QTD_PLACAS_ATIVAS BIGINT := (SELECT COUNT(V.PLACA)
                               FROM VEICULO V
                               WHERE V.COD_UNIDADE = ANY (F_COD_UNIDADES) AND V.STATUS_ATIVO = TRUE);
BEGIN
  RETURN QUERY
  WITH QTD_PLACAS_VENCIDAS AS (
      SELECT (SELECT COUNT(PLACA)
              FROM FUNC_AFERICAO_RELATORIO_QTD_DIAS_PLACAS_VENCIDAS(F_COD_UNIDADES,
                                                                    F_DATA_HORA_ATUAL_UTC)) AS QTD_VENCIDAS
  )

  SELECT
    QPV.QTD_VENCIDAS                     AS QTD_VENCIDAS,
    QTD_PLACAS_ATIVAS - QPV.QTD_VENCIDAS AS QTD_PRAZO
  FROM QTD_PLACAS_VENCIDAS QPV;
END;
$$;