CREATE OR REPLACE FUNCTION FUNC_AFERICAO_RELATORIO_QTD_AFERICOES_REALIZADAS_POR_DIA(
  F_COD_UNIDADES BIGINT[],
  F_DATA_HOJE_UTC TIMESTAMP WITH TIME ZONE,
  F_DIAS_RETROATIVOS_PARA_BUSCAR BIGINT)
  RETURNS TABLE(
    DATA DATE,
    DATA_FORMATADA TEXT,
    QTD_AFERICAO_SULCO BIGINT,
    QTD_AFERICAO_PRESSAO BIGINT,
    QTD_AFERICAO_SULCO_PRESSAO BIGINT)
LANGUAGE PLPGSQL
AS $$
DECLARE
  DATA_INICIAL            DATE := F_DATA_HOJE_UTC + INTERVAL '1' DAY
                                  - (INTERVAL '1' DAY * F_DIAS_RETROATIVOS_PARA_BUSCAR);
  DATA_FINAL              DATE := F_DATA_HOJE_UTC + INTERVAL '1' DAY;
  AFERICAO_SULCO          VARCHAR := 'SULCO';
  AFERICAO_PRESSAO        VARCHAR := 'PRESSAO';
  AFERICAO_SULCO_PRESSAO  VARCHAR := 'SULCO_PRESSAO';
BEGIN
  RETURN QUERY

  WITH DIAS AS (
      SELECT G.DAY :: DATE AS DATA
      FROM GENERATE_SERIES(DATA_INICIAL, DATA_FINAL, '1 DAY') G(DAY)
      ORDER BY DATA
  ),

  AFERICOES_DIA AS (
    SELECT
      (A.DATA_HORA AT TIME ZONE TZ_UNIDADE(A.COD_UNIDADE)) :: DATE AS DATA,
      SUM(CASE WHEN A.TIPO_MEDICAO_COLETADA = AFERICAO_SULCO THEN 1 ELSE 0 END)  QTD_AFERICAO_SULCO,
      SUM(CASE WHEN A.TIPO_MEDICAO_COLETADA = AFERICAO_PRESSAO THEN 1 ELSE 0 END)  QTD_AFERICAO_PRESSAO,
      SUM(CASE WHEN A.TIPO_MEDICAO_COLETADA = AFERICAO_SULCO_PRESSAO THEN 1 ELSE 0 END)  QTD_AFERICAO_SULCO_PRESSAO
    FROM AFERICAO A
    WHERE
      A.COD_UNIDADE = ANY (F_COD_UNIDADES)
      AND (A.DATA_HORA AT TIME ZONE TZ_UNIDADE(A.COD_UNIDADE)) :: DATE BETWEEN DATA_INICIAL AND DATA_FINAL
    GROUP BY DATA
    ORDER BY DATA
  )

  SELECT
    D.DATA                          AS DATA,
    TO_CHAR(D.DATA, 'DD/MM')        AS DATA_FORMATADA,
    AD.QTD_AFERICAO_SULCO           AS QTD_AFERICAO_SULCO,
    AD.QTD_AFERICAO_PRESSAO         AS QTD_AFERICAO_PRESSAO,
    AD.QTD_AFERICAO_SULCO_PRESSAO   AS QTD_AFERICAO_SULCO_PRESSAO
  FROM DIAS D
    LEFT JOIN AFERICOES_DIA AD ON D.DATA = AD.DATA
  ORDER BY D.DATA;
END;
$$;