CREATE OR REPLACE FUNCTION FUNC_MARCACAO_GET_LISTAGEM_MARCACOES(
  F_COD_UNIDADE        BIGINT,
  F_CPF_COLABORADOR    BIGINT,
  F_COD_TIPO_INTERVALO BIGINT,
  F_DATA_INICIAL       DATE,
  F_DATA_FINAL         DATE)
  RETURNS TABLE(
    FONTE_DATA_HORA_INICIO          TEXT,
    FONTE_DATA_HORA_FIM             TEXT,
    JUSTIFICATIVA_ESTOURO           TEXT,
    JUSTIFICATIVA_TEMPO_RECOMENDADO TEXT,
    LATITUDE_MARCACAO_INICIO        TEXT,
    LONGITUDE_MARCACAO_INICIO       TEXT,
    LATITUDE_MARCACAO_FIM           TEXT,
    LONGITUDE_MARCACAO_FIM          TEXT,
    COD_UNIDADE                     BIGINT,
    CPF_COLABORADOR                 TEXT,
    NOME_COLABORADOR                TEXT,
    COD_TIPO_INTERVALO_POR_UNIDADE  BIGINT,
    COD_TIPO_INTERVALO              BIGINT,
    NOME_TIPO_INTERVALO             TEXT,
    ICONE_TIPO_INTERVALO            TEXT,
    TEMPO_RECOMENDADO_MINUTOS       BIGINT,
    TEMPO_ESTOURO_MINUTOS           BIGINT,
    DATA_HORA_INICIO                TIMESTAMP WITHOUT TIME ZONE,
    DATA_HORA_FIM                   TIMESTAMP WITHOUT TIME ZONE,
    DURACAO_EM_SEGUNDOS             BIGINT,
    COD_MARCACAO_VINCULO            BIGINT,
    COD_MARCACAO_INICIO             BIGINT,
    COD_MARCACAO_FIM                BIGINT,
    STATUS_ATIVO_INICIO             BOOLEAN,
    STATUS_ATIVO_FIM                BOOLEAN,
    FOI_AJUSTADO_INICIO             BOOLEAN,
    FOI_AJUSTADO_FIM                BOOLEAN,
    DATA_HORA_SINCRONIZACAO_INICIO  TIMESTAMP WITHOUT TIME ZONE,
    DATA_HORA_SINCRONIZACAO_FIM     TIMESTAMP WITHOUT TIME ZONE,
    TIPO_JORNADA                    BOOLEAN)
LANGUAGE PLPGSQL
AS $$
DECLARE
  F_TIME_ZONE_UNIDADE TEXT := TZ_UNIDADE(F_COD_UNIDADE);
BEGIN
  RETURN QUERY
  WITH INTERVALOS AS (
      SELECT IT.*
      FROM INTERVALO IT
      WHERE IT.COD_UNIDADE = F_COD_UNIDADE
            AND F_IF(F_CPF_COLABORADOR IS NULL, TRUE, IT.CPF_COLABORADOR = F_CPF_COLABORADOR)
            AND F_IF(F_COD_TIPO_INTERVALO IS NULL, TRUE, IT.COD_TIPO_INTERVALO = F_COD_TIPO_INTERVALO)
            AND ((IT.DATA_HORA AT TIME ZONE F_TIME_ZONE_UNIDADE) :: DATE >= F_DATA_INICIAL
                 AND (IT.DATA_HORA AT TIME ZONE F_TIME_ZONE_UNIDADE) :: DATE <= F_DATA_FINAL)),
      INICIOS AS (
        SELECT
          MI.COD_MARCACAO_INICIO                AS COD_MARCACAO_INICIO,
          MV.COD_MARCACAO_FIM                   AS COD_MARCACAO_VINCULO,
          I.FONTE_DATA_HORA                     AS FONTE_DATA_HORA_INICIO,
          I.LATITUDE_MARCACAO                   AS LATITUDE_MARCACAO_INICIO,
          I.LONGITUDE_MARCACAO                  AS LONGITUDE_MARCACAO_INICIO,
          I.COD_UNIDADE                         AS COD_UNIDADE,
          I.CPF_COLABORADOR                     AS CPF_COLABORADOR,
          CO.NOME                               AS NOME_COLABORADOR,
          I.COD_TIPO_INTERVALO                  AS COD_TIPO_INTERVALO,
          VIT.NOME                              AS NOME_TIPO_INTERVALO,
          VIT.ICONE                             AS ICONE_TIPO_INTERVALO,
          VIT.TEMPO_RECOMENDADO_MINUTOS         AS TEMPO_RECOMENDADO_MINUTOS,
          VIT.TEMPO_ESTOURO_MINUTOS             AS TEMPO_ESTOURO_MINUTOS,
          I.DATA_HORA                           AS DATA_HORA,
          I.CODIGO                              AS CODIGO_INICIO,
          I.STATUS_ATIVO                        AS STATUS_ATIVO_INICIO,
          I.FOI_AJUSTADO                        AS FOI_AJUSTADO_INICIO,
          I.DATA_HORA_SINCRONIZACAO             AS DATA_HORA_SINCRONIZACAO_INICIO,
          VIT.CODIGO_TIPO_INTERVALO_POR_UNIDADE AS COD_TIPO_INTERVALO_POR_UNIDADE,
          VIT.TIPO_JORNADA                      AS TIPO_JORNADA
        FROM MARCACAO_INICIO MI
          LEFT JOIN MARCACAO_VINCULO_INICIO_FIM MV ON MI.COD_MARCACAO_INICIO = MV.COD_MARCACAO_INICIO
          JOIN INTERVALOS I ON MI.COD_MARCACAO_INICIO = I.CODIGO
          JOIN COLABORADOR CO ON CO.CPF = I.CPF_COLABORADOR
          JOIN VIEW_INTERVALO_TIPO VIT ON I.COD_TIPO_INTERVALO = VIT.CODIGO),
      FINS AS (
        SELECT
          MF.COD_MARCACAO_FIM                   AS COD_MARCACAO_FIM,
          MV.COD_MARCACAO_INICIO                AS COD_MARCACAO_VINCULO,
          F.FONTE_DATA_HORA                     AS FONTE_DATA_HORA_FIM,
          F.JUSTIFICATIVA_ESTOURO               AS JUSTIFICATIVA_ESTOURO,
          F.JUSTIFICATIVA_TEMPO_RECOMENDADO     AS JUSTIFICATIVA_TEMPO_RECOMENDADO,
          F.LATITUDE_MARCACAO                   AS LATITUDE_MARCACAO_FIM,
          F.LONGITUDE_MARCACAO                  AS LONGITUDE_MARCACAO_FIM,
          F.COD_UNIDADE                         AS COD_UNIDADE,
          F.CPF_COLABORADOR                     AS CPF_COLABORADOR,
          CO.NOME                               AS NOME_COLABORADOR,
          F.COD_TIPO_INTERVALO                  AS COD_TIPO_INTERVALO,
          VIT.NOME                              AS NOME_TIPO_INTERVALO,
          VIT.ICONE                             AS ICONE_TIPO_INTERVALO,
          VIT.TEMPO_RECOMENDADO_MINUTOS         AS TEMPO_RECOMENDADO_MINUTOS,
          VIT.TEMPO_ESTOURO_MINUTOS             AS TEMPO_ESTOURO_MINUTOS,
          F.DATA_HORA                           AS DATA_HORA,
          F.CODIGO                              AS CODIGO_FIM,
          F.STATUS_ATIVO                        AS STATUS_ATIVO_FIM,
          F.FOI_AJUSTADO                        AS FOI_AJUSTADO_FIM,
          F.DATA_HORA_SINCRONIZACAO             AS DATA_HORA_SINCRONIZACAO_FIM,
          VIT.CODIGO_TIPO_INTERVALO_POR_UNIDADE AS COD_TIPO_INTERVALO_POR_UNIDADE,
          VIT.TIPO_JORNADA                      AS TIPO_JORNADA
        FROM MARCACAO_FIM MF
          LEFT JOIN MARCACAO_VINCULO_INICIO_FIM MV ON MF.COD_MARCACAO_FIM = MV.COD_MARCACAO_FIM
          JOIN INTERVALOS F ON MF.COD_MARCACAO_FIM = F.CODIGO
          JOIN COLABORADOR CO ON CO.CPF = F.CPF_COLABORADOR
          JOIN VIEW_INTERVALO_TIPO VIT ON F.COD_TIPO_INTERVALO = VIT.CODIGO)

  SELECT
    COALESCE(IC.FONTE_DATA_HORA_INICIO, IVI.FONTE_DATA_HORA) :: TEXT              AS FONTE_DATA_HORA_INICIO,
    COALESCE(F.FONTE_DATA_HORA_FIM, IVF.FONTE_DATA_HORA) :: TEXT                  AS FONTE_DATA_HORA_FIM,
    F.JUSTIFICATIVA_ESTOURO                                                       AS JUSTIFICATIVA_ESTOURO,
    F.JUSTIFICATIVA_TEMPO_RECOMENDADO                                             AS JUSTIFICATIVA_TEMPO_RECOMENDADO,
    COALESCE(IC.LATITUDE_MARCACAO_INICIO, IVI.LATITUDE_MARCACAO)                  AS LATITUDE_MARCACAO_INICIO,
    COALESCE(IC.LONGITUDE_MARCACAO_INICIO, IVI.LONGITUDE_MARCACAO)                AS LONGITUDE_MARCACAO_INICIO,
    COALESCE(F.LATITUDE_MARCACAO_FIM, IVF.LATITUDE_MARCACAO)                      AS LATITUDE_MARCACAO_FIM,
    COALESCE(F.LONGITUDE_MARCACAO_FIM, IVF.LONGITUDE_MARCACAO)                    AS LONGITUDE_MARCACAO_FIM,
    COALESCE(IC.COD_UNIDADE, F.COD_UNIDADE)                                       AS COD_UNIDADE,
    LPAD(COALESCE(IC.CPF_COLABORADOR, F.CPF_COLABORADOR) :: TEXT, 11, '0')        AS CPF_COLABORADOR,
    COALESCE(IC.NOME_COLABORADOR, F.NOME_COLABORADOR) :: TEXT                     AS NOME_COLABORADOR,
    COALESCE(IC.COD_TIPO_INTERVALO_POR_UNIDADE,
             F.COD_TIPO_INTERVALO_POR_UNIDADE)                                    AS COD_TIPO_INTERVALO_POR_UNIDADE,
    COALESCE(IC.COD_TIPO_INTERVALO, F.COD_TIPO_INTERVALO)                         AS COD_TIPO_INTERVALO,
    COALESCE(IC.NOME_TIPO_INTERVALO, F.NOME_TIPO_INTERVALO) :: TEXT               AS NOME_TIPO_INTERVALO,
    COALESCE(IC.ICONE_TIPO_INTERVALO, F.ICONE_TIPO_INTERVALO) :: TEXT             AS ICONE_TIPO_INTERVALO,
    COALESCE(IC.TEMPO_RECOMENDADO_MINUTOS, F.TEMPO_RECOMENDADO_MINUTOS) :: BIGINT AS TEMPO_RECOMENDADO_MINUTOS,
    COALESCE(IC.TEMPO_ESTOURO_MINUTOS, F.TEMPO_ESTOURO_MINUTOS) :: BIGINT         AS TEMPO_ESTOURO_MINUTOS,
    COALESCE(IC.DATA_HORA, IVI.DATA_HORA) AT TIME ZONE F_TIME_ZONE_UNIDADE        AS DATA_HORA_INICIO,
    COALESCE(F.DATA_HORA, IVF.DATA_HORA) AT TIME ZONE F_TIME_ZONE_UNIDADE         AS DATA_HORA_FIM,
    TO_SECONDS(COALESCE(F.DATA_HORA, IVF.DATA_HORA) -
               COALESCE(IC.DATA_HORA, IVI.DATA_HORA))                             AS DURACAO_EM_SEGUNDOS,
    COALESCE(IC.COD_MARCACAO_VINCULO, F.COD_MARCACAO_VINCULO)                     AS COD_MARCACAO_VINCULO,
    COALESCE(IC.CODIGO_INICIO, IVI.CODIGO)                                        AS COD_MARCACAO_INICIO,
    COALESCE(F.CODIGO_FIM, IVF.CODIGO)                                            AS COD_MARCACAO_FIM,
    COALESCE(IC.STATUS_ATIVO_INICIO, IVI.STATUS_ATIVO)                            AS STATUS_ATIVO_INICIO,
    COALESCE(F.STATUS_ATIVO_FIM, IVF.STATUS_ATIVO)                                AS STATUS_ATIVO_FIM,
    COALESCE(IC.FOI_AJUSTADO_INICIO, IVI.FOI_AJUSTADO)                            AS FOI_AJUSTADO_INICIO,
    COALESCE(F.FOI_AJUSTADO_FIM, IVF.FOI_AJUSTADO)                                AS FOI_AJUSTADO_FIM,
    COALESCE(IC.DATA_HORA_SINCRONIZACAO_INICIO,
             IVI.DATA_HORA_SINCRONIZACAO) AT TIME ZONE
    F_TIME_ZONE_UNIDADE                                                           AS DATA_HORA_SINCRONIZACAO_INICIO,
    COALESCE(F.DATA_HORA_SINCRONIZACAO_FIM, IVF.DATA_HORA_SINCRONIZACAO) AT TIME ZONE
    F_TIME_ZONE_UNIDADE                                                           AS DATA_HORA_SINCRONIZACAO_FIM,
    (F.TIPO_JORNADA = TRUE OR IC.TIPO_JORNADA = TRUE)                             AS TIPO_JORNADA
  FROM INICIOS IC
    FULL OUTER JOIN FINS F ON IC.COD_MARCACAO_VINCULO = F.COD_MARCACAO_FIM
    -- Com esses últimos left joins com INTERVALO garantimos que será buscado inícios ou fins vinculados a marcações
    -- que estão fora do filtro de data aplicado na primeira CTE INTERVALOS.
    -- Exemplo: se filtramos de 01/01/19 a 31/01/19 e temos uma marcação iniciada em 31/01/19 e finalizada em 01/02/19,
    -- sem esses left joins, esse fim não seria buscado.
    LEFT JOIN INTERVALO IVI ON IVI.CODIGO = F.COD_MARCACAO_VINCULO
    LEFT JOIN INTERVALO IVF ON IVF.CODIGO = IC.COD_MARCACAO_VINCULO
  ORDER BY
    CPF_COLABORADOR,
    COD_TIPO_INTERVALO,
    COALESCE(DATA_HORA_INICIO, DATA_HORA_FIM);
END;
$$;