
package br.com.zalf.prolog.webservice.integracao.avacorpavilan.deprecated.checklist.service;

import br.com.zalf.prolog.webservice.integracao.avacorpavilan.deprecated.AvaCorpAvilanConstants;
import br.com.zalf.prolog.webservice.integracao.avacorpavilan.deprecated.checklist.*;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChecklistSoap", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChecklistAvaCorpAvilanSoap {


    /**
     * Adicionar nova avaliação e retorna as questões
     *
     * @param questionario
     * @return
     *     returns br.com.avacorp.integracaoprolog.PerguntasAlternativasQuestionario
     */
    @WebMethod(action = AvaCorpAvilanConstants.NAMESPACE + "/buscarPerguntasAlternativasQuestionario")
    @WebResult(name = "buscarPerguntasAlternativasQuestionarioResult", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
    @RequestWrapper(localName = "buscarPerguntasAlternativasQuestionario", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.BuscarPerguntasAlternativasQuestionario")
    @ResponseWrapper(localName = "buscarPerguntasAlternativasQuestionarioResponse", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.BuscarPerguntasAlternativasQuestionarioResponse")
    public PerguntasAlternativasQuestionario buscarPerguntasAlternativasQuestionario(
            @WebParam(name = "questionario", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    AdicionarChecklist questionario);

    /**
     * Questionarios para um veiculo
     *
     * @param cpf
     * @return
     *     returns br.com.avacorp.integracaoprolog.BuscaQuestionarioColaborador
     */
    @WebMethod(action = AvaCorpAvilanConstants.NAMESPACE + "/buscarQuestionariosColaborador")
    @WebResult(name = "buscarQuestionariosColaboradorResult", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
    @RequestWrapper(localName = "buscarQuestionariosColaborador", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.BuscarQuestionariosColaborador")
    @ResponseWrapper(localName = "buscarQuestionariosColaboradorResponse", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.BuscarQuestionariosColaboradorResponse")
    public BuscaQuestionarioColaborador buscarQuestionariosColaborador(
            @WebParam(name = "cpf", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String cpf);

    /**
     * Processa as respostas de uma avaliação
     *
     * @param respostas
     * @return
     *     returns br.com.avacorp.integracaoprolog.EnviaRespostaAvaliacao
     */
    @WebMethod(action = AvaCorpAvilanConstants.NAMESPACE + "/enviarChecklist")
    @WebResult(name = "enviarChecklistResult", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
    @RequestWrapper(localName = "enviarChecklist", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.EnviarChecklist")
    @ResponseWrapper(localName = "enviarChecklistResponse", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.EnviarChecklistResponse")
    public EnviaRespostaAvaliacao enviarChecklist(
            @WebParam(name = "respostas", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    RespostasAvaliacao respostas);

    /**
     * Farol
     *
     * @param filial
     * @param unidade
     * @param dataInicial
     * @param buscarRetroativo
     * @param dataFinal
     * @return
     *     returns br.com.avacorp.integracaoprologtestes.FarolChecklist2
     */
    @WebMethod(action = AvaCorpAvilanConstants.NAMESPACE + "/farolChecklist")
    @WebResult(name = "farolChecklistResult", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
    @RequestWrapper(localName = "farolChecklist", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.FarolChecklist")
    @ResponseWrapper(localName = "farolChecklistResponse", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.FarolChecklistResponse")
    public FarolChecklist2 farolChecklist(
            @WebParam(name = "filial", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    int filial,
            @WebParam(name = "unidade", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    int unidade,
            @WebParam(name = "dataInicial", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String dataInicial,
            @WebParam(name = "dataFinal", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String dataFinal,
            @WebParam(name = "buscarRetroativo", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    boolean buscarRetroativo);

    /**
     * Buscar checklists
     *
     * @param veiculo
     * @param tipoVeiculo
     * @param filial
     * @param unidade
     * @param dataInicial
     * @param dataFinal
     * @return
     *     returns br.com.avacorp.integracaoprologtestes.ChecklistsFiltro
     */
    @WebMethod(action = AvaCorpAvilanConstants.NAMESPACE + "/buscarChecklistFiltro")
    @WebResult(name = "buscarChecklistFiltroResult", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
    @RequestWrapper(localName = "buscarChecklistFiltro", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprologtestes.BuscarChecklistFiltro")
    @ResponseWrapper(localName = "buscarChecklistFiltroResponse", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprologtestes.BuscarChecklistFiltroResponse")
    public ChecklistsFiltro buscarChecklistFiltro(
            @WebParam(name = "filial", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    int filial,
            @WebParam(name = "unidade", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    int unidade,
            @WebParam(name = "dataInicial", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String dataInicial,
            @WebParam(name = "dataFinal", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String dataFinal,
            @WebParam(name = "veiculo", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String veiculo,
            @WebParam(name = "colaborador", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String colaborador,
            @WebParam(name = "tipoVeiculo", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String tipoVeiculo);

    /**
     * Buscar avaliações
     *
     * @param codigoAvaliacao
     * @return
     *     returns br.com.avacorp.integracaoprologtestes.ChecklistsFiltro
     */
    @WebMethod(action = AvaCorpAvilanConstants.NAMESPACE + "/buscarAvaliacaoFiltro")
    @WebResult(name = "buscarAvaliacaoFiltroResult", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
    @RequestWrapper(localName = "buscarAvaliacaoFiltro", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprologtestes.BuscarAvaliacaoFiltro")
    @ResponseWrapper(localName = "buscarAvaliacaoFiltroResponse", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprologtestes.BuscarAvaliacaoFiltroResponse")
    public ChecklistsFiltro buscarAvaliacaoFiltro(
            @WebParam(name = "codigoAvaliacao", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    int codigoAvaliacao);
}