-- Sobre:
--
-- Function utilizada para cadastrar as informações de um prontuário de condutor. O prontuário é vinculado ao CPF de
-- um colaborador. Se, no momento do cadastro, já existir um prontuário para o CPF sendo inserido, todas as informações
-- serão sobrescritas pelas nova recebidas. Ou seja, essa function trabalha como um UPSERT.
--
-- Histórico:
-- 2019-11-07 -> Function criada (luizfp - PL-2269).
CREATE OR REPLACE FUNCTION FUNC_PRONTUARIO_INSERT_OR_UPDATE(F_CPF_COLABORADOR BIGINT,
                                                            F_STATUS TEXT,
                                                            F_MOTIVO TEXT,
                                                            F_PONTUACAO INTEGER,
                                                            F_VENCIMENTO_CNH DATE,
                                                            F_DOCUMENTOS_RS TEXT,
                                                            F_DOCUMENTOS_EC TEXT,
                                                            F_DOCUMENTOS_IT TEXT,
                                                            F_PONTUACAO_PONDERADA REAL,
                                                            F_ACIDENTES_FAI INTEGER,
                                                            F_ACIDENTES_LTI INTEGER,
                                                            F_ACIDENTES_MDI INTEGER,
                                                            F_ACIDENTES_MTI INTEGER,
                                                            F_CAPOTAMENTOS INTEGER,
                                                            F_COLISOES INTEGER,
                                                            F_TOMBAMENTOS INTEGER,
                                                            F_FADIGAS_CELULAR INTEGER,
                                                            F_FADIGAS_CONSUMO_ALIMENTO INTEGER,
                                                            F_FADIGAS_FUMANDO INTEGER,
                                                            F_FADIGAS_OCLUSAO INTEGER,
                                                            F_FADIGAS_SEM_CINTO INTEGER,
                                                            F_MULTAS_LEVE INTEGER,
                                                            F_MULTAS_MEDIA INTEGER,
                                                            F_MULTAS_GRAVE INTEGER,
                                                            F_MULTAS_GRAVISSIMA INTEGER,
                                                            F_SAC_IMPERICIA INTEGER,
                                                            F_SAC_IMPRUDENCIA INTEGER,
                                                            F_SAV_IMPERICIA INTEGER,
                                                            F_SAV_IMPRUDENCIA INTEGER,
                                                            F_ADVERTENCIAS INTEGER,
                                                            F_SUSPENSOES INTEGER,
                                                            F_EXCESSO_VELOCIDADE_1 INTEGER,
                                                            F_EXCESSO_VELOCIDADE_2 INTEGER,
                                                            F_EXCESSO_VELOCIDADE_3 INTEGER,
                                                            F_FORCA_G INTEGER,
                                                            F_FRENAGEM_BRUSCA INTEGER,
                                                            F_POWER_ON INTEGER,
                                                            F_DATA_ATUALIZACAO TIMESTAMP WITH TIME ZONE)
    RETURNS VOID
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    INSERT INTO PRONTUARIO_CONDUTOR_CONSOLIDADO (CPF_COLABORADOR,
                                                 STATUS,
                                                 MOTIVO,
                                                 PONTUACAO,
                                                 VENCIMENTO_CNH,
                                                 DOCUMENTOS_RS,
                                                 DOCUMENTOS_EC,
                                                 DOCUMENTOS_IT,
                                                 PONTUACAO_PONDERADA,
                                                 ACIDENTES_FAI,
                                                 ACIDENTES_LTI,
                                                 ACIDENTES_MDI,
                                                 ACIDENTES_MTI,
                                                 CAPOTAMENTOS,
                                                 COLISOES,
                                                 TOMBAMENTOS,
                                                 FADIGAS_CELULAR,
                                                 FADIGAS_CONSUMO_ALIMENTO,
                                                 FADIGAS_FUMANDO,
                                                 FADIGAS_OCLUSAO,
                                                 FADIGAS_SEM_CINTO,
                                                 MULTAS_LEVE,
                                                 MULTAS_MEDIA,
                                                 MULTAS_GRAVE,
                                                 MULTAS_GRAVISSIMA,
                                                 SAC_IMPERICIA,
                                                 SAC_IMPRUDENCIA,
                                                 SAV_IMPERICIA,
                                                 SAV_IMPRUDENCIA,
                                                 ADVERTENCIAS,
                                                 SUSPENSOES,
                                                 EXCESSO_VELOCIDADE_1,
                                                 EXCESSO_VELOCIDADE_2,
                                                 EXCESSO_VELOCIDADE_3,
                                                 FORCA_G,
                                                 FRENAGEM_BRUSCA,
                                                 POWER_ON,
                                                 DATA_ATUALIZACAO)
    VALUES (F_CPF_COLABORADOR,
            F_STATUS,
            F_MOTIVO,
            F_PONTUACAO,
            F_VENCIMENTO_CNH,
            F_DOCUMENTOS_RS,
            F_DOCUMENTOS_EC,
            F_DOCUMENTOS_IT,
            F_PONTUACAO_PONDERADA,
            F_ACIDENTES_FAI,
            F_ACIDENTES_LTI,
            F_ACIDENTES_MDI,
            F_ACIDENTES_MTI,
            F_CAPOTAMENTOS,
            F_COLISOES,
            F_TOMBAMENTOS,
            F_FADIGAS_CELULAR,
            F_FADIGAS_CONSUMO_ALIMENTO,
            F_FADIGAS_FUMANDO,
            F_FADIGAS_OCLUSAO,
            F_FADIGAS_SEM_CINTO,
            F_MULTAS_LEVE,
            F_MULTAS_MEDIA,
            F_MULTAS_GRAVE,
            F_MULTAS_GRAVISSIMA,
            F_SAC_IMPERICIA,
            F_SAC_IMPRUDENCIA,
            F_SAV_IMPERICIA,
            F_SAV_IMPRUDENCIA,
            F_ADVERTENCIAS,
            F_SUSPENSOES,
            F_EXCESSO_VELOCIDADE_1,
            F_EXCESSO_VELOCIDADE_2,
            F_EXCESSO_VELOCIDADE_3,
            F_FORCA_G,
            F_FRENAGEM_BRUSCA,
            F_POWER_ON,
            F_DATA_ATUALIZACAO)
    ON CONFLICT ON CONSTRAINT PK_PRONTUARIO_CONDUTOR_CONSOLIDADO
        DO UPDATE SET CPF_COLABORADOR          = F_CPF_COLABORADOR,
                      STATUS                   = F_STATUS,
                      MOTIVO                   = F_MOTIVO,
                      PONTUACAO                = F_PONTUACAO,
                      VENCIMENTO_CNH           = F_VENCIMENTO_CNH,
                      DOCUMENTOS_RS            = F_DOCUMENTOS_RS,
                      DOCUMENTOS_EC            = F_DOCUMENTOS_EC,
                      DOCUMENTOS_IT            = F_DOCUMENTOS_IT,
                      PONTUACAO_PONDERADA      = F_PONTUACAO_PONDERADA,
                      ACIDENTES_FAI            = F_ACIDENTES_FAI,
                      ACIDENTES_LTI            = F_ACIDENTES_LTI,
                      ACIDENTES_MDI            = F_ACIDENTES_MDI,
                      ACIDENTES_MTI            = F_ACIDENTES_MTI,
                      CAPOTAMENTOS             = F_CAPOTAMENTOS,
                      COLISOES                 = F_COLISOES,
                      TOMBAMENTOS              = F_TOMBAMENTOS,
                      FADIGAS_CELULAR          = F_FADIGAS_CELULAR,
                      FADIGAS_CONSUMO_ALIMENTO = F_FADIGAS_CONSUMO_ALIMENTO,
                      FADIGAS_FUMANDO          = F_FADIGAS_FUMANDO,
                      FADIGAS_OCLUSAO          = F_FADIGAS_OCLUSAO,
                      FADIGAS_SEM_CINTO        = F_FADIGAS_SEM_CINTO,
                      MULTAS_LEVE              = F_MULTAS_LEVE,
                      MULTAS_MEDIA             = F_MULTAS_MEDIA,
                      MULTAS_GRAVE             = F_MULTAS_GRAVE,
                      MULTAS_GRAVISSIMA        = F_MULTAS_GRAVISSIMA,
                      SAC_IMPERICIA            = F_SAC_IMPERICIA,
                      SAC_IMPRUDENCIA          = F_SAC_IMPRUDENCIA,
                      SAV_IMPERICIA            = F_SAV_IMPERICIA,
                      SAV_IMPRUDENCIA          = F_SAV_IMPRUDENCIA,
                      ADVERTENCIAS             = F_ADVERTENCIAS,
                      SUSPENSOES               = F_SUSPENSOES,
                      EXCESSO_VELOCIDADE_1     = F_EXCESSO_VELOCIDADE_1,
                      EXCESSO_VELOCIDADE_2     = F_EXCESSO_VELOCIDADE_2,
                      EXCESSO_VELOCIDADE_3     = F_EXCESSO_VELOCIDADE_3,
                      FORCA_G                  = F_FORCA_G,
                      FRENAGEM_BRUSCA          = F_FRENAGEM_BRUSCA,
                      POWER_ON                 = F_POWER_ON,
                      DATA_ATUALIZACAO         = F_DATA_ATUALIZACAO;
END;
$$;