-- Sobre:
-- A lógica aplicada nessa function é a seguinte:
-- Deleta nps de acordo com codigo de colaboradores.
--
-- Histórico:
-- 2020-04-06 -> Function criada (thaisksf - PL-2034).
CREATE OR REPLACE FUNCTION INTERNO.FUNC_DELETA_NPS(F_COD_COLABORADORES BIGINT[])
    RETURNS VOID
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    -- DELETA COLABORADORES BLOQUEADOS DO NPS
    DELETE
    FROM CS.NPS_BLOQUEIO_PESQUISA_COLABORADOR NBPC
    WHERE NBPC.COD_COLABORADOR_BLOQUEIO = ANY (F_COD_COLABORADORES);

    -- DELETA RESPOSTAS DE NPS
    DELETE FROM CS.NPS_RESPOSTAS NR WHERE NR.COD_COLABORADOR_RESPOSTAS = ANY (F_COD_COLABORADORES);
END;
$$;