CREATE OR REPLACE FUNCTION INTERNO.FUNC_DELETA_TESTES_AFERIDOR(F_COD_TESTES_AFERIDOR BIGINT[])
    RETURNS VOID
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    DELETE
    FROM AFERIDOR.PROCEDIMENTO_TESTE PT
    WHERE PT.CODIGO = ANY (F_COD_TESTES_AFERIDOR);
END;
$$;