CREATE OR REPLACE FUNCTION INTERNO.FUNC_DELETA_VEICULOS(F_COD_EMPRESA BIGINT, F_COD_UNIDADES BIGINT[])
    RETURNS VOID
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    -- DELETA VINCULO VEÍCULO_PNEU
    DELETE FROM VEICULO_PNEU VP WHERE VP.COD_UNIDADE = ANY (F_COD_UNIDADES);

    -- DELETA TODOS OS VEÍCULOS DA EMPRESA DESTINO
    DELETE
    FROM VEICULO_DATA VD
    WHERE VD.COD_EMPRESA = F_COD_EMPRESA;

    -- REALIZA UPDATE DE VEICULOS QUE FORAM TRANSFERIDOS ENTRE EMPRESA PARA REMOVER O COD_UNIDADE_CADASTRO
    UPDATE VEICULO_DATA
    SET COD_UNIDADE_CADASTRO = COD_UNIDADE
    WHERE COD_UNIDADE_CADASTRO = ANY (F_COD_UNIDADES);

    -- DELETA VEICULOS DA EMPRESA DESTINO QUE ESTÃO EM BACKUP
    DELETE
    FROM VEICULO_BACKUP VB
    WHERE VB.COD_UNIDADE = ANY (F_COD_UNIDADES);

    -- REALIZA UPDATE DE VEICULOS QUE FORAM TRANSFERIDOS ENTRE EMPRESA PARA REMOVER O COD_UNIDADE_CADASTRO
    UPDATE VEICULO_BACKUP
    SET COD_UNIDADE_CADASTRO = COD_UNIDADE
    WHERE COD_UNIDADE_CADASTRO = ANY (F_COD_UNIDADES);

    -- DELETA OS MODELOS DE VEÍCULO DA EMPRESA DESTINO
    DELETE
    FROM MODELO_VEICULO MV
    WHERE MV.COD_EMPRESA = F_COD_EMPRESA;

    -- DELETA NOMENCLATURAS
    DELETE
    FROM PNEU_POSICAO_NOMENCLATURA_EMPRESA PPNE
    WHERE PPNE.COD_EMPRESA = F_COD_EMPRESA;

    -- DELETA NOMENCLATURAS ANTIGAS
    DELETE
    FROM PNEU_ORDEM_NOMENCLATURA_ANTIGA PONA
    WHERE PONA.COD_UNIDADE = ANY (F_COD_UNIDADES);

    -- DELETA OS TIPOS DE VEÍCULOS DA EMPRESA DESTINO
    DELETE
    FROM VEICULO_TIPO VT
    WHERE VT.COD_EMPRESA = F_COD_EMPRESA;

    -- DELETA AS NOMENCLATURAS BACKUP
    DELETE
    FROM PNEU_ORDEM_NOMENCLATURA_UNIDADE_BACKUP PONUB
    WHERE PONUB.COD_UNIDADE = ANY (F_COD_UNIDADES);

    -- DELETA OS TIPOS DE VEÍCULOS DA EMPRESA DESTINO
    DELETE
    FROM VEICULO_TIPO_BACKUP VTB
    WHERE VTB.COD_UNIDADE = ANY (F_COD_UNIDADES);

    -- DELETA VEICULO DA TABELA DE ALTERAÇÃO DE KM
    DELETE
    FROM PROLOG_ANALISES.veiculo_alteracao_km VAK
    WHERE VAK.COD_UNIDADE_ALOCADO = ANY (F_COD_UNIDADES);
END;
$$;