-- Sobre:
-- A lógica aplicada nessa function é a seguinte:
-- Deleta os colaboradores de uma unidade e suas dependências.
--
-- Histórico:
-- 2020-04-06 -> Function criada (thaisksf - PL-2034).
CREATE OR REPLACE FUNCTION INTERNO.FUNC_DELETA_COLABORADORES(F_COD_EMPRESA BIGINT, F_COD_UNIDADES BIGINT[])
    RETURNS VOID
    LANGUAGE PLPGSQL
AS
$$
DECLARE
    V_COD_COLABORADORES BIGINT[] := (SELECT ARRAY_AGG(CD.CODIGO)
                                     FROM COLABORADOR_DATA CD
                                     WHERE CD.COD_EMPRESA = F_COD_EMPRESA);
BEGIN
    -- DELETA TOKENS
    DELETE FROM TOKEN_AUTENTICACAO TA WHERE TA.COD_COLABORADOR = ANY (V_COD_COLABORADORES);

    -- DELETA INFORMAÇÕES DE TELEFONE
    DELETE FROM COLABORADOR_TELEFONE CT WHERE CT.COD_COLABORADOR = ANY (V_COD_COLABORADORES);

    -- DELETA INFORMACOES DE E-MAIL
    DELETE FROM COLABORADOR_EMAIL CE WHERE CE.COD_COLABORADOR = ANY (V_COD_COLABORADORES);

    -- REMOVE CODIGO DE COLABORADOR DA TABELA FUNCAO_DATA
    UPDATE FUNCAO_DATA SET COD_COLABORADOR_UPDATE = NULL WHERE COD_COLABORADOR_UPDATE = ANY (V_COD_COLABORADORES);

    -- DELETA TODOS OS COLABORADORES DA UNIDADE DESTINO
     DELETE FROM COLABORADOR_DATA WHERE COD_UNIDADE = ANY (F_COD_UNIDADES);

    -- REALIZA UPDATE DE COLABORADORES QUE FORAM TRANSFERIDOS ENTRE EMPRESA PARA REMOVER O COD_UNIDADE_CADASTRO
    UPDATE COLABORADOR_DATA
    SET COD_UNIDADE_CADASTRO = COD_UNIDADE
    WHERE COD_UNIDADE_CADASTRO = ANY (F_COD_UNIDADES);

    -- DELETA AS EQUIPES DA UNIDADE DESTINO
    DELETE FROM EQUIPE E WHERE E.COD_UNIDADE = ANY (F_COD_UNIDADES);

    -- DELETA OS SETORES DA UNIDADE DESTINO
    DELETE FROM SETOR S WHERE S.COD_UNIDADE = ANY (F_COD_UNIDADES);

    -- DELETA AS FUNÇÕES DA EMPRESA DESTINO
    DELETE FROM CARGO_FUNCAO_PROLOG_V11 CFPV WHERE CFPV.COD_UNIDADE = ANY (F_COD_UNIDADES);
    DELETE FROM FUNCAO_DATA FD WHERE FD.COD_EMPRESA = F_COD_EMPRESA;
END;
$$;