-- Sobre:
-- A lógica aplicada nessa function é a seguinte:
-- Deleta unidades de uma empresa.
--
-- Histórico:
-- 2020-04-06 -> Function criada (thaisksf - PL-2034).
CREATE OR REPLACE FUNCTION INTERNO.FUNC_DELETA_UNIDADES(F_COD_EMPRESA BIGINT, F_COD_UNIDADES BIGINT[])
    RETURNS VOID
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    -- DELETA VINCULO UNIDADE PILAR
    DELETE FROM UNIDADE_PILAR_PROLOG UPP WHERE UPP.COD_UNIDADE = ANY (F_COD_UNIDADES);

    -- DELETA UNIDADES
    DELETE FROM UNIDADE U WHERE U.COD_EMPRESA = F_COD_EMPRESA;
END;
$$;