-- Sobre:
-- A lógica aplicada nessa function é a seguinte:
-- Deleta movimentacoes de uma unidade e suas dependências.
--
-- Histórico:
-- 2020-04-06 -> Function criada (thaisksf - PL-2034).
CREATE OR REPLACE FUNCTION INTERNO.FUNC_DELETA_MOVIMENTACOES_DEPENDENCIAS(F_COD_UNIDADES BIGINT[],
                                                                          F_COD_MOVIMENTACOES BIGINT[])
    RETURNS VOID
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    DELETE
    FROM MOVIMENTACAO_PNEU_SERVICO_REALIZADO_RECAPADORA_DATA MPSRRD
    WHERE MPSRRD.COD_MOVIMENTACAO = ANY (F_COD_MOVIMENTACOES);

    DELETE
    FROM MOVIMENTACAO_PNEU_SERVICO_REALIZADO_DATA MPSRD
    WHERE MPSRD.COD_MOVIMENTACAO = ANY (F_COD_MOVIMENTACOES);

    DELETE
    FROM MOVIMENTACAO_ORIGEM MO
    WHERE MO.
              COD_MOVIMENTACAO = ANY (F_COD_MOVIMENTACOES);

    DELETE
    FROM MOVIMENTACAO_DESTINO MD
    WHERE MD.COD_MOVIMENTACAO = ANY (F_COD_MOVIMENTACOES);

    DELETE
    FROM MOVIMENTACAO M
    WHERE M.CODIGO = ANY (F_COD_MOVIMENTACOES);

    DELETE
    FROM MOVIMENTACAO_PROCESSO MP
    WHERE MP.COD_UNIDADE = ANY (F_COD_UNIDADES);
END;
$$;