CREATE OR REPLACE FUNCTION INTERNO.FUNC_DELETA_PNEUS(F_COD_EMPRESA BIGINT, F_COD_UNIDADES BIGINT[])
    RETURNS VOID
    LANGUAGE PLPGSQL
AS
$$
DECLARE
    V_COD_PNEUS BIGINT[] := (SELECT ARRAY_AGG(PD.CODIGO) FROM PNEU_DATA PD WHERE PD.COD_EMPRESA = F_COD_EMPRESA);
BEGIN
    -- DELETA VINCULO VEÍCULO_PNEU
    DELETE
    FROM VEICULO_PNEU VP
    WHERE VP.COD_UNIDADE = ANY (F_COD_UNIDADES);

    -- DELETA FOTO DE PNEU
    DELETE
    FROM PNEU_FOTO_CADASTRO PFC
    WHERE PFC.COD_PNEU = ANY (V_COD_PNEUS);

    -- DELETA TODOS OS PNEUS DA EMPRESA DESTINO
    DELETE
    FROM PNEU_DATA PD
    WHERE PD.COD_EMPRESA = F_COD_EMPRESA;

    -- DELETA OS MODELOS DE PNEUS DA EMPRESA DESTINO
    DELETE
    FROM MODELO_PNEU MP
    WHERE MP.COD_EMPRESA = F_COD_EMPRESA;

    -- DELETA OS MODELOS DE BANDA DA EMPRESA DESTINO
    DELETE
    FROM MODELO_BANDA MOB
    WHERE MOB.COD_EMPRESA = F_COD_EMPRESA;

    -- DELETA AS MARCAS DE BANDA DA EMPRESA DESTINO
    DELETE
    FROM MARCA_BANDA MAB
    WHERE MAB.COD_EMPRESA = F_COD_EMPRESA;
END;
$$;