CREATE OR REPLACE FUNCTION INTERNO.FUNC_DELETA_VEICULOS(F_COD_EMPRESA BIGINT, F_COD_UNIDADES BIGINT[])
    RETURNS VOID
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    -- DELETA VINCULO VEÍCULO_PNEU
    DELETE FROM VEICULO_PNEU VP WHERE VP.COD_UNIDADE = ANY (F_COD_UNIDADES);

    -- DELETA TODOS OS VEÍCULOS DA EMPRESA DESTINO
    DELETE
    FROM VEICULO_DATA VD
    WHERE VD.COD_EMPRESA = F_COD_EMPRESA;

    -- REALIZA UPDATE DE VEICULOS QUE FORAM TRANSFERIDOS ENTRE EMPRESA PARA REMOVER O COD_UNIDADE_CADASTRO
    UPDATE VEICULO_DATA
    SET COD_UNIDADE_CADASTRO = COD_UNIDADE
    WHERE COD_UNIDADE_CADASTRO = ANY (F_COD_UNIDADES);

    -- DELETA OS MODELOS DE VEÍCULO DA EMPRESA DESTINO
    DELETE
    FROM MODELO_VEICULO MV
    WHERE MV.COD_EMPRESA = F_COD_EMPRESA;

    -- DELETA NOMENCLATURAS
    DELETE
    FROM PNEU_POSICAO_NOMENCLATURA_EMPRESA PPNE
    WHERE PPNE.COD_EMPRESA = F_COD_EMPRESA;

       -- DELETA OS TIPOS DE VEÍCULOS DA EMPRESA DESTINO
    DELETE
    FROM VEICULO_TIPO VT
    WHERE VT.COD_EMPRESA = F_COD_EMPRESA;
END;
$$;