-- Sobre:
-- A lógica aplicada nessa function é a seguinte:
-- Deleta transferencias de veiculos de uma unidade e suas dependências.
--
-- Histórico:
-- 2020-04-06 -> Function criada (thaisksf - PL-2034).
CREATE OR REPLACE FUNCTION INTERNO.FUNC_DELETA_TRANSFERENCIAS_VEICULOS_DEPENDENCIAS(F_CODIGOS_TRANSFERENCIAS_PROCESSOS BIGINT[])
    RETURNS VOID
    LANGUAGE PLPGSQL
AS
$$
DECLARE
    V_COD_TRANSFERENCIAS_INFORMACOES BIGINT[] := (SELECT ARRAY_AGG(VTI.CODIGO)
                                                  FROM VEICULO_TRANSFERENCIA_INFORMACOES VTI
                                                  WHERE VTI.COD_PROCESSO_TRANSFERENCIA = ANY
                                                        (F_CODIGOS_TRANSFERENCIAS_PROCESSOS));
BEGIN
    DELETE
    FROM CHECKLIST_ORDEM_SERVICO_DELETADA_TRANSFERENCIA COSDT
    WHERE COSDT.COD_VEICULO_TRANSFERENCIA_INFORMACOES = ANY (V_COD_TRANSFERENCIAS_INFORMACOES);

    DELETE
    FROM VEICULO_TRANSFERENCIA_VINCULO_PROCESSO_PNEU VTVIP
    WHERE VTVIP.COD_VEICULO_TRANSFERENCIA_INFORMACOES = ANY (V_COD_TRANSFERENCIAS_INFORMACOES);

    DELETE
    FROM VEICULO_TRANSFERENCIA_INFORMACOES VTI
    WHERE VTI.CODIGO = ANY (V_COD_TRANSFERENCIAS_INFORMACOES);

    DELETE
    FROM VEICULO_TRANSFERENCIA_PROCESSO VTP
    WHERE VTP.CODIGO = ANY (F_CODIGOS_TRANSFERENCIAS_PROCESSOS);
END;
$$;
