CREATE OR REPLACE FUNCTION INTERNO.FUNC_DELETA_RELATOS_DEPENDENCIAS(F_COD_UNIDADES BIGINT[])
    RETURNS VOID
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    DELETE FROM RELATO R WHERE R.COD_UNIDADE = ANY (F_COD_UNIDADES);

    DELETE FROM RELATO_ALTERNATIVA RA WHERE RA.COD_UNIDADE = ANY (F_COD_UNIDADES);
END;
$$;