CREATE OR REPLACE FUNCTION INTERNO.FUNC_DELETA_SERVICOS_PNEU_DEPENDENCIAS(F_COD_EMPRESA BIGINT, F_COD_SERVICOS_REALIZADOS BIGINT[])
    RETURNS VOID
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    DELETE
    FROM PNEU_SERVICO_REALIZADO_INCREMENTA_VIDA_DATA PSRIVD
    WHERE PSRIVD.COD_SERVICO_REALIZADO = ANY (F_COD_SERVICOS_REALIZADOS);
    
    DELETE 
    FROM PNEU_SERVICO_CADASTRO_DATA PSCD 
    WHERE PSCD.COD_SERVICO_REALIZADO = ANY (F_COD_SERVICOS_REALIZADOS);
    
    DELETE 
    FROM PNEU_SERVICO_REALIZADO_DATA PSRD 
    WHERE PSRD.CODIGO = ANY (F_COD_SERVICOS_REALIZADOS);
    
    DELETE 
    FROM PNEU_TIPO_SERVICO PTS 
    WHERE PTS.COD_EMPRESA = F_COD_EMPRESA;
END;
$$;