-- Sobre:
-- A lógica aplicada nessa function é a seguinte:
-- Deleta treinamentos de uma unidade e suas dependências.
--
-- Histórico:
-- 2020-04-06 -> Function criada (thaisksf - PL-2034).
CREATE OR REPLACE FUNCTION INTERNO.FUNC_DELETA_TREINAMENTOS_DEPENDENCIAS(V_COD_TREINAMENTOS BIGINT[])
    RETURNS VOID
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    DELETE
    FROM TREINAMENTO_COLABORADOR TC
    WHERE TC.COD_TREINAMENTO = ANY (V_COD_TREINAMENTOS);

    DELETE
    FROM RESTRICAO_TREINAMENTO RT
    WHERE RT.COD_TREINAMENTO = ANY (V_COD_TREINAMENTOS);

    DELETE
    FROM TREINAMENTO_URL_PAGINAS TUP
    WHERE TUP.COD_TREINAMENTO = ANY (V_COD_TREINAMENTOS);

    DELETE
    FROM TREINAMENTO T
    WHERE T.CODIGO = ANY (V_COD_TREINAMENTOS);
END;
$$;