CREATE OR REPLACE FUNCTION FUNC_CHECKLIST_RELATORIO_DADOS_GERAIS(
  F_COD_UNIDADES    BIGINT [],
  F_DATA_INICIAL    DATE,
  F_DATA_FINAL      DATE,
  F_PLACA           TEXT,
  F_COD_COLABORADOR BIGINT)
  RETURNS TABLE(
    UNIDADE                TEXT,
    "CÓDIGO CHECKLIST"     BIGINT,
    "DATA/HORA REALIZAÇÃO" TEXT,
    "CPF COLABORADOR"      TEXT,
    "NOME COLABORADOR"     TEXT,
    "TIPO VEÍCULO"         TEXT,
    PLACA                  TEXT,
    "TIPO CHECKLIST"       TEXT,
    "CÓDIGO MODELO"        TEXT,
    "NOME MODELO"          TEXT,
    PERGUNTA               TEXT,
    ALTERNATIVA            TEXT,
    RESPOSTA               TEXT,
    PRIORIDADE             TEXT,
    "TIPO RESPOSTA"        TEXT
  )
LANGUAGE SQL
AS $$
SELECT
  U.NOME                                         AS NOME_UNIDADE,
  CL.CODIGO                                      AS COD_CHECKLIST,
  TO_CHAR(CL.DATA_HORA, 'DD/MM/YYYY HH24:MI:SS') AS DATA_HORA_REALIZACAO,
  LPAD(CL.CPF_COLABORADOR :: TEXT, 11, '0')      AS CPF_COLABORADOR,
  CO.NOME                                        AS NOME_COLABORADOR,
  VT.NOME                                        AS NOME_TIPO_VEICULO,
  CL.PLACA_VEICULO                               AS PLACA_VEICULO,
  CASE WHEN CL.TIPO = 'S'
    THEN 'SAÍDA'
  ELSE 'RETORNO' END                             AS TIPO_CHECKLIST,
  CM.CODIGO :: TEXT                              AS CODIGO_MODELO_CHECKLIST,
  CM.NOME                                        AS NOME_MODELO_CHECKLIST,
  CP.PERGUNTA                                    AS PERGUNTA,
  CAP.ALTERNATIVA                                AS ALTERNATIVA,
  CR.RESPOSTA                                    AS RESPOSTA,
  CAP.PRIORIDADE                                 AS PRIORIDADE,
  CASE WHEN CP.SINGLE_CHOICE
    THEN 'ÚNICA ESCOLHA'
  ELSE 'MÚLTIPLA ESCOLHA' END                    AS TIPO_RESPOSTA
FROM CHECKLIST CL
  JOIN CHECKLIST_MODELO CM ON CL.COD_CHECKLIST_MODELO = CM.CODIGO
  JOIN CHECKLIST_PERGUNTAS CP ON CM.CODIGO = CP.COD_CHECKLIST_MODELO
  JOIN CHECKLIST_ALTERNATIVA_PERGUNTA CAP ON CP.CODIGO = CAP.COD_PERGUNTA
  JOIN UNIDADE U ON CL.COD_UNIDADE = U.CODIGO
  JOIN CHECKLIST_RESPOSTAS CR ON CAP.CODIGO = CR.COD_ALTERNATIVA
                                 AND CR.COD_CHECKLIST = CL.CODIGO
  JOIN COLABORADOR CO ON CO.CPF = CL.CPF_COLABORADOR
  JOIN VEICULO_TIPO VT ON VT.CODIGO =
                          (SELECT V.COD_TIPO
                           FROM VEICULO V
                           WHERE V.PLACA = CL.PLACA_VEICULO)
WHERE U.CODIGO = ANY (F_COD_UNIDADES)
      AND (CL.DATA_HORA AT TIME ZONE TZ_UNIDADE(CL.COD_UNIDADE)) :: DATE >= F_DATA_INICIAL
      AND (CL.DATA_HORA AT TIME ZONE TZ_UNIDADE(CL.COD_UNIDADE)) :: DATE <= F_DATA_FINAL
      AND F_IF(F_PLACA IS NOT NULL, CL.PLACA_VEICULO = F_PLACA, TRUE)
      AND F_IF(F_COD_COLABORADOR IS NOT NULL, CO.CODIGO = F_COD_COLABORADOR, TRUE)
ORDER BY U.CODIGO, CL.DATA_HORA DESC, CL.PLACA_VEICULO, CM.CODIGO, CP.PERGUNTA, CAP.CODIGO;
$$;