--################### Essa function busca checklists realizados abaixo de um determinado tempo de realização ###########
CREATE OR REPLACE FUNCTION FUNC_CHECKLIST_RELATORIO_REALIZADOS_ABAIXO_TEMPO_DEFINIDO(
  F_COD_UNIDADES                  BIGINT[],
  F_TEMPO_REALIZACAO_MILLIS       BIGINT,
  F_DATA_HOJE_UTC                 DATE,
  F_DIAS_RETROATIVOS_PARA_BUSCAR  BIGINT)
  RETURNS TABLE(
    UNIDADE                                                             TEXT,
    NOME                                                                TEXT,
    "QUANTIDADE CHECKLISTS REALIZADOS ABAIXO TEMPO ESPECIFICO"          BIGINT,
    "QUANTIDADE CHECKLISTS REALIZADOS"                                  BIGINT
  )
LANGUAGE PLPGSQL
AS $$
DECLARE
  DATA_INICIAL       DATE := F_DATA_HOJE_UTC + INTERVAL '1' DAY - (INTERVAL '1' DAY * F_DIAS_RETROATIVOS_PARA_BUSCAR);
  DATA_FINAL         DATE := F_DATA_HOJE_UTC + INTERVAL '1' DAY;
BEGIN
  RETURN QUERY
    WITH PRE_SELECT AS (
        SELECT
          U.NOME :: TEXT                                                AS NOME_UNIDADE,
          CO.NOME :: TEXT                                               AS NOME_COLABORADOR,
          COUNT(CL.CPF_COLABORADOR)
            FILTER (WHERE TEMPO_REALIZACAO < F_TEMPO_REALIZACAO_MILLIS) AS REALIZADOS_ABAIXO_TEMPO_DEFINIDO,
          COUNT(CL.CPF_COLABORADOR)                                     AS REALIZADOS
        FROM CHECKLIST CL
          JOIN UNIDADE U
            ON CL.COD_UNIDADE = U.CODIGO
          JOIN COLABORADOR CO
            ON CO.CPF = CL.CPF_COLABORADOR
        WHERE CL.COD_UNIDADE = ANY (F_COD_UNIDADES)
              AND (CL.DATA_HORA AT TIME ZONE TZ_UNIDADE(CL.COD_UNIDADE)) :: DATE BETWEEN DATA_INICIAL AND DATA_FINAL
        GROUP BY U.CODIGO, CO.CPF, CO.NOME
        ORDER BY REALIZADOS_ABAIXO_TEMPO_DEFINIDO DESC, CO.NOME ASC
    )
    SELECT
      PS.NOME_UNIDADE,
      PS.NOME_COLABORADOR,
      PS.REALIZADOS_ABAIXO_TEMPO_DEFINIDO,
      PS.REALIZADOS
  FROM PRE_SELECT PS
  WHERE PS.REALIZADOS_ABAIXO_TEMPO_DEFINIDO > 0;
END;
$$;