CREATE OR REPLACE FUNCTION FUNC_CHECKLIST_RELATORIO_TEMPO_REALIZACAO_MOTORISTAS(
  F_COD_UNIDADES BIGINT [],
  F_DATA_INICIAL DATE,
  F_DATA_FINAL   DATE)
  RETURNS TABLE(
    "UNIDADE"                              TEXT,
    "NOME"                                 TEXT,
    "FUNÇÃO"                               TEXT,
    "CHECKS SAÍDA"                         BIGINT,
    "CHECKS RETORNO"                       BIGINT,
    "TOTAL"                                BIGINT,
    "MÉDIA TEMPO DE REALIZAÇÃO (SEGUNDOS)" NUMERIC)
LANGUAGE SQL
AS $$
SELECT
  U.NOME                                AS NOME_UNIDADE,
  CO.NOME                               AS NOME,
  F.NOME                                AS FUNCAO,
  SUM(CASE WHEN C.TIPO = 'S'
    THEN 1
      ELSE 0 END)                       AS CHECKS_SAIDA,
  SUM(CASE WHEN C.TIPO = 'R'
    THEN 1
      ELSE 0 END)                       AS CHECKS_RETORNO,
  COUNT(C.TIPO)                         AS TOTAL_CHECKS,
  ROUND(AVG(C.TEMPO_REALIZACAO) / 1000) AS MEDIA_SEGUNDOS_REALIZACAO
FROM CHECKLIST C
  JOIN UNIDADE U ON C.COD_UNIDADE = U.CODIGO
  JOIN COLABORADOR CO ON CO.CPF = C.CPF_COLABORADOR
  JOIN FUNCAO F ON F.CODIGO = CO.COD_FUNCAO AND F.COD_EMPRESA = CO.COD_EMPRESA
WHERE C.COD_UNIDADE = ANY (F_COD_UNIDADES)
      AND (C.DATA_HORA AT TIME ZONE TZ_UNIDADE(C.COD_UNIDADE)) :: DATE >= F_DATA_INICIAL
      AND (C.DATA_HORA AT TIME ZONE TZ_UNIDADE(C.COD_UNIDADE)) :: DATE <= F_DATA_FINAL
GROUP BY U.CODIGO, CO.CPF, CO.NOME, F.CODIGO, F.NOME 
ORDER BY U.NOME, CO.NOME
$$;