# Arquivo utilizado para manter as familias:modelos bloqueados da Expresso Nepomuceno. Este é um facilitador para não
# precisar lançar um novo WS a cada modelo novo que deve ser bloqueado.
# Os códigos aqui mapeados devem estar no formato - FA001:M0002

# Código das famílias bloqueadas. Todas as placas que pertencerem a essa família não serão exibidos no Prolog.
familiasBloqueadas:
  - 'FA008'
  - 'FA011'

# Código dos modelos bloqueadas. Todas as placas que pertencerem a essas famílias:modelos específicos não serão
# exibidos no Prolog.
modelosBloqueados:
  - 'FA001:M0464'
  - 'FA002:M0710'
  - 'FA002:M0720'
  - 'FA002:M0721'
  - 'FA002:M0726'
  - 'FA002:M0727'
  - 'FA003:M0511'
  - 'FA003:M0598'
  - 'FA003:M0709'
  - 'FA004:M0717'
  - 'FA003:M0732'
  - 'FA003:M0728'
  - 'FA005:M0458'
  - 'FA006:M0322'
  - 'FA006:M0323'
  - 'FA006:M0324'
  - 'FA006:M0385'
  - 'FA006:M0389'
  - 'FA006:M0397'
  - 'FA006:M0412'
  - 'FA006:M0414'
  - 'FA006:M0415'
  - 'FA006:M0416'
  - 'FA006:M0444'
  - 'FA006:M0445'
  - 'FA006:M0463'
  - 'FA006:M0469'
  - 'FA006:M0516'
  - 'FA006:M0553'
  - 'FA006:M0578'
  - 'FA006:M0580'
  - 'FA006:M0581'
  - 'FA006:M0601'
  - 'FA006:M0612'
  - 'FA006:M0620'
  - 'FA006:M0622'
  - 'FA006:M0634'
  - 'FA006:M0697'
  - 'FA006:M0703'
  - 'FA006:M0707'
  - 'FA006:M0712'
  - 'FA006:M0713'
  - 'FA006:M0714'
  - 'FA006:M0715'
  - 'FA006:M0716'
  - 'FA010:M0391'
  - 'FA012:M0398'
  - 'FA013:M0462'
  - 'FA013:M0476'

# Código de placas específicas a serem bloqueadas no Prolog. Todas as placas aqui exibidas não
# serão exibidos no Prolog.
placasBloqueadas:
  - 'GUS1234'

# Estes campos informados no de-para abaixo são atributos da classe InspecaoRemovidoRealizada, que é o objeto que vai
# para a Nepomuceno. Como nem toda informação necessária existia nativamente no Prolog, utilizamos os campos
# personalizados para obter essa informação. Contudo, não temos como saber qual campo personalizado é referente a qual
# informação. Por conta disso, criamos este de-para para realizar esse vínculo. É estritamente necessário que cada
# código de campo de fato exista para que tudo funcione corretamente!
deParaCamposPersonalizados:
  - '4:codLipPneu'
  - '5:codOrigemFilial'
  - '6:codDestinoPneu'
  - '7:codCausaSucataPneu'
  - '8:observacao'

# Esse código 'D3–Sucata' é utilizado quando o usuário quer descartar um pneu. Uma vez informado, torna obrigatório
# informar o código da causa da sucata.
# Caso o usuário informar 'D3' e não informar uma causa para a sucata, o sistema deve mostrar um erro.
codSucataPneu: 'D3'