-- Sobre:
--
-- View que busca dados não deletados da tabela AFERICAO_MANUTENCAO_DATA.
--
-- Histórico:
-- 2020-05-12 -> Arquivo criado e nova coluna adicionada (FORMA_COLETA_DADOS_FECHAMENTO) (luiz_fp - PL-2714).
CREATE OR REPLACE VIEW AFERICAO_MANUTENCAO AS
SELECT AM.COD_AFERICAO,
       AM.COD_PNEU,
       AM.COD_UNIDADE,
       AM.TIPO_SERVICO,
       AM.DATA_HORA_RESOLUCAO,
       AM.CPF_MECANICO,
       AM.QT_APONTAMENTOS,
       AM.PSI_APOS_CONSERTO,
       AM.KM_MOMENTO_CONSERTO,
       AM.COD_ALTERNATIVA,
       AM.COD_PNEU_INSERIDO,
       AM.CODIGO,
       AM.COD_PROCESSO_MOVIMENTACAO,
       AM.TEMPO_REALIZACAO_MILLIS,
       AM.FECHADO_AUTOMATICAMENTE_MOVIMENTACAO,
       AM.FECHADO_AUTOMATICAMENTE_INTEGRACAO,
       AM.FORMA_COLETA_DADOS_FECHAMENTO
FROM AFERICAO_MANUTENCAO_DATA AM
WHERE (AM.DELETADO = FALSE);