CREATE OR REPLACE VIEW PNEU AS
  SELECT
    P.CODIGO_CLIENTE,
    P.COD_MODELO,
    P.COD_DIMENSAO,
    P.PRESSAO_RECOMENDADA,
    P.PRESSAO_ATUAL,
    P.ALTURA_SULCO_INTERNO,
    P.ALTURA_SULCO_CENTRAL_INTERNO,
    P.ALTURA_SULCO_EXTERNO,
    P.COD_UNIDADE,
    P.STATUS,
    P.VIDA_ATUAL,
    P.VIDA_TOTAL,
    P.COD_MODELO_BANDA,
    P.ALTURA_SULCO_CENTRAL_EXTERNO,
    P.DOT,
    P.VALOR,
    P.DATA_HORA_CADASTRO,
    P.PNEU_NOVO_NUNCA_RODADO,
    P.CODIGO,
    P.COD_EMPRESA,
    P.COD_UNIDADE_CADASTRO
  FROM PNEU_DATA P
  WHERE P.DELETADO = FALSE;