
package br.com.zalf.prolog.webservice.integracao.avacorpavilan.checklist.service;

import br.com.zalf.prolog.webservice.integracao.avacorpavilan.AvaCorpAvilanConstants;
import br.com.zalf.prolog.webservice.integracao.avacorpavilan.checklist.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChecklistSoap", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChecklistAvaCorpAvilanSoap {


    /**
     * Adicionar nova avaliação e retorna as questões
     * 
     * @param questionario
     * @return
     *     returns br.com.avacorp.integracaoprolog.PerguntasAlternativasQuestionario
     */
    @WebMethod(action = AvaCorpAvilanConstants.NAMESPACE + "/buscarPerguntasAlternativasQuestionario")
    @WebResult(name = "buscarPerguntasAlternativasQuestionarioResult", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
    @RequestWrapper(localName = "buscarPerguntasAlternativasQuestionario", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.BuscarPerguntasAlternativasQuestionario")
    @ResponseWrapper(localName = "buscarPerguntasAlternativasQuestionarioResponse", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.BuscarPerguntasAlternativasQuestionarioResponse")
    public PerguntasAlternativasQuestionario buscarPerguntasAlternativasQuestionario(
            @WebParam(name = "questionario", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    AdicionarChecklist questionario);

    /**
     * Questionarios para um veiculo
     * 
     * @param cpf
     * @return
     *     returns br.com.avacorp.integracaoprolog.BuscaQuestionarioColaborador
     */
    @WebMethod(action = AvaCorpAvilanConstants.NAMESPACE + "/buscarQuestionariosColaborador")
    @WebResult(name = "buscarQuestionariosColaboradorResult", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
    @RequestWrapper(localName = "buscarQuestionariosColaborador", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.BuscarQuestionariosColaborador")
    @ResponseWrapper(localName = "buscarQuestionariosColaboradorResponse", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.BuscarQuestionariosColaboradorResponse")
    public BuscaQuestionarioColaborador buscarQuestionariosColaborador(
            @WebParam(name = "cpf", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String cpf);

    /**
     * Processa as respostas de uma avaliação
     * 
     * @param respostas
     * @return
     *     returns br.com.avacorp.integracaoprolog.EnviaRespostaAvaliacao
     */
    @WebMethod(action = AvaCorpAvilanConstants.NAMESPACE + "/enviarChecklist")
    @WebResult(name = "enviarChecklistResult", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
    @RequestWrapper(localName = "enviarChecklist", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.EnviarChecklist")
    @ResponseWrapper(localName = "enviarChecklistResponse", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.EnviarChecklistResponse")
    public EnviaRespostaAvaliacao enviarChecklist(
            @WebParam(name = "respostas", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    RespostasAvaliacao respostas);

    /**
     * Farol
     *
     * @param filial
     * @param unidade
     * @param dataInicial
     * @param buscarRetroativo
     * @param dataFinal
     * @return
     *     returns br.com.avacorp.integracaoprologtestes.FarolChecklist2
     */
    @WebMethod(action = "http://www.avacorp.com.br/integracaoprologtestes/farolChecklist")
    @WebResult(name = "farolChecklistResult", targetNamespace = "http://www.avacorp.com.br/integracaoprologtestes")
    @RequestWrapper(localName = "farolChecklist", targetNamespace = "http://www.avacorp.com.br/integracaoprologtestes", className = "br.com.avacorp.integracaoprologtestes.FarolChecklist")
    @ResponseWrapper(localName = "farolChecklistResponse", targetNamespace = "http://www.avacorp.com.br/integracaoprologtestes", className = "br.com.avacorp.integracaoprologtestes.FarolChecklistResponse")
    public FarolChecklist2 farolChecklist(
            @WebParam(name = "filial", targetNamespace = "http://www.avacorp.com.br/integracaoprologtestes")
                    int filial,
            @WebParam(name = "unidade", targetNamespace = "http://www.avacorp.com.br/integracaoprologtestes")
                    int unidade,
            @WebParam(name = "dataInicial", targetNamespace = "http://www.avacorp.com.br/integracaoprologtestes")
                    String dataInicial,
            @WebParam(name = "dataFinal", targetNamespace = "http://www.avacorp.com.br/integracaoprologtestes")
                    String dataFinal,
            @WebParam(name = "buscarRetroativo", targetNamespace = "http://www.avacorp.com.br/integracaoprologtestes")
                    boolean buscarRetroativo);

    /**
     * Integração de arquivos binarios
     * 
     * @param extensao
     * @param numerosequencia
     * @param conteudo
     * @param numerosequenciaitem
     * @param cnpjcpfcodigo
     * @param serie
     * @param dtemissao
     * @param diferenciadornumero
     * @param nomearquivo
     * @param tipodocumento
     * @return
     *     returns br.com.avacorp.integracaoprolog.RetornoPadrao
     */
    @WebMethod(action = AvaCorpAvilanConstants.NAMESPACE + "/integrarArquivo")
    @WebResult(name = "integrarArquivoResult", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
    @RequestWrapper(localName = "integrarArquivo", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.IntegrarArquivo")
    @ResponseWrapper(localName = "integrarArquivoResponse", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.IntegrarArquivoResponse")
    public RetornoPadrao integrarArquivo(
            @WebParam(name = "tipodocumento", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    int tipodocumento,
            @WebParam(name = "diferenciadornumero", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    int diferenciadornumero,
            @WebParam(name = "serie", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    int serie,
            @WebParam(name = "numerosequencia", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    int numerosequencia,
            @WebParam(name = "numerosequenciaitem", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    int numerosequenciaitem,
            @WebParam(name = "cnpjcpfcodigo", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String cnpjcpfcodigo,
            @WebParam(name = "dtemissao", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String dtemissao,
            @WebParam(name = "nomearquivo", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String nomearquivo,
            @WebParam(name = "extensao", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String extensao,
            @WebParam(name = "conteudo", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String conteudo);

}
