
package br.com.zalf.prolog.webservice.integracao.avacorpavilan.checklist.service;

import br.com.zalf.prolog.webservice.integracao.avacorpavilan.checklist.*;
import br.com.zalf.prolog.webservice.integracao.avacorpavilan.checklist.farol.Farol;
import br.com.zalf.prolog.webservice.integracao.avacorpavilan.checklist.farol.FarolChecklist2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChecklistSoap", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChecklistAvaCorpAvilanSoap {


    /**
     * Adicionar nova avaliação e retorna as questões
     * 
     * @param questionario
     * @return
     *     returns br.com.avacorp.integracaoprolog.PerguntasAlternativasQuestionario
     */
    @WebMethod(action = "http://www.avacorp.com.br/integracaoprolog/buscarPerguntasAlternativasQuestionario")
    @WebResult(name = "buscarPerguntasAlternativasQuestionarioResult", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
    @RequestWrapper(localName = "buscarPerguntasAlternativasQuestionario", targetNamespace = "http://www.avacorp.com.br/integracaoprolog", className = "br.com.avacorp.integracaoprolog.BuscarPerguntasAlternativasQuestionario")
    @ResponseWrapper(localName = "buscarPerguntasAlternativasQuestionarioResponse", targetNamespace = "http://www.avacorp.com.br/integracaoprolog", className = "br.com.avacorp.integracaoprolog.BuscarPerguntasAlternativasQuestionarioResponse")
    public PerguntasAlternativasQuestionario buscarPerguntasAlternativasQuestionario(
            @WebParam(name = "questionario", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    AdicionarChecklist questionario);

    /**
     * Questionarios para um veiculo
     * 
     * @param cpf
     * @return
     *     returns br.com.avacorp.integracaoprolog.BuscaQuestionarioColaborador
     */
    @WebMethod(action = "http://www.avacorp.com.br/integracaoprolog/buscarQuestionariosColaborador")
    @WebResult(name = "buscarQuestionariosColaboradorResult", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
    @RequestWrapper(localName = "buscarQuestionariosColaborador", targetNamespace = "http://www.avacorp.com.br/integracaoprolog", className = "br.com.avacorp.integracaoprolog.BuscarQuestionariosColaborador")
    @ResponseWrapper(localName = "buscarQuestionariosColaboradorResponse", targetNamespace = "http://www.avacorp.com.br/integracaoprolog", className = "br.com.avacorp.integracaoprolog.BuscarQuestionariosColaboradorResponse")
    public BuscaQuestionarioColaborador buscarQuestionariosColaborador(
            @WebParam(name = "cpf", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    String cpf);

    /**
     * Processa as respostas de uma avaliação
     * 
     * @param respostas
     * @return
     *     returns br.com.avacorp.integracaoprolog.EnviaRespostaAvaliacao
     */
    @WebMethod(action = "http://www.avacorp.com.br/integracaoprolog/enviarChecklist")
    @WebResult(name = "enviarChecklistResult", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
    @RequestWrapper(localName = "enviarChecklist", targetNamespace = "http://www.avacorp.com.br/integracaoprolog", className = "br.com.avacorp.integracaoprolog.EnviarChecklist")
    @ResponseWrapper(localName = "enviarChecklistResponse", targetNamespace = "http://www.avacorp.com.br/integracaoprolog", className = "br.com.avacorp.integracaoprolog.EnviarChecklistResponse")
    public EnviaRespostaAvaliacao enviarChecklist(
            @WebParam(name = "respostas", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    RespostasAvaliacao respostas);

    /**
     * Farol
     *
     * @param farol
     * @return
     *     returns br.com.avacorp.integracaoprolog.FarolChecklist2
     */
    @WebMethod(action = "http://www.avacorp.com.br/integracaoprolog/farolChecklist")
    @WebResult(name = "farolChecklistResult", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
    @RequestWrapper(localName = "farolChecklist", targetNamespace = "http://www.avacorp.com.br/integracaoprolog", className = "br.com.avacorp.integracaoprolog.FarolChecklist")
    @ResponseWrapper(localName = "farolChecklistResponse", targetNamespace = "http://www.avacorp.com.br/integracaoprolog", className = "br.com.avacorp.integracaoprolog.FarolChecklistResponse")
    public FarolChecklist2 farolChecklist(
            @WebParam(name = "farol", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    Farol farol);

    /**
     * Integração de arquivos binarios
     * 
     * @param extensao
     * @param numerosequencia
     * @param conteudo
     * @param numerosequenciaitem
     * @param cnpjcpfcodigo
     * @param serie
     * @param dtemissao
     * @param diferenciadornumero
     * @param nomearquivo
     * @param tipodocumento
     * @return
     *     returns br.com.avacorp.integracaoprolog.RetornoPadrao
     */
    @WebMethod(action = "http://www.avacorp.com.br/integracaoprolog/integrarArquivo")
    @WebResult(name = "integrarArquivoResult", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
    @RequestWrapper(localName = "integrarArquivo", targetNamespace = "http://www.avacorp.com.br/integracaoprolog", className = "br.com.avacorp.integracaoprolog.IntegrarArquivo")
    @ResponseWrapper(localName = "integrarArquivoResponse", targetNamespace = "http://www.avacorp.com.br/integracaoprolog", className = "br.com.avacorp.integracaoprolog.IntegrarArquivoResponse")
    public RetornoPadrao integrarArquivo(
            @WebParam(name = "tipodocumento", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    int tipodocumento,
            @WebParam(name = "diferenciadornumero", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    int diferenciadornumero,
            @WebParam(name = "serie", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    int serie,
            @WebParam(name = "numerosequencia", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    int numerosequencia,
            @WebParam(name = "numerosequenciaitem", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    int numerosequenciaitem,
            @WebParam(name = "cnpjcpfcodigo", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    String cnpjcpfcodigo,
            @WebParam(name = "dtemissao", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    String dtemissao,
            @WebParam(name = "nomearquivo", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    String nomearquivo,
            @WebParam(name = "extensao", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    String extensao,
            @WebParam(name = "conteudo", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    String conteudo);

}
