CREATE TRIGGER TG_FUNC_AUDIT_FUNCAO_DATA
  AFTER INSERT OR UPDATE OR DELETE
  ON FUNCAO_DATA
  FOR EACH ROW EXECUTE PROCEDURE AUDIT.FUNC_AUDIT();

CREATE TRIGGER TG_FUNC_AUDIT_UNIDADE
  AFTER INSERT OR UPDATE OR DELETE
  ON UNIDADE
  FOR EACH ROW EXECUTE PROCEDURE AUDIT.FUNC_AUDIT();

CREATE TRIGGER TG_FUNC_AUDIT_EMPRESA
  AFTER INSERT OR UPDATE OR DELETE
  ON EMPRESA
  FOR EACH ROW EXECUTE PROCEDURE AUDIT.FUNC_AUDIT();

CREATE TRIGGER TG_FUNC_AUDIT_COLABORADOR
  AFTER INSERT OR UPDATE OR DELETE
  ON COLABORADOR_DATA
  FOR EACH ROW EXECUTE PROCEDURE AUDIT.FUNC_AUDIT();

CREATE TRIGGER TG_FUNC_AUDIT_VEICULO
  AFTER INSERT OR UPDATE OR DELETE
  ON VEICULO_DATA
  FOR EACH ROW EXECUTE PROCEDURE AUDIT.FUNC_AUDIT();

CREATE TRIGGER TG_FUNC_AUDIT_PNEU
  AFTER INSERT OR UPDATE OR DELETE
  ON PNEU_DATA
  FOR EACH ROW EXECUTE PROCEDURE AUDIT.FUNC_AUDIT();

CREATE TRIGGER TG_FUNC_AUDIT_PNEU_RESTRICAO_UNIDADE
  AFTER INSERT OR UPDATE OR DELETE
  ON PNEU_RESTRICAO_UNIDADE
  FOR EACH ROW EXECUTE PROCEDURE AUDIT.FUNC_AUDIT();

CREATE TRIGGER TG_FUNC_AUDIT_VEICULO_PNEU
  AFTER INSERT OR UPDATE OR DELETE
  ON VEICULO_PNEU
  FOR EACH ROW EXECUTE PROCEDURE AUDIT.FUNC_AUDIT();

CREATE TRIGGER TG_FUNC_AUDIT_AFERICAO
  AFTER INSERT OR UPDATE OR DELETE
  ON AFERICAO_DATA
  FOR EACH ROW EXECUTE PROCEDURE AUDIT.FUNC_AUDIT();

CREATE TRIGGER TG_FUNC_AUDIT_COLABORADOR_TELEFONE
  AFTER INSERT OR UPDATE OR DELETE
  ON COLABORADOR_TELEFONE
  FOR EACH ROW EXECUTE PROCEDURE AUDIT.FUNC_AUDIT();

CREATE TRIGGER TG_FUNC_AUDIT_COLABORADOR_EMAIL
  AFTER INSERT OR UPDATE OR DELETE
  ON COLABORADOR_EMAIL
  FOR EACH ROW EXECUTE PROCEDURE AUDIT.FUNC_AUDIT();

CREATE TRIGGER TG_FUNC_AUDIT_MESSAGING_PUSH_COLABORADOR_TOKEN
  AFTER INSERT OR UPDATE OR DELETE
  ON MESSAGING.PUSH_COLABORADOR_TOKEN
  FOR EACH ROW EXECUTE PROCEDURE AUDIT.FUNC_AUDIT();

CREATE TRIGGER TG_FUNC_AUDIT_RELATO_ALTERNATIVA
  AFTER INSERT OR UPDATE OR DELETE
  ON RELATO_ALTERNATIVA
  FOR EACH ROW EXECUTE PROCEDURE AUDIT.FUNC_AUDIT();

CREATE TRIGGER TG_FUNC_AUDIT_TOKEN_AUTENTICACAO
  AFTER DELETE
  ON TOKEN_AUTENTICACAO
  FOR EACH ROW EXECUTE PROCEDURE AUDIT.FUNC_AUDIT();

CREATE TRIGGER TG_FUNC_AUDIT_MOVIMENTACAO_MOTIVO_DESCARTE_EMPRESA
  AFTER INSERT OR UPDATE OR DELETE
  ON MOVIMENTACAO_MOTIVO_DESCARTE_EMPRESA
  FOR EACH ROW EXECUTE PROCEDURE AUDIT.FUNC_AUDIT();

CREATE TRIGGER TG_FUNC_AUDIT_AFERICAO_CONFIGURACAO_TIPO_AFERICAO_VEICULO
  AFTER INSERT OR UPDATE OR DELETE
  ON AFERICAO_CONFIGURACAO_TIPO_AFERICAO_VEICULO
  FOR EACH ROW EXECUTE PROCEDURE AUDIT.FUNC_AUDIT();

create trigger tg_func_audit_funcao_prolog_bloqueada
    after insert or delete
    on funcao_prolog_bloqueada
    for each row
execute procedure audit.func_audit();

create trigger tg_func_audit_intervalo
  after delete
  on intervalo
  for each row execute procedure audit.func_audit();

create trigger tg_func_audit_modelo_pneu
    after insert or update or delete
    on modelo_pneu
    for each row
execute procedure audit.func_audit();

create trigger tg_func_audit_modelo_banda
    after insert or update or delete
    on modelo_banda
    for each row
execute procedure audit.func_audit();