CREATE OR REPLACE VIEW TYPES.CHECKLIST_PARAMETRIZACAO_MIDIA AS
SELECT TIPO_PARAMETRIZACAO_MIDIA                     AS TIPO_PARAMETRIZACAO_MIDIA,
       F_IF((SELECT CURRENT_SETTING('lc_messages') = 'es_es.UTF-8'),
            TIPO_PARAMETRIZACAO_MIDIA_LEGIVEL_ES,
            TIPO_PARAMETRIZACAO_MIDIA_LEGIVEL_PT_BR) AS TIPO_PARAMETRIZACAO_MIDIA_LEGIVEL
FROM TYPES.CHECKLIST_PARAMETRIZACAO_MIDIA_TYPE
WHERE ATIVO = TRUE;