CREATE OR REPLACE VIEW TYPES.CHECKLIST_TIPO_MIDIA AS
SELECT TIPO_MIDIA                     AS TIPO_MIDIA,
       F_IF((SELECT CURRENT_SETTING('lc_messages') = 'es_es.UTF-8'),
            TIPO_MIDIA_LEGIVEL_ES,
            TIPO_MIDIA_LEGIVEL_PT_BR) AS TIPO_PARAMETRIZACAO_MIDIA_LEGIVEL
FROM TYPES.CHECKLIST_TIPO_MIDIA_TYPE
WHERE ATIVO = TRUE;