create or replace function migration_checklist.func_migration_9_criacao_indexes()
    returns void
    language plpgsql
as
$func$
begin
    CREATE INDEX IDX_CHECKLIST_RESPOSTAS_NOK_COD_CHECKLIST
        ON CHECKLIST_RESPOSTAS_NOK (COD_CHECKLIST);

    CREATE INDEX IDX_CHECKLIST_RESPOSTAS_NOK_COD_ALTERNATIVA
        ON CHECKLIST_RESPOSTAS_NOK (COD_ALTERNATIVA);

    CREATE INDEX IDX_CHECKLIST_ALTERNATIVA_PERGUNTA_COD_PERGUNTA
        ON CHECKLIST_ALTERNATIVA_PERGUNTA_DATA (COD_PERGUNTA);
end;
$func$;