CREATE OR REPLACE FUNCTION FUNC_PNEU_RELATORIO_QUANTIDADE_KMS_RODADOS_COM_SERVICOS_ABERTOS(F_COD_UNIDADES BIGINT [])
  RETURNS TABLE(
    PLACA_VEICULO TEXT,
    TOTAL_KM      BIGINT)
LANGUAGE PLPGSQL
AS $$
DECLARE
  TIPO_SERVICO_CALIBRAGEM TEXT := 'calibragem';
  TIPO_SERVICO_INSPECAO   TEXT := 'inspecao';
BEGIN
  RETURN QUERY
  WITH DADOS AS (SELECT
                   DISTINCT ON (V.PLACA)
                   V.PLACA AS PLACA_VEICULO,
                   AM.KM_MOMENTO_CONSERTO - A.KM_VEICULO AS TOTAL_KM
                 FROM AFERICAO_MANUTENCAO AM
                   JOIN AFERICAO A ON A.CODIGO = AM.COD_AFERICAO
                   JOIN VEICULO V ON V.CODIGO = A.COD_VEICULO
                   JOIN VEICULO_PNEU VP ON VP.COD_VEICULO = A.COD_VEICULO
                                           AND AM.COD_PNEU = VP.COD_PNEU
                                           AND AM.COD_UNIDADE = VP.COD_UNIDADE
                 WHERE AM.COD_UNIDADE = ANY (F_COD_UNIDADES)
                       AND AM.DATA_HORA_RESOLUCAO IS NOT NULL
                       AND (AM.TIPO_SERVICO IN (TIPO_SERVICO_CALIBRAGEM, TIPO_SERVICO_INSPECAO))
  )

  SELECT
    D.PLACA_VEICULO :: TEXT AS PLACA_VEICULO,
    D.TOTAL_KM              AS TOTAL_KM
  FROM DADOS D
  WHERE D.TOTAL_KM > 0
  ORDER BY TOTAL_KM DESC;
END;
$$;