CREATE OR REPLACE FUNCTION FUNC_QUIZ_RELATORIO_ESTRATIFICACAO_REALIZACAO(
  F_COD_UNIDADE  BIGINT,
  F_COD_MODELO   BIGINT,
  F_DATA_INICIAL DATE,
  F_DATA_FINAL   DATE)
  RETURNS TABLE(
    "MAT PROMAX"               TEXT,
    "MAT RH"                   TEXT,
    "NOME"                     TEXT,
    "CARGO"                    TEXT,
    "REALIZADOS"               BIGINT,
    "APROVADOS"                BIGINT,
    "PORCENTAGEM DE APROVAÇÃO" TEXT,
    "MÁXIMO DE ACERTOS"        INTEGER,
    "MÍNIMO DE ACERTOS"        INTEGER)
LANGUAGE PLPGSQL
AS $$
BEGIN
  RETURN QUERY
  SELECT
    C.MATRICULA_AMBEV :: TEXT                                     AS MAT_PROMAX,
    C.MATRICULA_TRANS :: TEXT                                     AS MAT_RH,
    INITCAP(C.NOME)                                               AS NOME_COLABORADOR,
    F.NOME :: TEXT                                                AS CARGO,
    COALESCE(REALIZADOS.REALIZADOS, REALIZADOS.REALIZADOS, 0)     AS REALIZADOS,
    COALESCE(REALIZADOS.QT_APROVADOS, REALIZADOS.QT_APROVADOS, 0) AS APROVADOS,
    CASE WHEN COALESCE(REALIZADOS.REALIZADOS, REALIZADOS.REALIZADOS, 0) > 0
      THEN
        ROUND(
            (COALESCE(REALIZADOS.QT_APROVADOS, REALIZADOS.QT_APROVADOS, 0) /
             COALESCE(REALIZADOS.REALIZADOS, REALIZADOS.REALIZADOS, 0) :: NUMERIC) * 100) || '%'
    ELSE 0 || '%' END                                             AS PORCENTAGEM_APROVACAO,
    COALESCE(REALIZADOS.MAX_ACERTOS, REALIZADOS.MAX_ACERTOS, 0)   AS MAXIMO_ACERTOS,
    COALESCE(REALIZADOS.MIN_ACERTOS, REALIZADOS.MIN_ACERTOS, 0)   AS MINIMO_ACERTOS
  FROM COLABORADOR C
    JOIN FUNCAO F ON F.CODIGO = C.COD_FUNCAO AND F.COD_EMPRESA = C.COD_EMPRESA
    LEFT JOIN
    (SELECT
       C.CPF              AS CPF_REALIZADOS,
       COUNT(C.CPF)       AS REALIZADOS,
       SUM(
           CASE WHEN (Q.QT_CORRETAS :: REAL / (Q.QT_CORRETAS + Q.QT_ERRADAS) :: REAL) >= QM.PORCENTAGEM_APROVACAO
             THEN 1
           ELSE 0
           END
       )                  AS QT_APROVADOS,
       MAX(Q.QT_CORRETAS) AS MAX_ACERTOS,
       MIN(Q.QT_CORRETAS) AS MIN_ACERTOS
     FROM
       COLABORADOR C LEFT JOIN QUIZ Q ON Q.CPF_COLABORADOR = C.CPF
       JOIN QUIZ_MODELO QM ON QM.CODIGO = Q.COD_MODELO AND QM.COD_UNIDADE = Q.COD_UNIDADE
     WHERE F_IF(F_COD_MODELO IS NULL, TRUE, Q.COD_MODELO = F_COD_MODELO)
           AND (Q.DATA_HORA AT TIME ZONE TZ_UNIDADE(Q.COD_UNIDADE)) :: DATE BETWEEN F_DATA_INICIAL AND F_DATA_FINAL
     GROUP BY 1) AS REALIZADOS ON CPF_REALIZADOS = C.CPF
  WHERE C.STATUS_ATIVO = TRUE
        AND C.COD_UNIDADE = F_COD_UNIDADE
  ORDER BY REALIZADOS DESC;
END;
$$;