CREATE FUNCTION FUNC_QUIZ_RELATORIO_REALIZACAO_CARGO(
  F_COD_UNIDADE BIGINT,
  F_COD_MODELO  BIGINT)
  RETURNS TABLE(
    "QUIZ"                         TEXT,
    "CARGO"                        TEXT,
    "COLABORADORES CADASTRADOS"    BIGINT,
    "COLABORADORES QUE REALIZARAM" BIGINT,
    "PROPORÇÃO"                    TEXT)
LANGUAGE SQL
AS $$
SELECT
  QM.NOME,
  F.NOME,
  REALIZAR.TOTAL_DEVERIAM_TER_REALIZADO,
  COALESCE(REALIZADOS.TOTAL_REALIZARAM, 0) AS REALIZARAM,
  TRUNC((COALESCE(REALIZADOS.TOTAL_REALIZARAM, 0) / REALIZAR.TOTAL_DEVERIAM_TER_REALIZADO :: FLOAT) * 100) || '%'
FROM QUIZ_MODELO_FUNCAO QMF
  JOIN QUIZ_MODELO QM ON QM.CODIGO = QMF.COD_MODELO AND QM.COD_UNIDADE = QMF.COD_UNIDADE
  JOIN UNIDADE U ON U.CODIGO = QMF.COD_UNIDADE
  JOIN FUNCAO F ON F.CODIGO = QMF.COD_FUNCAO_COLABORADOR AND U.COD_EMPRESA = F.COD_EMPRESA
  JOIN (SELECT
          QMF.COD_MODELO,
          QMF.COD_FUNCAO_COLABORADOR AS COD_FUNCAO_DEVERIAM,
          COUNT(C.CPF)               AS TOTAL_DEVERIAM_TER_REALIZADO
        FROM QUIZ_MODELO_FUNCAO QMF
          JOIN COLABORADOR C
            ON C.COD_FUNCAO = QMF.COD_FUNCAO_COLABORADOR AND C.COD_UNIDADE = QMF.COD_UNIDADE AND C.STATUS_ATIVO IS TRUE
        WHERE QMF.COD_UNIDADE = F_COD_UNIDADE
              AND F_IF(F_COD_MODELO IS NULL, TRUE, QMF.COD_MODELO = F_COD_MODELO)
        GROUP BY 1, 2) AS REALIZAR
    ON QMF.COD_FUNCAO_COLABORADOR = REALIZAR.COD_FUNCAO_DEVERIAM AND QMF.COD_MODELO = REALIZAR.COD_MODELO
  LEFT JOIN (SELECT
               CALCULO.COD_MODELO,
               CALCULO.COD_FUNCAO AS COD_FUNCAO_REALIZARAM,
               COUNT(CALCULO.CPF) AS TOTAL_REALIZARAM
             FROM
               (SELECT
                  Q.COD_MODELO,
                  C.CPF,
                  C.COD_FUNCAO,
                  COUNT(C.COD_FUNCAO)
                FROM QUIZ Q
                  JOIN COLABORADOR C ON C.CPF = Q.CPF_COLABORADOR AND C.STATUS_ATIVO IS TRUE
                WHERE Q.COD_UNIDADE = F_COD_UNIDADE
                      AND F_IF(F_COD_MODELO IS NULL, TRUE, Q.COD_MODELO = F_COD_MODELO)
                GROUP BY 1, 2, 3) AS CALCULO
             GROUP BY 1, 2) AS REALIZADOS
    ON QMF.COD_FUNCAO_COLABORADOR = REALIZADOS.COD_FUNCAO_REALIZARAM AND REALIZADOS.COD_MODELO = QMF.COD_MODELO
WHERE QMF.COD_UNIDADE = F_COD_UNIDADE
      AND F_IF(F_COD_MODELO IS NULL, TRUE, QMF.COD_MODELO = F_COD_MODELO)
ORDER BY QM.NOME, F.NOME;
$$;