-- PL-1998

CREATE OR REPLACE FUNCTION FUNC_QUIZ_RELATORIO_RESPOSTAS_REALIZADOS(
  F_COD_UNIDADE         BIGINT,
  F_COD_MODELO          BIGINT,
  F_CPF                 BIGINT,
  F_DATA_INICIAL        DATE,
  F_DATA_FINAL          DATE,
  F_APENAS_SELECIONADAS BOOLEAN
)
  RETURNS TABLE(
    "QUIZ"               TEXT,
    "DATA DE REALIZAÇÃO" TEXT,
    "COLABORADOR"        TEXT,
    "CPF"                TEXT,
    "PERGUNTA"           TEXT,
    "ALTERNATIVA"        TEXT,
    "SELECIONADA"        TEXT,
    "CORRETA"            TEXT)
LANGUAGE PLPGSQL
AS $$
BEGIN
  RETURN QUERY
  SELECT
    QM.NOME :: TEXT                                                              AS MODELO,
    FORMAT_WITH_TZ(Q.DATA_HORA, TZ_UNIDADE(Q.COD_UNIDADE), 'DD/MM/YYYY HH24:MI') AS DATA_HORA,
    C.NOME :: TEXT                                                               AS COLABORADOR,
    LPAD(C.CPF :: TEXT, 11, '0')                                                 AS CPF_COLABORADOR,
    QP.PERGUNTA :: TEXT                                                          AS PERGUNTA,
    QAP.ALTERNATIVA :: TEXT                                                      AS ALTERNATIVA,
    F_IF(QR.SELECIONADA, 'Sim' :: TEXT, 'Não' :: TEXT)                           AS SELECIONADA,
    F_IF(QAP.CORRETA, 'Sim' :: TEXT, 'Não' :: TEXT)                              AS CORRETA
  FROM QUIZ Q
    LEFT JOIN QUIZ_MODELO QM ON (QM.CODIGO = Q.COD_MODELO)
    LEFT JOIN COLABORADOR C ON (C.CPF = Q.CPF_COLABORADOR)
    LEFT JOIN QUIZ_RESPOSTAS QR ON (Q.CODIGO = QR.COD_QUIZ)
    LEFT JOIN QUIZ_PERGUNTAS QP ON (QP.CODIGO = QR.COD_PERGUNTA)
    LEFT JOIN QUIZ_ALTERNATIVA_PERGUNTA QAP
      ON (QR.COD_PERGUNTA = QAP.COD_PERGUNTA AND QR.COD_ALTERNATIVA = QAP.CODIGO)
  WHERE Q.COD_UNIDADE = F_COD_UNIDADE
        AND F_IF(F_COD_MODELO IS NULL, TRUE, Q.COD_MODELO = F_COD_MODELO)
        AND F_IF(F_CPF IS NULL, TRUE, Q.CPF_COLABORADOR = F_CPF)
        AND
        (Q.DATA_HORA AT TIME ZONE TZ_UNIDADE(Q.COD_UNIDADE)) :: DATE BETWEEN F_DATA_INICIAL AND F_DATA_FINAL
        AND F_IF(F_APENAS_SELECIONADAS IS TRUE, QR.SELECIONADA, TRUE)
  ORDER BY Q.DATA_HORA, QAP.CORRETA DESC, QR.SELECIONADA;
END;
$$;