CREATE OR REPLACE FUNCTION FUNC_QUIZ_RELATORIO_ESTRATIFICACAO_RESPOSTAS(
  F_COD_UNIDADE BIGINT,
  F_COD_MODELO  BIGINT)
  RETURNS TABLE(
    "QUIZ"        TEXT,
    "PERGUNTA"    TEXT,
    "RESPOSTA"    TEXT,
    "TOTAL"       BIGINT,
    "ACERTOS"     BIGINT,
    "PORCENTAGEM" TEXT)
LANGUAGE PLPGSQL
AS $$
BEGIN
  RETURN QUERY
  SELECT
    QM.NOME :: TEXT                                         AS QUIZ,
    QP.PERGUNTA                                             AS PERGUNTA_QUIZ,
    QAP.ALTERNATIVA                                         AS RESPOSTA,
    COUNT(QAP.ALTERNATIVA)                                  AS TOTAL,
    SUM(CASE WHEN QAP.CORRETA = TRUE AND QR.SELECIONADA = TRUE
      THEN 1
        ELSE 0 END)                                         AS ACERTOS,
    ROUND((SUM(CASE WHEN QAP.CORRETA = TRUE AND QR.SELECIONADA = TRUE
      THEN 1
               ELSE 0 END) :: FLOAT /
           COUNT(QAP.ALTERNATIVA) * 100) :: NUMERIC) || '%' AS PORCENTAGEM
  FROM QUIZ Q
    JOIN QUIZ_MODELO QM ON QM.CODIGO = Q.COD_MODELO
    JOIN QUIZ_PERGUNTAS QP ON QP.COD_MODELO = Q.COD_MODELO
    JOIN QUIZ_ALTERNATIVA_PERGUNTA QAP ON QAP.COD_PERGUNTA = QP.CODIGO
    JOIN QUIZ_RESPOSTAS QR ON QR.COD_QUIZ = Q.CODIGO
  WHERE QAP.CORRETA = TRUE
        AND Q.COD_UNIDADE = F_COD_UNIDADE
        AND F_IF(F_COD_MODELO IS NULL, TRUE, Q.COD_MODELO = F_COD_MODELO)
  GROUP BY QUIZ, PERGUNTA, ALTERNATIVA
  ORDER BY QUIZ, PORCENTAGEM DESC;
END;
$$;