CREATE OR REPLACE FUNCTION FUNC_GARANTE_INTEGRIDADE_EMPRESA_COLABORADOR(
  F_COD_EMPRESA BIGINT,
  F_CPF_COLABORADOR BIGINT)
  RETURNS VOID
LANGUAGE PLPGSQL
AS $$
BEGIN
  --VERIFICA SE COLABORADOR EXISTE
  PERFORM FUNC_GARANTE_COLABORADOR_EXISTE(F_CPF_COLABORADOR);

  --VERIFICA SE EMPRESA EXISTE
  PERFORM FUNC_GARANTE_EMPRESA_EXISTE(F_COD_EMPRESA);

  -- VERIFICA SE O COLABORADOR PERTENCE À EMPRESA.
  IF NOT EXISTS(SELECT C.CPF
                FROM COLABORADOR C
                WHERE C.CPF = F_CPF_COLABORADOR AND C.COD_EMPRESA = F_COD_EMPRESA)
  THEN RAISE EXCEPTION 'O colaborador com CPF: %, nome: %, não pertence a empresa: % - %!',
  F_CPF_COLABORADOR,
  (SELECT C.NOME FROM COLABORADOR C WHERE C.CPF = F_CPF_COLABORADOR),
  F_COD_EMPRESA,
  (SELECT E.NOME FROM EMPRESA E WHERE E.CODIGO = F_COD_EMPRESA);
  END IF;
END;
$$;