CREATE OR REPLACE FUNCTION FUNC_GARANTE_EMPRESA_EXISTE(F_COD_EMPRESA BIGINT, F_ERROR_MESSAGE TEXT DEFAULT NULL)
  RETURNS VOID
LANGUAGE PLPGSQL
AS $$
DECLARE
  ERROR_MESSAGE TEXT :=
  F_IF(F_ERROR_MESSAGE IS NULL, FORMAT('Empresa de código %s não existe!', F_COD_EMPRESA), F_ERROR_MESSAGE);
BEGIN
  IF NOT EXISTS(SELECT E.CODIGO
                FROM EMPRESA E
                WHERE E.CODIGO = F_COD_EMPRESA)
  THEN PERFORM THROW_GENERIC_ERROR(ERROR_MESSAGE);
  END IF;
END;
$$;