CREATE OR REPLACE FUNCTION FUNC_GARANTE_INTEGRIDADE_EMPRESA_UNIDADE(
  F_COD_EMPRESA BIGINT,
  F_COD_UNIDADE BIGINT,
  F_ERROR_MESSAGE TEXT DEFAULT NULL)
  RETURNS VOID
LANGUAGE PLPGSQL
AS $$
BEGIN
  PERFORM FUNC_GARANTE_EMPRESA_EXISTE(F_COD_EMPRESA, F_ERROR_MESSAGE);
  PERFORM FUNC_GARANTE_UNIDADE_EXISTE(F_COD_UNIDADE, F_ERROR_MESSAGE);
  PERFORM FUNC_GARANTE_EMPRESA_POSSUI_UNIDADE(F_COD_EMPRESA, F_COD_UNIDADE, F_ERROR_MESSAGE);
END;
$$;