CREATE OR REPLACE FUNCTION FUNC_GARANTE_PNEU_EXISTE(
  F_COD_EMPRESA BIGINT,
  F_COD_UNIDADE BIGINT,
  F_COD_PNEU    BIGINT)
  RETURNS VOID
LANGUAGE PLPGSQL
AS $$
BEGIN
  IF NOT EXISTS(SELECT P.CODIGO
                FROM PNEU P
                WHERE P.CODIGO = F_COD_PNEU AND P.COD_UNIDADE = F_COD_UNIDADE AND P.COD_EMPRESA = F_COD_EMPRESA)
  THEN RAISE EXCEPTION 'Pneu com código %, não existe na unidade % - %', F_COD_PNEU,
  F_COD_UNIDADE, (SELECT U.NOME
                  FROM UNIDADE U
                  WHERE U.CODIGO = F_COD_UNIDADE);
  END IF;
END;
$$;