CREATE OR REPLACE FUNCTION FUNC_GARANTE_UNIDADE_EXISTE(F_COD_UNIDADE BIGINT, F_ERROR_MESSAGE TEXT DEFAULT NULL)
  RETURNS VOID
LANGUAGE PLPGSQL
AS $$
DECLARE
  ERROR_MESSAGE TEXT :=
  F_IF(F_ERROR_MESSAGE IS NULL, FORMAT('Unidade de código %s não existe!', F_COD_UNIDADE), F_ERROR_MESSAGE);
BEGIN
  IF NOT EXISTS(SELECT U.CODIGO
                FROM UNIDADE U
                WHERE U.CODIGO = F_COD_UNIDADE)
  THEN PERFORM THROW_GENERIC_ERROR(ERROR_MESSAGE);
  END IF;
END;
$$;