CREATE OR REPLACE FUNCTION FUNC_GARANTE_EMPRESAS_DISTINTAS(
  F_COD_EMPRESA_1 BIGINT,
  F_COD_EMPRESA_2 BIGINT)
  RETURNS VOID
LANGUAGE PLPGSQL
AS $$
BEGIN
  -- Verifica se as empresas são iguais.
  IF (F_COD_EMPRESA_1 = F_COD_EMPRESA_2)
  THEN RAISE EXCEPTION 'As empresas são iguais';
  END IF;
END;
$$;