CREATE OR REPLACE FUNCTION FUNC_GARANTE_NOT_NULL(F_VALUE ANYELEMENT, F_FIELD_NAME TEXT)
    RETURNS VOID
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    IF (F_VALUE IS NULL)
    THEN
        RAISE EXCEPTION '% não pode ser nulo', F_FIELD_NAME;
    END IF;
END;
$$;