CREATE OR REPLACE FUNCTION FUNC_MOTIVO_MOVIMENTO_TRANSICAO_DELETA(F_COD_EMPRESA BIGINT)
    RETURNS VOID
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    DELETE FROM MOVIMENTACAO_MOTIVO_MOVIMENTO_TRANSICAO MMMT WHERE MMMT.COD_EMPRESA = F_COD_EMPRESA;
END;
$$;
