CREATE OR REPLACE FUNCTION FUNC_QUIZ_GET_LISTAGEM_MODELOS(
  F_COD_UNIDADE         BIGINT,
  F_DATA_HORA_ATUAL_UTC TIMESTAMP WITH TIME ZONE)
  RETURNS TABLE(
    COD_MODELO_QUIZ             BIGINT,
    NOME_MODELO_QUIZ            TEXT,
    COD_UNIDADE_MODELO_QUIZ     BIGINT,
    NOME_CARGO_LIBERADO         TEXT,
    PORCENTAGEM_APROVACAO       REAL,
    QTD_PERGUNTAS               BIGINT,
    TEM_MATERIAL_APOIO          BOOLEAN,
    ESTA_ABERTO_PARA_REALIZACAO BOOLEAN)
LANGUAGE SQL
AS $$
SELECT
  QM.CODIGO                                       AS COD_MODELO_QUIZ,
  QM.NOME :: TEXT                                 AS NOME_MODELO_QUIZ,
  QM.COD_UNIDADE                                  AS COD_UNIDADE_MODELO_QUIZ,
  F.NOME :: TEXT                                  AS NOME_CARGO_LIBERADO,
  QM.PORCENTAGEM_APROVACAO                        AS PORCENTAGEM_APROVACAO,
  (SELECT COUNT(*)
   FROM QUIZ_PERGUNTAS QP
   WHERE QP.COD_MODELO = QM.CODIGO)               AS QTD_PERGUNTAS,
  QMT.COD_TREINAMENTO IS NOT NULL                 AS TEM_MATERIAL_APOIO,
  QM.DATA_HORA_FECHAMENTO > F_DATA_HORA_ATUAL_UTC AS ESTA_ABERTO_PARA_REALIZACAO
FROM QUIZ_MODELO QM
  LEFT JOIN QUIZ_MODELO_TREINAMENTO QMT
    ON QM.CODIGO = QMT.COD_MODELO_QUIZ
  LEFT JOIN QUIZ_MODELO_FUNCAO QMF
    ON QM.CODIGO = QMF.COD_MODELO
  LEFT JOIN FUNCAO F
    ON F.CODIGO = QMF.COD_FUNCAO_COLABORADOR
WHERE QM.COD_UNIDADE = F_COD_UNIDADE
ORDER BY COD_MODELO_QUIZ ASC, NOME_CARGO_LIBERADO ASC
$$;