CREATE OR REPLACE FUNCTION FUNC_MARCACAO_GET_TIPOS_MARCACOES(F_COD_UNIDADE BIGINT, F_APENAS_ATIVOS BOOLEAN)
  RETURNS TABLE(
    CODIGO_TIPO_INTERVALO             BIGINT,
    CODIGO_TIPO_INTERVALO_POR_UNIDADE BIGINT,
    NOME_TIPO_INTERVALO               CHARACTER VARYING,
    COD_UNIDADE                       BIGINT,
    ATIVO                             BOOLEAN,
    HORARIO_SUGERIDO                  TIME WITHOUT TIME ZONE,
    ICONE                             CHARACTER VARYING,
    TEMPO_ESTOURO_MINUTOS             BIGINT,
    TEMPO_RECOMENDADO_MINUTOS         BIGINT,
    TIPO_JORNADA                      BOOLEAN,
    COD_AUXILIAR                      TEXT)
LANGUAGE SQL
AS $$
SELECT DISTINCT
  IT.CODIGO                            AS CODIGO_TIPO_INTERVALO,
  IT.CODIGO_TIPO_INTERVALO_POR_UNIDADE AS CODIGO_TIPO_INTERVALO_POR_UNIDADE,
  IT.NOME                              AS NOME_TIPO_INTERVALO,
  IT.COD_UNIDADE,
  IT.ATIVO,
  IT.HORARIO_SUGERIDO,
  IT.ICONE,
  IT.TEMPO_ESTOURO_MINUTOS,
  IT.TEMPO_RECOMENDADO_MINUTOS,
  IT.TIPO_JORNADA,
  IT.COD_AUXILIAR
FROM VIEW_INTERVALO_TIPO IT
WHERE IT.COD_UNIDADE = F_COD_UNIDADE
      AND CASE WHEN F_APENAS_ATIVOS IS TRUE
  THEN IT.ATIVO = TRUE
          ELSE TRUE END
ORDER BY IT.ATIVO DESC, IT.NOME ASC;
$$;