CREATE OR REPLACE FUNCTION FUNC_MARCACAO_VERIFICA_UNIDADE_TEM_TIPO_JORNADA(
  F_COD_UNIDADE BIGINT)
  RETURNS BOOLEAN
LANGUAGE PLPGSQL
AS $$
BEGIN
  RETURN EXISTS(SELECT MTJ.COD_TIPO_JORNADA
                FROM MARCACAO_TIPO_JORNADA MTJ
                WHERE MTJ.COD_UNIDADE = F_COD_UNIDADE);
END;
$$;