CREATE OR REPLACE FUNCTION FUNC_MARCACAO_REMOVE_INFOS_TIPO_JORNADA_UNIDADE(
  F_COD_UNIDADE      BIGINT,
  F_COD_TIPO_EDITADO BIGINT)
  RETURNS BOOLEAN
LANGUAGE PLPGSQL
AS $$
BEGIN
  IF (SELECT TIPO_JORNADA
      FROM VIEW_INTERVALO_TIPO VIT
      WHERE VIT.CODIGO = F_COD_TIPO_EDITADO)
  THEN
    DELETE FROM MARCACAO_TIPOS_DESCONTADOS_CALCULO_JORNADA_BRUTA_LIQUIDA WHERE COD_UNIDADE = F_COD_UNIDADE;
    DELETE FROM MARCACAO_TIPO_JORNADA WHERE COD_UNIDADE = F_COD_UNIDADE;
  END IF;
  RETURN TRUE;
END;
$$;