CREATE OR REPLACE FUNCTION FUNC_MARCACAO_ATUALIZA_INFOS_TIPO_JORNADA_UNIDADE(
  F_COD_UNIDADE BIGINT,
  F_NOVO_COD_TIPO_JORNADA BIGINT)
  RETURNS BOOLEAN
LANGUAGE PLPGSQL
AS $$
DECLARE
  QTDROWS BIGINT;
BEGIN
  DELETE FROM MARCACAO_TIPOS_DESCONTADOS_CALCULO_JORNADA_BRUTA_LIQUIDA WHERE COD_UNIDADE = F_COD_UNIDADE;
  DELETE FROM MARCACAO_TIPO_JORNADA WHERE COD_UNIDADE = F_COD_UNIDADE;

  INSERT INTO MARCACAO_TIPO_JORNADA (COD_UNIDADE, COD_TIPO_JORNADA) VALUES (F_COD_UNIDADE, F_NOVO_COD_TIPO_JORNADA);
  GET DIAGNOSTICS QTDROWS = ROW_COUNT;
  IF QTDROWS = 1
    THEN RETURN TRUE;
  ELSE
    RAISE EXCEPTION 'Erro ao inserir tipo como jornada. Unidade: % e Tipo: %', F_COD_UNIDADE, F_NOVO_COD_TIPO_JORNADA;
  END IF;
END;
$$;