-- CRIA TRIGGER PARA IMPEDIR A DELEÇÃO DE REGISTROS DE TOKEN PARA CHECKLIST OFFLINE
CREATE TRIGGER TG_BLOQUEIO_DELECAO_TOKEN_CHECKLIST_OFFLINE
  BEFORE DELETE
  ON CHECKLIST_OFFLINE_DADOS_UNIDADE
  FOR EACH ROW
EXECUTE PROCEDURE TG_FUNC_BLOQUEIO();