CREATE OR REPLACE FUNCTION TG_FUNC_CHECKLIST_UPDATE_VERSAO_DADOS_OFFLINE_EMPRESA_LIBERADA()
  RETURNS TRIGGER AS $TG_FUNC_UPDATE_VERSAO_DADOS_CHECKLIST_OFFLINE_EMPRESA_LIBERADA$
BEGIN
  UPDATE CHECKLIST_OFFLINE_DADOS_UNIDADE SET VERSAO_DADOS = VERSAO_DADOS + 1
      WHERE COD_UNIDADE IN (SELECT COD_UNIDADE FROM UNIDADE WHERE COD_EMPRESA = OLD.COD_EMPRESA);
  RETURN NEW;
END;
$TG_FUNC_UPDATE_VERSAO_DADOS_CHECKLIST_OFFLINE_EMPRESA_LIBERADA$
LANGUAGE PLPGSQL;

-- CRIA TRIGGER PARA INCREMENTAR A VERSÃO DOS DADOS DE CHECKLIST OFFLINE CASO A EMPRESA TENHA SIDO LIBERADA
CREATE TRIGGER TG_UPDATE_VERSAO_DADOS_CHECKLIST_OFFLINE_EMPRESA_LIBERADA
  AFTER DELETE ON CHECKLIST_OFFLINE_EMPRESA_BLOQUEADA
  FOR EACH ROW
  EXECUTE PROCEDURE TG_FUNC_CHECKLIST_UPDATE_VERSAO_DADOS_OFFLINE_EMPRESA_LIBERADA();