-- CRIA FUNCTION QUE BLOQUEIA O DECREMENTO DE VERSÃO DOS DADOS DE CHECKLIST OFFLINE
CREATE OR REPLACE FUNCTION TG_FUNC_CHECKLIST_BLOQUEIA_DECREMENTO_VERSAO_DADOS_OFFLINE()
  RETURNS TRIGGER AS $TG_BLOQUEIA_DECREMENTO_VERSAO_CHECKLIST_OFFLINE$
BEGIN
  IF (NEW.VERSAO_DADOS < OLD.VERSAO_DADOS)
  THEN
    RAISE EXCEPTION 'NÃO É PERMITIDO DECREMENTAR A VERSÃO DOS DADOS DE CHECKLIST OFFLINE!'
    USING HINT = 'A VERSÃO ATUAL É ' || OLD.VERSAO_DADOS || ' E VOCÊ ESTÁ TENTANDO ALTERAR PARA ' || NEW.VERSAO_DADOS || '.';
  END IF;
  RETURN NEW;
END;
$TG_BLOQUEIA_DECREMENTO_VERSAO_CHECKLIST_OFFLINE$
LANGUAGE PLPGSQL;

-- CRIA TRIGGER PARA BLOQUEAR O DECREMENTO DE VERSÃO DOS DADOS DE CHECKLIST OFFLINE
CREATE TRIGGER TG_BLOQUEIA_DECREMENTO_VERSAO_CHECKLIST_OFFLINE
  BEFORE UPDATE ON CHECKLIST_OFFLINE_DADOS_UNIDADE
  FOR EACH ROW
  EXECUTE PROCEDURE TG_FUNC_CHECKLIST_BLOQUEIA_DECREMENTO_VERSAO_DADOS_OFFLINE();