CREATE OR REPLACE FUNCTION TG_FUNC_CHECKLIST_INSERE_TOKEN_UNIDADE_CHECKLIST_OFFLINE()
  RETURNS TRIGGER AS $TG_UNIDADE_ADICIONA_TOKEN_CHECKLIST_OFFLINE$
BEGIN
  INSERT INTO CHECKLIST_OFFLINE_DADOS_UNIDADE (COD_UNIDADE, TOKEN_SINCRONIZACAO_CHECKLIST)
  VALUES (NEW.CODIGO, F_RANDOM_STRING(64));
  RETURN NEW;
END;
$TG_UNIDADE_ADICIONA_TOKEN_CHECKLIST_OFFLINE$
LANGUAGE plpgsql SECURITY DEFINER;

-- CRIA TRIGGER PARA INSERIR UM TOKEN DE CHECKLIST OFFLINE AO INSERIR UMA UNIDADE
CREATE CONSTRAINT TRIGGER TG_UNIDADE_INSERE_TOKEN_CHECKLIST_OFFLINE
  AFTER INSERT
  ON UNIDADE
  DEFERRABLE
  FOR EACH ROW
EXECUTE PROCEDURE TG_FUNC_CHECKLIST_INSERE_TOKEN_UNIDADE_CHECKLIST_OFFLINE();