CREATE OR REPLACE VIEW CHECKLIST_PERGUNTAS AS
SELECT CP.COD_CHECKLIST_MODELO,
       CP.COD_VERSAO_CHECKLIST_MODELO,
       CP.COD_UNIDADE,
       CP.ORDEM,
       CP.PERGUNTA,
       CP.SINGLE_CHOICE,
       CP.COD_IMAGEM,
       CP.CODIGO,
       CP.CODIGO_CONTEXTO,
       CP.ANEXO_MIDIA_RESPOSTA_OK
FROM CHECKLIST_PERGUNTAS_DATA CP
WHERE CP.DELETADO = FALSE;