CREATE OR REPLACE VIEW CHECKLIST_MODELO AS
    SELECT CM.COD_UNIDADE,
           CM.CODIGO,
           CM.COD_VERSAO_ATUAL,
           CM.NOME,
           CM.STATUS_ATIVO
    FROM CHECKLIST_MODELO_DATA CM
    WHERE CM.DELETADO = FALSE;