CREATE OR REPLACE VIEW CHECKLIST_ALTERNATIVA_PERGUNTA AS
SELECT CAP.COD_CHECKLIST_MODELO,
       CAP.COD_VERSAO_CHECKLIST_MODELO,
       CAP.COD_UNIDADE,
       CAP.ALTERNATIVA,
       CAP.ORDEM,
       CAP.COD_PERGUNTA,
       CAP.CODIGO,
       CAP.CODIGO_CONTEXTO,
       CAP.ALTERNATIVA_TIPO_OUTROS,
       CAP.PRIORIDADE,
       CAP.DEVE_ABRIR_ORDEM_SERVICO,
       CAP.ANEXO_MIDIA
FROM CHECKLIST_ALTERNATIVA_PERGUNTA_DATA CAP
WHERE CAP.DELETADO = FALSE;