CREATE OR REPLACE VIEW CHECKLIST_ORDEM_SERVICO AS
  SELECT
    COS.CODIGO_PROLOG,
    COS.CODIGO,
    COS.COD_UNIDADE,
    COS.COD_CHECKLIST,
    COS.STATUS,
    COS.DATA_HORA_FECHAMENTO
  FROM CHECKLIST_ORDEM_SERVICO_DATA COS
  WHERE COS.DELETADO = FALSE;