-- Sobre:
--
-- Essa view retorna uma lista de itens de ordem de serviço.
--
-- Histórico:
-- 2020-03-02 -> Atualização de arquivo e documentação (wvinim - PL-2494).
-- 2020-11-23 -> Adiciona campo código processo (steinert999 - PL-3335).
CREATE OR REPLACE VIEW CHECKLIST_ORDEM_SERVICO_ITENS AS
SELECT COSI.COD_UNIDADE,
       COSI.CODIGO,
       COSI.COD_OS,
       COSI.CPF_MECANICO,
       COSI.COD_PERGUNTA_PRIMEIRO_APONTAMENTO,
       COSI.COD_CONTEXTO_PERGUNTA,
       COSI.COD_CONTEXTO_ALTERNATIVA,
       COSI.COD_ALTERNATIVA_PRIMEIRO_APONTAMENTO,
       COSI.STATUS_RESOLUCAO,
       COSI.QT_APONTAMENTOS,
       COSI.KM,
       COSI.DATA_HORA_CONSERTO,
       COSI.DATA_HORA_INICIO_RESOLUCAO,
       COSI.DATA_HORA_FIM_RESOLUCAO,
       COSI.TEMPO_REALIZACAO,
       COSI.FEEDBACK_CONSERTO,
       COSI.COD_PROCESSO
FROM CHECKLIST_ORDEM_SERVICO_ITENS_DATA COSI
WHERE COSI.DELETADO = FALSE;