CREATE OR REPLACE FUNCTION FUNC_PRE_CONTRACHEQUE_DELETA_ITENS(F_COD_ITENS BIGINT[])
  RETURNS BIGINT
LANGUAGE PLPGSQL
AS $$
DECLARE
  QTD_LINHAS_ATUALIZADAS BIGINT;
BEGIN
  IF ((SELECT COUNT(CODIGO) FROM PRE_CONTRACHEQUE_ITENS WHERE CODIGO =  ANY (F_COD_ITENS)) <= 0)
  THEN
    PERFORM THROW_GENERIC_ERROR('Os itens selecionados não foram encontrados. Por favor, filtre novamente.');
  END IF;

  -- DELETA ITENS DO PRÉ-CONTRACHEQUE IMPORTADO.
  DELETE FROM PRE_CONTRACHEQUE_ITENS WHERE CODIGO =  ANY (F_COD_ITENS);

  GET DIAGNOSTICS QTD_LINHAS_ATUALIZADAS = ROW_COUNT;

  RETURN QTD_LINHAS_ATUALIZADAS;
END;
$$;