CREATE OR REPLACE FUNCTION FUNC_SOCORRO_ROTA_OPS_PROBLEM_DISP_ABERTURA_SOCORRO_BY_EMP(
    F_COD_EMPRESA BIGINT
)
    RETURNS TABLE
            (
                CODIGO_OPCAO_PROBLEMA           BIGINT,
                DESCRICAO_OPCAO_PROBLEMA        CITEXT,
                OBRIGA_DESCRICAO_OPCAO_PROBLEMA BOOLEAN
            )
    LANGUAGE SQL
AS
$$
SELECT SROP.CODIGO    AS     CODIGO_OPCAO_PROBLEMA,
       SROP.DESCRICAO AS     DESCRICAO_OPCAO_PROBLEMA,
       SROP.OBRIGA_DESCRICAO OBRIGA_DESCRICAO_OPCAO_PROBLEMA
FROM SOCORRO_ROTA_OPCAO_PROBLEMA SROP
WHERE SROP.COD_EMPRESA = F_COD_EMPRESA
  AND SROP.STATUS_ATIVO = TRUE
ORDER BY SROP.DESCRICAO;
$$;