CREATE VIEW RESUMO_DADOS AS
  SELECT DISTINCT
    M.DATA AS MAPA,
    T.DATA AS TRACKING,
    M.COD_UNIDADE,
    T."código_transportadora"
  FROM (MAPA M
    LEFT JOIN TRACKING T ON ((M.DATA = T.DATA)))
  ORDER BY M.DATA DESC, T.DATA;

COMMENT ON VIEW RESUMO_DADOS
IS 'VIEW UTILIZADA PARA JUNTAR AS DATAS QUE TEM DADOS ENVIADOS AO SISTEMA, PLANILHAS AMBEV (2ART E TRACKING)';