-- Sobre:
--
-- Esta função retorna a lista de configurações para uma nova aferição avulsa de acordo com uma placa.
--
-- Histórico:
-- 2019-12-10 -> Adição de colunas de bloqueio  (wvinim - PL-1934).
-- 2020-05-07 -> Modifica campos de retorno de liberação de aferição de boolean para text (gustavocnp95 - PL-2689)
CREATE OR REPLACE FUNCTION FUNC_AFERICAO_GET_CONFIGURACOES_NOVA_AFERICAO_PLACA(F_PLACA_VEICULO TEXT)
    RETURNS TABLE
            (
                SULCO_MINIMO_DESCARTE                  REAL,
                SULCO_MINIMO_RECAPAGEM                 REAL,
                TOLERANCIA_CALIBRAGEM                  REAL,
                TOLERANCIA_INSPECAO                    REAL,
                PERIODO_AFERICAO_SULCO                 INTEGER,
                PERIODO_AFERICAO_PRESSAO               INTEGER,
                FORMA_COLETA_DADOS_SULCO               TEXT,
                FORMA_COLETA_DADOS_PRESSAO             TEXT,
                FORMA_COLETA_DADOS_SULCO_PRESSAO       TEXT,
                PODE_AFERIR_ESTEPE                     BOOLEAN,
                VARIACAO_ACEITA_SULCO_MENOR_MILIMETROS DOUBLE PRECISION,
                VARIACAO_ACEITA_SULCO_MAIOR_MILIMETROS DOUBLE PRECISION,
                BLOQUEAR_VALORES_MENORES               BOOLEAN,
                BLOQUEAR_VALORES_MAIORES               BOOLEAN,
                VARIACOES_SULCO_DEFAULT_PROLOG         BOOLEAN
            )
    LANGUAGE PLPGSQL
AS
$$
DECLARE
    F_COD_UNIDADE      BIGINT;
    F_COD_TIPO_VEICULO BIGINT;
BEGIN
    SELECT INTO F_COD_UNIDADE, F_COD_TIPO_VEICULO V.COD_UNIDADE,
                                                  V.COD_TIPO
    FROM VEICULO V
    WHERE V.PLACA = F_PLACA_VEICULO;

    RETURN QUERY
        SELECT PRU.SULCO_MINIMO_DESCARTE,
               PRU.SULCO_MINIMO_RECAPAGEM,
               PRU.TOLERANCIA_INSPECAO,
               PRU.TOLERANCIA_CALIBRAGEM,
               PRU.PERIODO_AFERICAO_SULCO,
               PRU.PERIODO_AFERICAO_PRESSAO,
               CONFIG_PODE_AFERIR.FORMA_COLETA_DADOS_SULCO,
               CONFIG_PODE_AFERIR.FORMA_COLETA_DADOS_PRESSAO,
               CONFIG_PODE_AFERIR.FORMA_COLETA_DADOS_SULCO_PRESSAO,
               CONFIG_PODE_AFERIR.PODE_AFERIR_ESTEPE,
               CONFIG_ALERTA_SULCO.VARIACAO_ACEITA_SULCO_MENOR_MILIMETROS,
               CONFIG_ALERTA_SULCO.VARIACAO_ACEITA_SULCO_MAIOR_MILIMETROS,
               CONFIG_ALERTA_SULCO.BLOQUEAR_VALORES_MENORES,
               CONFIG_ALERTA_SULCO.BLOQUEAR_VALORES_MAIORES,
               CONFIG_ALERTA_SULCO.USA_DEFAULT_PROLOG AS VARIACOES_SULCO_DEFAULT_PROLOG
        FROM FUNC_AFERICAO_GET_CONFIG_TIPO_AFERICAO_VEICULO(F_COD_UNIDADE) AS CONFIG_PODE_AFERIR
                 JOIN VIEW_AFERICAO_CONFIGURACAO_ALERTA_SULCO AS CONFIG_ALERTA_SULCO
                      ON CONFIG_PODE_AFERIR.COD_UNIDADE_CONFIGURACAO = CONFIG_ALERTA_SULCO.COD_UNIDADE
                 JOIN PNEU_RESTRICAO_UNIDADE PRU
                      ON PRU.COD_UNIDADE = CONFIG_PODE_AFERIR.COD_UNIDADE_CONFIGURACAO
        WHERE CONFIG_PODE_AFERIR.COD_UNIDADE_CONFIGURACAO = F_COD_UNIDADE
          AND CONFIG_PODE_AFERIR.COD_TIPO_VEICULO = F_COD_TIPO_VEICULO;
END;
$$;