CREATE OR REPLACE FUNCTION FUNC_AFERICAO_GET_CONFIGURACOES_NOVA_AFERICAO_AVULSA(F_COD_PNEU BIGINT)
    RETURNS TABLE
            (
                SULCO_MINIMO_DESCARTE                  REAL,
                SULCO_MINIMO_RECAPAGEM                 REAL,
                TOLERANCIA_CALIBRAGEM                  REAL,
                TOLERANCIA_INSPECAO                    REAL,
                PERIODO_AFERICAO_SULCO                 INTEGER,
                PERIODO_AFERICAO_PRESSAO               INTEGER,
                VARIACAO_ACEITA_SULCO_MENOR_MILIMETROS DOUBLE PRECISION,
                VARIACAO_ACEITA_SULCO_MAIOR_MILIMETROS DOUBLE PRECISION,
                BLOQUEAR_VALORES_MENORES               BOOLEAN,
                BLOQUEAR_VALORES_MAIORES               BOOLEAN,
                VARIACOES_SULCO_DEFAULT_PROLOG         BOOLEAN
            )
    LANGUAGE PLPGSQL
AS
$$
DECLARE
    F_COD_UNIDADE BIGINT;
BEGIN
    SELECT INTO F_COD_UNIDADE P.COD_UNIDADE
    FROM PNEU P
    WHERE P.CODIGO = F_COD_PNEU;

    RETURN QUERY
        SELECT PRU.SULCO_MINIMO_DESCARTE                                  AS SULCO_MINIMO_DESCARTE,
               PRU.SULCO_MINIMO_RECAPAGEM                                 AS SULCO_MINIMO_RECAPAGEM,
               PRU.TOLERANCIA_INSPECAO                                    AS TOLERANCIA_INSPECAO,
               PRU.TOLERANCIA_CALIBRAGEM                                  AS TOLERANCIA_CALIBRAGEM,
               PRU.PERIODO_AFERICAO_SULCO                                 AS PERIODO_AFERICAO_SULCO,
               PRU.PERIODO_AFERICAO_PRESSAO                               AS PERIODO_AFERICAO_PRESSAO,
               CONFIG_ALERTA_SULCO.VARIACAO_ACEITA_SULCO_MENOR_MILIMETROS AS VARIACAO_ACEITA_SULCO_MENOR_MILIMETROS,
               CONFIG_ALERTA_SULCO.VARIACAO_ACEITA_SULCO_MAIOR_MILIMETROS AS VARIACAO_ACEITA_SULCO_MAIOR_MILIMETROS,
               CONFIG_ALERTA_SULCO.BLOQUEAR_VALORES_MENORES               AS BLOQUEAR_VALORES_MENORES,
               CONFIG_ALERTA_SULCO.BLOQUEAR_VALORES_MAIORES               AS BLOQUEAR_VALORES_MAIORES,
               CONFIG_ALERTA_SULCO.USA_DEFAULT_PROLOG                     AS VARIACOES_SULCO_DEFAULT_PROLOG
        FROM VIEW_AFERICAO_CONFIGURACAO_ALERTA_SULCO CONFIG_ALERTA_SULCO
                 JOIN PNEU_RESTRICAO_UNIDADE PRU
                      ON PRU.COD_UNIDADE = CONFIG_ALERTA_SULCO.COD_UNIDADE
        WHERE CONFIG_ALERTA_SULCO.COD_UNIDADE = F_COD_UNIDADE;
END;
$$;