
package br.com.zalf.prolog.webservice.integracao.avacorpavilan.deprecated.afericao.service;

import br.com.zalf.prolog.webservice.integracao.avacorpavilan.deprecated.AvaCorpAvilanConstants;
import br.com.zalf.prolog.webservice.integracao.avacorpavilan.deprecated.afericao.AfericoesFiltro;
import br.com.zalf.prolog.webservice.integracao.avacorpavilan.deprecated.afericao.IncluirMedida2;
import br.com.zalf.prolog.webservice.integracao.avacorpavilan.deprecated.afericao.IncluirRegistroVeiculo;
import br.com.zalf.prolog.webservice.integracao.avacorpavilan.deprecated.afericao.ObjectFactory;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AfericaoSoap", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AfericaoAvaCorpAvilanSoap {


    /**
     * 
     * @param medida
     * @return
     *     returns br.com.avacorp.integracaoprolog.IncluirRegistroVeiculo
     */
    @WebMethod(action = AvaCorpAvilanConstants.NAMESPACE + "/incluirMedida")
    @WebResult(name = "incluirMedidaResult", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
    @RequestWrapper(localName = "incluirMedida", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.IncluirMedida")
    @ResponseWrapper(localName = "incluirMedidaResponse", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprolog.IncluirMedidaResponse")
    public IncluirRegistroVeiculo incluirMedida(
            @WebParam(name = "medida", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    IncluirMedida2 medida);

    /**
     *
     * @param veiculo
     * @param tipoVeiculo
     * @param filial
     * @param unidade
     * @param dataInicial
     * @param dataFinal
     * @return
     *     returns br.com.avacorp.integracaoprologtestes.AfericoesFiltro
     */
    @WebMethod(action = AvaCorpAvilanConstants.NAMESPACE + "/buscarAfericoesFiltro")
    @WebResult(name = "buscarAfericoesFiltroResult", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
    @RequestWrapper(localName = "buscarAfericoesFiltro", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprologtestes.BuscarAfericoesFiltro")
    @ResponseWrapper(localName = "buscarAfericoesFiltroResponse", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprologtestes.BuscarAfericoesFiltroResponse")
    public AfericoesFiltro buscarAfericoesFiltro(
            @WebParam(name = "filial", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    int filial,
            @WebParam(name = "unidade", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    int unidade,
            @WebParam(name = "dataInicial", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String dataInicial,
            @WebParam(name = "dataFinal", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String dataFinal,
            @WebParam(name = "veiculo", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String veiculo,
            @WebParam(name = "tipoVeiculo", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    String tipoVeiculo,
            @WebParam(name = "limit", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    int limit,
            @WebParam(name = "offset", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    int offset);

    /**
     *
     * @param codigo
     * @return
     *     returns br.com.avacorp.integracaoprologtestes.AfericoesFiltro
     */
    @WebMethod(action = AvaCorpAvilanConstants.NAMESPACE + "/buscarAfericoesFiltroEspecifico")
    @WebResult(name = "buscarAfericoesFiltroEspecificoResult", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
    @RequestWrapper(localName = "buscarAfericoesFiltroEspecifico", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprologtestes.BuscarAfericoesFiltroEspecifico")
    @ResponseWrapper(localName = "buscarAfericoesFiltroEspecificoResponse", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, className = "br.com.avacorp.integracaoprologtestes.BuscarAfericoesFiltroEspecificoResponse")
    public AfericoesFiltro buscarAfericoesFiltroEspecifico(
            @WebParam(name = "codigo", targetNamespace = AvaCorpAvilanConstants.NAMESPACE)
                    int codigo);

}