
package br.com.zalf.prolog.webservice.integracao.avacorpavilan.deprecated.afericao.service;

import br.com.zalf.prolog.webservice.integracao.avacorpavilan.deprecated.AvaCorpAvilanConstants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * Web Service para integracao do Avacorp com o ProLog
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Afericao", targetNamespace = AvaCorpAvilanConstants.NAMESPACE, wsdlLocation = AvaCorpAvilanConstants.BASE_URL + "Afericao.asmx?WSDL")
public class AfericaoAvaCorpAvilanService extends Service {

    private final static URL AFERICAO_WSDL_LOCATION;
    private final static WebServiceException AFERICAO_EXCEPTION;
    private final static QName AFERICAO_QNAME = new QName(AvaCorpAvilanConstants.NAMESPACE, "Afericao");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(AvaCorpAvilanConstants.BASE_URL + "Afericao.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AFERICAO_WSDL_LOCATION = url;
        AFERICAO_EXCEPTION = e;
    }

    public AfericaoAvaCorpAvilanService() {
        super(__getWsdlLocation(), AFERICAO_QNAME);
    }

    public AfericaoAvaCorpAvilanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AFERICAO_QNAME, features);
    }

    public AfericaoAvaCorpAvilanService(URL wsdlLocation) {
        super(wsdlLocation, AFERICAO_QNAME);
    }

    public AfericaoAvaCorpAvilanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AFERICAO_QNAME, features);
    }

    public AfericaoAvaCorpAvilanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AfericaoAvaCorpAvilanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AfericaoSoap
     */
    @WebEndpoint(name = "AfericaoSoap")
    public AfericaoAvaCorpAvilanSoap getAfericaoSoap() {
        return super.getPort(new QName(AvaCorpAvilanConstants.NAMESPACE, "AfericaoSoap"), AfericaoAvaCorpAvilanSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AfericaoSoap
     */
    @WebEndpoint(name = "AfericaoSoap")
    public AfericaoAvaCorpAvilanSoap getAfericaoSoap(WebServiceFeature... features) {
        return super.getPort(new QName(AvaCorpAvilanConstants.NAMESPACE, "AfericaoSoap"), AfericaoAvaCorpAvilanSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AFERICAO_EXCEPTION!= null) {
            throw AFERICAO_EXCEPTION;
        }
        return AFERICAO_WSDL_LOCATION;
    }

}
