
package br.com.zalf.prolog.webservice.integracao.avacorpavilan.cadastro;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CadastroSoap", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CadastroAvaCorpAvilanSoap {


    /**
     * Busca Veiculos ativos
     * 
     * @param cpf
     * @return
     *     returns br.com.avacorp.integracaoprolog.VeiculosAtivos
     */
    @WebMethod(action = "http://www.avacorp.com.br/integracaoprolog/buscarVeiculosAtivos")
    @WebResult(name = "buscarVeiculosAtivosResult", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
    @RequestWrapper(localName = "buscarVeiculosAtivos", targetNamespace = "http://www.avacorp.com.br/integracaoprolog", className = "br.com.avacorp.integracaoprolog.BuscarVeiculosAtivos")
    @ResponseWrapper(localName = "buscarVeiculosAtivosResponse", targetNamespace = "http://www.avacorp.com.br/integracaoprolog", className = "br.com.avacorp.integracaoprolog.BuscarVeiculosAtivosResponse")
    public VeiculosAtivos buscarVeiculosAtivos(
            @WebParam(name = "cpf", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    String cpf);

    /**
     * Busca Pneus de um  veiculo
     * 
     * @param veiculo
     * @return
     *     returns br.com.avacorp.integracaoprolog.PneusVeiculo
     */
    @WebMethod(action = "http://www.avacorp.com.br/integracaoprolog/buscarPneusVeiculo")
    @WebResult(name = "buscarPneusVeiculoResult", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
    @RequestWrapper(localName = "buscarPneusVeiculo", targetNamespace = "http://www.avacorp.com.br/integracaoprolog", className = "br.com.avacorp.integracaoprolog.BuscarPneusVeiculo")
    @ResponseWrapper(localName = "buscarPneusVeiculoResponse", targetNamespace = "http://www.avacorp.com.br/integracaoprolog", className = "br.com.avacorp.integracaoprolog.BuscarPneusVeiculoResponse")
    public PneusVeiculo buscarPneusVeiculo(
            @WebParam(name = "veiculo", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    String veiculo);

    /**
     * Busca usuário para integração
     * 
     * @param cpf
     * @param dataNascimento
     * @return
     *     returns br.com.avacorp.integracaoprolog.UsuarioIntegracao
     */
    @WebMethod(action = "http://www.avacorp.com.br/integracaoprolog/buscarUsuarioIntegracao")
    @WebResult(name = "buscarUsuarioIntegracaoResult", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
    @RequestWrapper(localName = "buscarUsuarioIntegracao", targetNamespace = "http://www.avacorp.com.br/integracaoprolog", className = "br.com.avacorp.integracaoprolog.BuscarUsuarioIntegracao")
    @ResponseWrapper(localName = "buscarUsuarioIntegracaoResponse", targetNamespace = "http://www.avacorp.com.br/integracaoprolog", className = "br.com.avacorp.integracaoprolog.BuscarUsuarioIntegracaoResponse")
    public UsuarioIntegracao buscarUsuarioIntegracao(
            @WebParam(name = "cpf", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    String cpf,
            @WebParam(name = "dataNascimento", targetNamespace = "http://www.avacorp.com.br/integracaoprolog")
                    String dataNascimento);

}
