CREATE OR REPLACE FUNCTION FUNC_VEICULO_TRANSFERENCIA_DETALHES_PLACA_TRANSFERIDA(
  F_COD_PROCESSO_TRANSFERENCIA BIGINT,
  F_COD_VEICULO                BIGINT)
  RETURNS TABLE(
    PLACA_VEICULO                           TEXT,
    COD_DIAGRAMA_VEICULO                    BIGINT,
    NOME_TIPO_VEICULO_MOMENTO_TRANSFERENCIA TEXT,
    COD_PNEU                                BIGINT,
    CODIGO_CLIENTE                          TEXT,
    ALTURA_SULCO_EXTERNO                    REAL,
    ALTURA_SULCO_CENTRAL_EXTERNO            REAL,
    ALTURA_SULCO_CENTRAL_INTERNO            REAL,
    ALTURA_SULCO_INTERNO                    REAL,
    PRESSAO_PNEU                            REAL,
    VIDA_MOMENTO_TRANSFERENCIA              INTEGER,
    POSICAO_PNEU_TRANSFERENCIA              INTEGER)
LANGUAGE PLPGSQL
AS $$
BEGIN
  RETURN QUERY
  SELECT
    V.PLACA::TEXT                    AS PLACA_VEICULO,
    VTI.COD_DIAGRAMA_VEICULO         AS COD_DIAGRAMA_VEICULO,
    VT.NOME::TEXT                    AS NOME_TIPO_VEICULO_MOMENTO_TRANSFERENCIA,
    PTI.COD_PNEU                     AS COD_PNEU,
    P.CODIGO_CLIENTE::TEXT           AS CODIGO_CLIENTE,
    PTI.ALTURA_SULCO_EXTERNO         AS ALTURA_SULCO_EXTERNO,
    PTI.ALTURA_SULCO_CENTRAL_EXTERNO AS ALTURA_SULCO_CENTRAL_EXTERNO,
    PTI.ALTURA_SULCO_CENTRAL_INTERNO AS ALTURA_SULCO_CENTRAL_INTERNO,
    PTI.ALTURA_SULCO_INTERNO         AS ALTURA_SULCO_INTERNO,
    PTI.PSI                          AS PRESSAO_PNEU,
    PTI.VIDA_MOMENTO_TRANSFERENCIA   AS VIDA_MOMENTO_TRANSFERENCIA,
    PTI.POSICAO_PNEU_TRANSFERENCIA   AS POSICAO_PNEU_TRANSFERENCIA
  FROM VEICULO_TRANSFERENCIA_PROCESSO VTP
    JOIN VEICULO_TRANSFERENCIA_INFORMACOES VTI ON VTP.CODIGO = VTI.COD_PROCESSO_TRANSFERENCIA
    JOIN VEICULO V ON VTI.COD_VEICULO = V.CODIGO
    JOIN VEICULO_TIPO VT ON V.COD_TIPO = VT.CODIGO
    LEFT JOIN VEICULO_TRANSFERENCIA_VINCULO_PROCESSO_PNEU VTVPP
      ON VTI.CODIGO = VTVPP.COD_VEICULO_TRANSFERENCIA_INFORMACOES
    LEFT JOIN PNEU_TRANSFERENCIA_PROCESSO PTP ON VTVPP.COD_PROCESSO_TRANSFERENCIA_PNEU = PTP.CODIGO
    LEFT JOIN PNEU_TRANSFERENCIA_INFORMACOES PTI ON PTP.CODIGO = PTI.COD_PROCESSO_TRANSFERENCIA
    LEFT JOIN PNEU P ON PTI.COD_PNEU = P.CODIGO
  WHERE VTP.CODIGO = F_COD_PROCESSO_TRANSFERENCIA
        AND VTI.COD_VEICULO = F_COD_VEICULO;
END;
$$;