-- Sobre:
--
-- function utilizada para gerar o relatório de estratificação de mapa.
-- Nome no front: Mapa - Relatório de entrega.
-- Path no back: "/mapas/estratificados/{codUnidade}/csv" e "/mapas/estratificados/{codUnidade}/report".
--
-- Histórico:
-- 2020-06-22 -> Adiciona data de import (thaisksf - PL-2723).
-- 2020-11-04 -> Corrige filtro de data (luizfp - PS-1315).
create or replace function func_relatorio_mapa_estratificado(f_cod_unidade bigint, f_data_inicial date, f_data_final date)
    returns table
            (
                data                           character varying,
                placa                          character varying,
                mapa                           integer,
                "MATRIC MOTORISTA"             integer,
                "NOME MOTORISTA"               text,
                "MATRIC AJUDANTE 1"            integer,
                "NOME AJUDANTE 1"              text,
                "MATRIC AJUDANTE 2"            integer,
                "NOME AJUDANTE 2"              text,
                entregas                       integer,
                cxcarreg                       real,
                cxentreg                       real,
                transp                         integer,
                entrega                        character varying,
                cargaatual                     text,
                frota                          text,
                custospot                      real,
                regiao                         integer,
                veiculo                        integer,
                veiculoindisp                  real,
                placaindisp                    real,
                frotaindisp                    real,
                tipoindisp                     integer,
                ocupacao                       real,
                cxrota                         real,
                cxas                           real,
                veicbm                         real,
                rshow                          integer,
                entrvol                        character varying,
                hrsai                          timestamp without time zone,
                hrentr                         timestamp without time zone,
                kmsai                          integer,
                kmentr                         integer,
                custovariavel                  real,
                lucro                          real,
                lucrounit                      real,
                valorfrete                     real,
                tipoimposto                    character varying,
                percimposto                    real,
                valorimposto                   real,
                valorfaturado                  real,
                valorunitcxentregue            real,
                valorpgcxentregsemimp          real,
                valorpgcxentregcomimp          real,
                tempoprevistoroad              time without time zone,
                kmprevistoroad                 real,
                valorunitpontomot              real,
                valorunitpontoajd              real,
                valorequipeentrmot             real,
                valorequipeentrajd             real,
                custovariavelcedbz             real,
                lucrounitcedbz                 real,
                lucrovariavelcxentregueffcedbz real,
                tempointerno                   time without time zone,
                valordropdown                  real,
                veiccaddd                      character varying,
                kmlaco                         real,
                kmdeslocamento                 real,
                tempolaco                      time without time zone,
                tempodeslocamento              time without time zone,
                sitmulticdd                    real,
                unborigem                      integer,
                valorctedifere                 character varying,
                qtnfcarregadas                 integer,
                qtnfentregues                  integer,
                inddevcx                       real,
                inddevnf                       real,
                fator                          real,
                recarga                        character varying,
                hrmatinal                      time without time zone,
                hrjornadaliq                   time without time zone,
                hrmetajornada                  time without time zone,
                vlbateujornmot                 real,
                vlnaobateujornmot              real,
                vlrecargamot                   real,
                vlbateujornaju                 real,
                vlnaobateujornaju              real,
                vlrecargaaju                   real,
                vltotalmapa                    real,
                qthlcarregados                 real,
                qthlentregues                  real,
                indicedevhl                    real,
                regiao2                        character varying,
                qtnfcarreggeral                integer,
                qtnfentreggeral                integer,
                capacidadeveiculokg            real,
                pesocargakg                    real,
                capacveiculocx                 integer,
                entregascompletas              integer,
                entregasparciais               integer,
                entregasnaorealizadas          integer,
                codfilial                      integer,
                nomefilial                     character varying,
                codsupervtrs                   integer,
                nomesupervtrs                  character varying,
                codspot                        integer,
                nomespot                       text,
                equipcarregados                integer,
                equipdevolvidos                integer,
                equiprecolhidos                integer,
                cxentregtracking               real,
                hrcarreg                       timestamp without time zone,
                hrpcfisica                     timestamp without time zone,
                hrpcfinanceira                 timestamp without time zone,
                stmapa                         character varying,
                totalapontamentostracking      bigint,
                apontamentosok                 bigint,
                apontamentosnok                bigint,
                aderencia                      double precision,
                data_hora_import               character varying
            )
    language sql
as
$$
select to_char(m.data, 'DD/MM/YYYY'),
       placa,
       mapa,
       matricmotorista,
       coalesce(motorista.nome, '-')                                                  as nome_motorista,
       matricajud1,
       coalesce(ajudante1.nome, '-')                                                  as nome_ajudante1,
       matricajud2,
       coalesce(ajudante2.nome, '-')                                                  as nome_ajudante2,
       entregas                                                                       as entregas,
       cxcarreg                                                                       as cxcarreg,
       cxentreg                                                                       as cxentreg,
       transp                                                                         as transp,
       entrega                                                                        as entrega,
       cargaatual                                                                     as cargaatual,
       frota                                                                          as frota,
       custospot                                                                      as custospot,
       regiao                                                                         as regiao,
       veiculo                                                                        as veiculo,
       veiculoindisp                                                                  as veiculoindisp,
       placaindisp                                                                    as placaindisp,
       frotaindisp                                                                    as frotaindisp,
       tipoindisp                                                                     as tipoindisp,
       ocupacao                                                                       as ocupacao,
       cxrota                                                                         as cxrota,
       cxas                                                                           as cxas,
       veicbm                                                                         as veicbm,
       rshow                                                                          as rshow,
       entrvol                                                                        as entrvol,
       hrsai                                                                          as hrsai,
       hrentr                                                                         as hrentr,
       kmsai                                                                          as kmsai,
       kmentr                                                                         as kmentr,
       custovariavel                                                                  as custovariavel,
       lucro                                                                          as lucro,
       lucrounit                                                                      as lucrounit,
       valorfrete                                                                     as valorfrete,
       tipoimposto                                                                    as tipoimposto,
       percimposto                                                                    as percimposto,
       valorimposto                                                                   as valorimposto,
       valorfaturado                                                                  as valorfaturado,
       valorunitcxentregue                                                            as valorunitcxentregue,
       valorpgcxentregsemimp                                                          as valorpgcxentregsemimp,
       valorpgcxentregcomimp                                                          as valorpgcxentregcomimp,
       tempoprevistoroad                                                              as tempoprevistoroad,
       kmprevistoroad                                                                 as kmprevistoroad,
       valorunitpontomot                                                              as valorunitpontomot,
       valorunitpontoajd                                                              as valorunitpontoajd,
       valorequipeentrmot                                                             as valorequipeentrmot,
       valorequipeentrajd                                                             as valorequipeentrajd,
       custovariavelcedbz                                                             as custovariavelcedbz,
       lucrounitcedbz                                                                 as lucrounitcedbz,
       lucrovariavelcxentregueffcedbz                                                 as lucrovariavelcxentregueffcedbz,
       tempointerno                                                                   as tempointerno,
       valordropdown                                                                  as valordropdown,
       veiccaddd                                                                      as veiccaddd,
       kmlaco                                                                         as kmlaco,
       kmdeslocamento                                                                 as kmdeslocamento,
       tempolaco                                                                      as tempolaco,
       tempodeslocamento                                                              as tempodeslocamento,
       sitmulticdd                                                                    as sitmulticdd,
       unborigem                                                                      as unborigem,
       valorctedifere                                                                 as valorctedifere,
       qtnfcarregadas                                                                 as qtnfcarregadas,
       qtnfentregues                                                                  as qtnfentregues,
       inddevcx                                                                       as inddevcx,
       inddevnf                                                                       as inddevnf,
       fator                                                                          as fator,
       recarga                                                                        as recarga,
       hrmatinal                                                                      as hrmatinal,
       hrjornadaliq                                                                   as hrjornadaliq,
       hrmetajornada                                                                  as hrmetajornada,
       vlbateujornmot                                                                 as vlbateujornmot,
       vlnaobateujornmot                                                              as vlnaobateujornmot,
       vlrecargamot                                                                   as vlrecargamot,
       vlbateujornaju                                                                 as vlbateujornaju,
       vlnaobateujornaju                                                              as vlnaobateujornaju,
       vlrecargaaju                                                                   as vlrecargaaju,
       vltotalmapa                                                                    as vltotalmapa,
       qthlcarregados                                                                 as qthlcarregados,
       qthlentregues                                                                  as qthlentregues,
       indicedevhl                                                                    as indicedevhl,
       regiao2                                                                        as regiao2,
       qtnfcarreggeral                                                                as qtnfcarreggeral,
       qtnfentreggeral                                                                as qtnfentreggeral,
       capacidadeveiculokg                                                            as capacidadeveiculokg,
       pesocargakg                                                                    as pesocargakg,
       capacveiculocx                                                                 as capacveiculocx,
       entregascompletas                                                              as entregascompletas,
       entregasparciais                                                               as entregasparciais,
       entregasnaorealizadas                                                          as entregasnaorealizadas,
       codfilial                                                                      as codfilial,
       nomefilial                                                                     as nomefilial,
       codsupervtrs                                                                   as codsupervtrs,
       nomesupervtrs                                                                  as nomesupervtrs,
       codspot                                                                        as codspot,
       nomespot                                                                       as nomespot,
       equipcarregados                                                                as equipcarregados,
       equipdevolvidos                                                                as equipdevolvidos,
       equiprecolhidos                                                                as equiprecolhidos,
       cxentregtracking                                                               as cxentregtracking,
       hrcarreg                                                                       as hrcarreg,
       hrpcfisica                                                                     as hrpcfisica,
       hrpcfinanceira                                                                 as hrpcfinanceira,
       stmapa                                                                         as stmapa,
       tracking.total_apontamentos                                                    as total_apontamentos,
       tracking.apontamentos_ok                                                       as apontamentos_ok,
       tracking.total_apontamentos - tracking.apontamentos_ok                         as apontamentos_nok,
       trunc((tracking.apontamentos_ok :: float / tracking.total_apontamentos) * 100) as aderencia,
       to_char(m.data_hora_import, 'DD/MM/YYYY HH24:MI')                              as data_hora_import
from mapa m
         join unidade_funcao_produtividade ufp on ufp.cod_unidade = m.cod_unidade
         left join colaborador motorista
                   on motorista.cod_unidade = m.cod_unidade and motorista.cod_funcao = ufp.cod_funcao_motorista
                       and motorista.matricula_ambev = m.matricmotorista
         left join colaborador ajudante1
                   on ajudante1.cod_unidade = m.cod_unidade and ajudante1.cod_funcao = ufp.cod_funcao_ajudante
                       and ajudante1.matricula_ambev = m.matricajud1
         left join colaborador ajudante2
                   on ajudante2.cod_unidade = m.cod_unidade and ajudante2.cod_funcao = ufp.cod_funcao_ajudante
                       and ajudante2.matricula_ambev = m.matricajud2
         left join (select t.mapa                         as tracking_mapa,
                           t.código_transportadora           tracking_unidade,
                           count(t.disp_apont_cadastrado) as total_apontamentos,
                           sum(case
                                   when t.disp_apont_cadastrado <= um.meta_raio_tracking
                                       then 1
                                   else 0 end)            as apontamentos_ok
                    from tracking t
                             join unidade_metas um on um.cod_unidade = t.código_transportadora
                    group by 1, 2) as tracking on tracking_mapa = m.mapa and tracking_unidade = m.cod_unidade
where m.cod_unidade = f_cod_unidade
  and m.data between f_data_inicial and f_data_final
order by m.mapa
$$;