-- Sobre:
--
-- Esta função retorna uma lista com as configurações de aferição por unidade.
-- Retorna valores padrão para as unidades que ainda não tem as configurações setadas.
--
-- Histórico:
-- 2019-12-10 -> Adição de colunas de bloqueio  (wvinim - PL-1934).
CREATE OR REPLACE VIEW VIEW_AFERICAO_CONFIGURACAO_ALERTA_SULCO AS
WITH CONFIGURACAO_PROLOG AS (
    SELECT AP.VARIACAO_ACEITA_SULCO_MAIOR_MILIMETROS,
           AP.VARIACAO_ACEITA_SULCO_MENOR_MILIMETROS,
           AP.BLOQUEAR_VALORES_MENORES,
           AP.BLOQUEAR_VALORES_MAIORES
    FROM AFERICAO_CONFIGURACAO_PROLOG AP
)
SELECT U.CODIGO                                                               AS COD_UNIDADE,
       CONFIG.CODIGO                                                          AS COD_CONFIG,
       COALESCE(CONFIG.VARIACAO_ACEITA_SULCO_MENOR_MILIMETROS,
                CP.VARIACAO_ACEITA_SULCO_MENOR_MILIMETROS)                    AS VARIACAO_ACEITA_SULCO_MENOR_MILIMETROS,
       COALESCE(CONFIG.VARIACAO_ACEITA_SULCO_MAIOR_MILIMETROS,
                CP.VARIACAO_ACEITA_SULCO_MAIOR_MILIMETROS)                    AS VARIACAO_ACEITA_SULCO_MAIOR_MILIMETROS,
       F_IF(CONFIG.CODIGO IS NULL, TRUE, FALSE)                               AS USA_DEFAULT_PROLOG,
       COALESCE(CONFIG.BLOQUEAR_VALORES_MENORES, CP.BLOQUEAR_VALORES_MENORES) AS BLOQUEAR_VALORES_MENORES,
       COALESCE(CONFIG.BLOQUEAR_VALORES_MAIORES, CP.BLOQUEAR_VALORES_MAIORES) AS BLOQUEAR_VALORES_MAIORES
FROM UNIDADE U
         LEFT JOIN AFERICAO_CONFIGURACAO_ALERTA_SULCO CONFIG ON U.CODIGO = CONFIG.COD_UNIDADE
         FULL JOIN CONFIGURACAO_PROLOG CP ON TRUE;