CREATE OR REPLACE FUNCTION FUNC_PNEUS_GET_LISTAGEM_PNEUS_MOVIMENTACOES_ANALISE(F_COD_UNIDADE BIGINT)
  RETURNS TABLE(
    CODIGO                       BIGINT,
    CODIGO_CLIENTE               TEXT,
    DOT                          TEXT,
    VALOR                        REAL,
    COD_UNIDADE_ALOCADO          BIGINT,
    NOME_UNIDADE_ALOCADO         TEXT,
    COD_REGIONAL_ALOCADO         BIGINT,
    NOME_REGIONAL_ALOCADO        TEXT,
    PNEU_NOVO_NUNCA_RODADO       BOOLEAN,
    COD_MARCA_PNEU               BIGINT,
    NOME_MARCA_PNEU              TEXT,
    COD_MODELO_PNEU              BIGINT,
    NOME_MODELO_PNEU             TEXT,
    QT_SULCOS_MODELO_PNEU        SMALLINT,
    COD_MARCA_BANDA              BIGINT,
    NOME_MARCA_BANDA             TEXT,
    ALTURA_SULCOS_MODELO_PNEU    REAL,
    COD_MODELO_BANDA             BIGINT,
    NOME_MODELO_BANDA            TEXT,
    QT_SULCOS_MODELO_BANDA       SMALLINT,
    ALTURA_SULCOS_MODELO_BANDA   REAL,
    VALOR_BANDA                  REAL,
    ALTURA                       INTEGER,
    LARGURA                      INTEGER,
    ARO                          REAL,
    COD_DIMENSAO                 BIGINT,
    ALTURA_SULCO_CENTRAL_INTERNO REAL,
    ALTURA_SULCO_CENTRAL_EXTERNO REAL,
    ALTURA_SULCO_INTERNO         REAL,
    ALTURA_SULCO_EXTERNO         REAL,
    PRESSAO_RECOMENDADA          REAL,
    PRESSAO_ATUAL                REAL,
    STATUS                       TEXT,
    VIDA_ATUAL                   INTEGER,
    VIDA_TOTAL                   INTEGER,
    POSICAO_PNEU                 INTEGER,
    POSICAO_APLICADO_CLIENTE     TEXT,
    COD_VEICULO_APLICADO         BIGINT,
    PLACA_APLICADO               TEXT,
    IDENTIFICADOR_FROTA          TEXT,
    COD_MOVIMENTACAO             BIGINT,
    COD_RECAPADORA               BIGINT,
    NOME_RECAPADORA              TEXT,
    COD_EMPRESA_RECAPADORA       BIGINT,
    RECAPADORA_ATIVA             BOOLEAN,
    COD_COLETA                   TEXT)
LANGUAGE SQL
AS $$
WITH MOVIMENTACOES_ANALISE AS (
    SELECT
      INNER_TABLE.CODIGO                 AS COD_MOVIMENTACAO,
      INNER_TABLE.COD_PNEU               AS COD_PNEU,
      INNER_TABLE.COD_RECAPADORA_DESTINO AS COD_RECAPADORA,
      INNER_TABLE.NOME                   AS NOME_RECAPADORA,
      INNER_TABLE.COD_EMPRESA            AS COD_EMPRESA_RECAPADORA,
      INNER_TABLE.ATIVA                  AS RECAPADORA_ATIVA,
      INNER_TABLE.COD_COLETA             AS COD_COLETA
    FROM (SELECT
            MOV.CODIGO,
            MOV.COD_PNEU,
            MAX(MOV.CODIGO)
            OVER (
              PARTITION BY COD_PNEU ) AS MAX_COD_MOVIMENTACAO,
            MD.COD_RECAPADORA_DESTINO,
            REC.NOME,
            REC.COD_EMPRESA,
            REC.ATIVA,
            MD.COD_COLETA
          FROM MOVIMENTACAO AS MOV
            JOIN MOVIMENTACAO_DESTINO AS MD ON MOV.CODIGO = MD.COD_MOVIMENTACAO
            LEFT JOIN RECAPADORA AS REC ON MD.COD_RECAPADORA_DESTINO = REC.CODIGO
          WHERE COD_UNIDADE = F_COD_UNIDADE AND MD.TIPO_DESTINO = 'ANALISE') AS INNER_TABLE
    WHERE CODIGO = INNER_TABLE.MAX_COD_MOVIMENTACAO
)

SELECT
  FUNC.*,
  MA.COD_MOVIMENTACAO,
  MA.COD_RECAPADORA,
  MA.NOME_RECAPADORA,
  MA.COD_EMPRESA_RECAPADORA,
  MA.RECAPADORA_ATIVA,
  MA.COD_COLETA
FROM FUNC_PNEU_GET_LISTAGEM_PNEUS_BY_STATUS(array[F_COD_UNIDADE], 'ANALISE') AS FUNC
  JOIN MOVIMENTACOES_ANALISE MA ON MA.COD_PNEU = FUNC.CODIGO;
$$;