CREATE OR REPLACE FUNCTION FUNC_PNEU_FORMAT_SULCO(
  F_SULCO REAL)
  RETURNS TEXT
LANGUAGE PLPGSQL
AS $$
BEGIN
  RETURN REPLACE(COALESCE(TRUNC(F_SULCO :: NUMERIC, 2) :: TEXT, '-'), '.', ',');
END;
$$;