-- Sobre:
--
-- Retorna informações dos pneus vinculados de uma placa.
--
-- Histórico:
-- 2019-09-06 -> Function criada (thaisksf PL-2258).
-- 2019-10-09 -> Adiciona ordenamento por ordem_exibicao (diogenesvanzella - PL-2344).
-- 2020-07-01 -> Adiciona identificador frota (luiz_fp - PL-2760).
CREATE OR REPLACE FUNCTION FUNC_PNEU_GET_PNEU_BY_PLACA(F_PLACA VARCHAR(7))
  RETURNS TABLE (
    NOME_MARCA_PNEU              VARCHAR(255),
    COD_MARCA_PNEU               BIGINT,
    CODIGO                       BIGINT,
    CODIGO_CLIENTE               VARCHAR(255),
    COD_UNIDADE_ALOCADO          BIGINT,
    COD_REGIONAL_ALOCADO         BIGINT,
    PRESSAO_ATUAL                REAL,
    VIDA_ATUAL                   INTEGER,
    VIDA_TOTAL                   INTEGER,
    PNEU_NOVO_NUNCA_RODADO       BOOLEAN,
    NOME_MODELO_PNEU             VARCHAR(255),
    COD_MODELO_PNEU              BIGINT,
    QT_SULCOS_MODELO_PNEU        SMALLINT,
    ALTURA_SULCOS_MODELO_PNEU    REAL,
    ALTURA                       INTEGER,
    LARGURA                      INTEGER,
    ARO                          REAL,
    COD_DIMENSAO                 BIGINT,
    PRESSAO_RECOMENDADA          REAL,
    ALTURA_SULCO_CENTRAL_INTERNO REAL,
    ALTURA_SULCO_CENTRAL_EXTERNO REAL,
    ALTURA_SULCO_INTERNO         REAL,
    ALTURA_SULCO_EXTERNO         REAL,
    STATUS                       VARCHAR(255),
    DOT                          VARCHAR(20),
    VALOR                        REAL,
    COD_MODELO_BANDA             BIGINT,
    NOME_MODELO_BANDA            VARCHAR(255),
    QT_SULCOS_MODELO_BANDA       SMALLINT,
    ALTURA_SULCOS_MODELO_BANDA   REAL,
    COD_MARCA_BANDA              BIGINT,
    NOME_MARCA_BANDA             VARCHAR(255),
    VALOR_BANDA                  REAL,
    POSICAO_PNEU                 INTEGER,
    POSICAO_APLICADO_CLIENTE     VARCHAR(255),
    COD_VEICULO_APLICADO         BIGINT,
    PLACA_APLICADO               VARCHAR(7),
    IDENTIFICADOR_FROTA          TEXT
  )
LANGUAGE SQL
AS $$
SELECT
  MP.NOME                                  AS NOME_MARCA_PNEU,
  MP.CODIGO                                AS COD_MARCA_PNEU,
  P.CODIGO,
  P.CODIGO_CLIENTE,
  U.CODIGO                                 AS COD_UNIDADE_ALOCADO,
  R.CODIGO                                 AS COD_REGIONAL_ALOCADO,
  P.PRESSAO_ATUAL,
  P.VIDA_ATUAL,
  P.VIDA_TOTAL,
  P.PNEU_NOVO_NUNCA_RODADO,
  MOP.NOME                                 AS NOME_MODELO_PNEU,
  MOP.CODIGO                               AS COD_MODELO_PNEU,
  MOP.QT_SULCOS                            AS QT_SULCOS_MODELO_PNEU,
  MOP.ALTURA_SULCOS                        AS ALTURA_SULCOS_MODELO_PNEU,
  PD.ALTURA,
  PD.LARGURA,
  PD.ARO,
  PD.CODIGO                                AS COD_DIMENSAO,
  P.PRESSAO_RECOMENDADA,
  P.ALTURA_SULCO_CENTRAL_INTERNO,
  P.ALTURA_SULCO_CENTRAL_EXTERNO,
  P.ALTURA_SULCO_INTERNO,
  P.ALTURA_SULCO_EXTERNO,
  P.STATUS,
  P.DOT,
  P.VALOR,
  MOB.CODIGO                               AS COD_MODELO_BANDA,
  MOB.NOME                                 AS NOME_MODELO_BANDA,
  MOB.QT_SULCOS                            AS QT_SULCOS_MODELO_BANDA,
  MOB.ALTURA_SULCOS                        AS ALTURA_SULCOS_MODELO_BANDA,
  MAB.CODIGO                               AS COD_MARCA_BANDA,
  MAB.NOME                                 AS NOME_MARCA_BANDA,
  PVV.VALOR                                AS VALOR_BANDA,
  PO.POSICAO_PROLOG                        AS POSICAO_PNEU,
  COALESCE(PPNE.NOMENCLATURA :: TEXT, '-') AS POSICAO_APLICADO_CLIENTE,
  VEI.CODIGO                               AS COD_VEICULO_APLICADO,
  VEI.PLACA                                AS PLACA_APLICADO,
  VEI.IDENTIFICADOR_FROTA                  AS IDENTIFICADOR_FROTA
FROM PNEU P
  JOIN MODELO_PNEU MOP ON MOP.CODIGO = P.COD_MODELO
  JOIN MARCA_PNEU MP ON MP.CODIGO = MOP.COD_MARCA
  JOIN DIMENSAO_PNEU PD ON PD.CODIGO = P.COD_DIMENSAO
  JOIN UNIDADE U ON U.CODIGO = P.COD_UNIDADE
  JOIN REGIONAL R ON U.COD_REGIONAL = R.CODIGO
  LEFT JOIN VEICULO_PNEU VP ON P.CODIGO = VP.COD_PNEU
  LEFT JOIN VEICULO VEI ON VEI.PLACA = VP.PLACA
  LEFT JOIN VEICULO_TIPO VT ON VT.CODIGO = VEI.COD_TIPO AND VT.COD_EMPRESA = P.COD_EMPRESA
  LEFT JOIN VEICULO_DIAGRAMA VD ON VT.COD_DIAGRAMA = VD.CODIGO
  LEFT JOIN PNEU_ORDEM PO ON VP.POSICAO = PO.POSICAO_PROLOG
  LEFT JOIN MODELO_BANDA MOB ON MOB.CODIGO = P.COD_MODELO_BANDA AND MOB.COD_EMPRESA = U.COD_EMPRESA
  LEFT JOIN MARCA_BANDA MAB ON MAB.CODIGO = MOB.COD_MARCA AND MAB.COD_EMPRESA = MOB.COD_EMPRESA
  LEFT JOIN PNEU_VALOR_VIDA PVV ON PVV.COD_PNEU = P.CODIGO AND PVV.VIDA = P.VIDA_ATUAL
  LEFT JOIN PNEU_POSICAO_NOMENCLATURA_EMPRESA PPNE ON
                                                     PPNE.COD_EMPRESA = P.COD_EMPRESA AND
                                                     PPNE.COD_DIAGRAMA = VD.CODIGO AND
                                                     PPNE.POSICAO_PROLOG = VP.POSICAO
WHERE VP.PLACA = F_PLACA
ORDER BY PO.ORDEM_EXIBICAO ASC;
$$;