CREATE OR REPLACE FUNCTION FUNC_PNEU_GET_COD_PNEU_BY_CODIGO_CLIENTE(F_COD_EMPRESA BIGINT, F_COD_CLIENTE TEXT[])
    RETURNS TABLE
            (
                COD_PNEU BIGINT
            )
    LANGUAGE SQL
AS
$$
SELECT P.CODIGO AS COD_PNEU
FROM PNEU P
WHERE P.COD_EMPRESA = F_COD_EMPRESA
  AND P.CODIGO_CLIENTE LIKE ANY (F_COD_CLIENTE);
$$;