CREATE OR REPLACE FUNCTION FUNC_PNEU_GET_NIVEL_DESGASTE_IRREGULAR(
  F_VARIACAO                REAL,
  F_TIPO_DESGASTE_ANALISADO PNEU_DESGASTE_IRREGULAR_TYPE)
  RETURNS PNEU_DESGASTE_IRREGULAR_NIVEL_TYPE
LANGUAGE PLPGSQL
AS $$
BEGIN
  IF F_VARIACAO <= 0
  THEN
    RETURN NULL :: PNEU_DESGASTE_IRREGULAR_NIVEL_TYPE;
  END IF;

  IF F_VARIACAO :: NUMERIC <@ (SELECT FAIXA_DESGASTE_BAIXO_MILIMETROS
                               FROM PNEU_NIVEL_DESGASTE_IRREGULAR_PADRAO_PROLOG
                               WHERE TIPO_DESGASTE_IRREGULAR = F_TIPO_DESGASTE_ANALISADO)
  THEN
    RETURN 'BAIXO' :: PNEU_DESGASTE_IRREGULAR_NIVEL_TYPE;
  ELSEIF F_VARIACAO :: NUMERIC <@ (SELECT FAIXA_DESGASTE_MODERADO_MILIMETROS
                                   FROM PNEU_NIVEL_DESGASTE_IRREGULAR_PADRAO_PROLOG
                                   WHERE TIPO_DESGASTE_IRREGULAR = F_TIPO_DESGASTE_ANALISADO)
    THEN
      RETURN 'MODERADO' :: PNEU_DESGASTE_IRREGULAR_NIVEL_TYPE;
  ELSEIF F_VARIACAO :: NUMERIC <@ (SELECT FAIXA_DESGASTE_ACENTUADO_MILIMETROS
                                   FROM PNEU_NIVEL_DESGASTE_IRREGULAR_PADRAO_PROLOG
                                   WHERE TIPO_DESGASTE_IRREGULAR = F_TIPO_DESGASTE_ANALISADO)
    THEN
      RETURN 'ACENTUADO' :: PNEU_DESGASTE_IRREGULAR_NIVEL_TYPE;
  END IF;
END;
$$;