CREATE OR REPLACE FUNCTION FUNC_PNEU_VERIFICA_DESGASTE_IRREGULAR(
  F_COD_PNEU              BIGINT,
  F_SULCO_EXTERNO         REAL,
  F_SULCO_CENTRAL_EXTERNO REAL,
  F_SULCO_CENTRAL_INTERNO REAL,
  F_SULCO_INTERNO         REAL)
  RETURNS TABLE(
    COD_PNEU                 BIGINT,
    TEM_DESGASTE_IRREGULAR   BOOLEAN,
    TIPO_DESGASTE_IRREGULAR  PNEU_DESGASTE_IRREGULAR_TYPE,
    NIVEL_DESGASTE_IRREGULAR PNEU_DESGASTE_IRREGULAR_NIVEL_TYPE)
LANGUAGE PLPGSQL
AS $$
DECLARE
  -- Esse array irá salvar os níveis de desgaste encontrados em um mesmo pneu.
  -- Ex.: Para um desgaste central, o sulco central em relação ao sulco externo pode ter um desgaste MODERADO. Porém,
  -- em relação ao interno pode ter um desgaste ACENTUADO. Nesse array será salvo os dois níveis.
  TT PNEU_DESGASTE_IRREGULAR_NIVEL_TYPE [];
BEGIN

  -- DESGASTE_OMBROS_BANDA_RODAGEM
  IF (F_SULCO_EXTERNO < F_SULCO_CENTRAL_EXTERNO AND F_SULCO_EXTERNO < F_SULCO_CENTRAL_INTERNO)
     AND (F_SULCO_INTERNO < F_SULCO_CENTRAL_EXTERNO AND F_SULCO_INTERNO < F_SULCO_CENTRAL_INTERNO)
  THEN
    -- Verfica a variação do sulco externo com relação aos centrais.
    SELECT ARRAY_APPEND(TT, FUNC_PNEU_GET_NIVEL_DESGASTE_IRREGULAR(F_SULCO_CENTRAL_EXTERNO - F_SULCO_EXTERNO, 'DESGASTE_OMBROS_BANDA_RODAGEM')) INTO TT;
    SELECT ARRAY_APPEND(TT, FUNC_PNEU_GET_NIVEL_DESGASTE_IRREGULAR(F_SULCO_CENTRAL_INTERNO - F_SULCO_EXTERNO, 'DESGASTE_OMBROS_BANDA_RODAGEM')) INTO TT;

    -- Verfica a variação do sulco interno com relação aos centrais.
    SELECT ARRAY_APPEND(TT, FUNC_PNEU_GET_NIVEL_DESGASTE_IRREGULAR(F_SULCO_CENTRAL_EXTERNO - F_SULCO_INTERNO, 'DESGASTE_OMBROS_BANDA_RODAGEM')) INTO TT;
    SELECT ARRAY_APPEND(TT, FUNC_PNEU_GET_NIVEL_DESGASTE_IRREGULAR(F_SULCO_CENTRAL_INTERNO - F_SULCO_INTERNO, 'DESGASTE_OMBROS_BANDA_RODAGEM')) INTO TT;
    RETURN QUERY
    SELECT
      F_COD_PNEU,
      TRUE,
      'DESGASTE_OMBROS_BANDA_RODAGEM' :: PNEU_DESGASTE_IRREGULAR_TYPE,
      -- Nesse momento, o array irá conter todos os níveis de desgaste encontrados no pneu analisado. Incluindo nulls,
      -- caso a variação seja <= 0. Nós pegamos o nível mais alto de desgaste encontrado e retornamos como o nível
      -- de desgaste do pneu. O que esse SELECT faz é transformar o array em várias linhas usando UNNEST, ordenar pelo
      -- ENUM e pegar apenas o nível mais alto usando LIMIT 1.
      -- Atente-se para algumas coisas importantes:
      -- 1 - ORDER BY NIVEL só funciona pois o PG ordena um enum com base na ordem em que os elementos foram criados
      -- nesse enum. E nós criamos como BAIXO, MODERADO, ACENTUADO. Por isso ORDER BY NIVEL DESC funciona.
      -- 2 - É imprescindível manter o NULLS LAST. Isso porque se o nível de desgaste for null, caso variação <= 0, como
      -- falado acima, o ORDER BY faria esses valores nulls ficarem primeiro e nós acabaríamos retornando eles como o nível
      -- de desgaste do pneu.
      (SELECT UNNEST(TT) AS NIVEL ORDER BY NIVEL DESC NULLS LAST LIMIT 1);
    RETURN;
  END IF;

  -- DESGASTE_CENTRALIZADO
  IF (F_SULCO_CENTRAL_EXTERNO < F_SULCO_EXTERNO AND F_SULCO_CENTRAL_EXTERNO < F_SULCO_INTERNO)
     AND (F_SULCO_CENTRAL_INTERNO < F_SULCO_EXTERNO AND F_SULCO_CENTRAL_INTERNO < F_SULCO_INTERNO)
  THEN
    SELECT ARRAY_APPEND(TT, FUNC_PNEU_GET_NIVEL_DESGASTE_IRREGULAR(F_SULCO_EXTERNO - F_SULCO_CENTRAL_EXTERNO, 'DESGASTE_CENTRALIZADO')) INTO TT;
    SELECT ARRAY_APPEND(TT, FUNC_PNEU_GET_NIVEL_DESGASTE_IRREGULAR(F_SULCO_INTERNO - F_SULCO_CENTRAL_EXTERNO, 'DESGASTE_CENTRALIZADO')) INTO TT;
    SELECT ARRAY_APPEND(TT, FUNC_PNEU_GET_NIVEL_DESGASTE_IRREGULAR(F_SULCO_EXTERNO - F_SULCO_CENTRAL_INTERNO, 'DESGASTE_CENTRALIZADO')) INTO TT;
    SELECT ARRAY_APPEND(TT, FUNC_PNEU_GET_NIVEL_DESGASTE_IRREGULAR(F_SULCO_INTERNO - F_SULCO_CENTRAL_INTERNO, 'DESGASTE_CENTRALIZADO')) INTO TT;
    RETURN QUERY
    SELECT
      F_COD_PNEU,
      TRUE,
      'DESGASTE_CENTRALIZADO' :: PNEU_DESGASTE_IRREGULAR_TYPE,
      (SELECT UNNEST(TT) AS NIVEL ORDER BY NIVEL DESC NULLS LAST LIMIT 1);
    RETURN;
  END IF;

  -- DESGASTE_ACENTUADO_UM_OMBRO_PNEU
  IF (F_SULCO_EXTERNO < F_SULCO_CENTRAL_EXTERNO
      AND F_SULCO_EXTERNO < F_SULCO_CENTRAL_INTERNO
      AND F_SULCO_EXTERNO < F_SULCO_INTERNO)
     OR (F_SULCO_INTERNO < F_SULCO_CENTRAL_EXTERNO
         AND F_SULCO_INTERNO < F_SULCO_CENTRAL_INTERNO
         AND F_SULCO_INTERNO < F_SULCO_EXTERNO)
  THEN
    -- Verifica a variação do sulco externo com relação a todos os outros sulcos.
    SELECT ARRAY_APPEND(TT, FUNC_PNEU_GET_NIVEL_DESGASTE_IRREGULAR(F_SULCO_CENTRAL_EXTERNO - F_SULCO_EXTERNO, 'DESGASTE_ACENTUADO_UM_OMBRO_PNEU')) INTO TT;
    SELECT ARRAY_APPEND(TT, FUNC_PNEU_GET_NIVEL_DESGASTE_IRREGULAR(F_SULCO_CENTRAL_INTERNO - F_SULCO_EXTERNO, 'DESGASTE_ACENTUADO_UM_OMBRO_PNEU')) INTO TT;
    SELECT ARRAY_APPEND(TT, FUNC_PNEU_GET_NIVEL_DESGASTE_IRREGULAR(F_SULCO_INTERNO - F_SULCO_EXTERNO, 'DESGASTE_ACENTUADO_UM_OMBRO_PNEU')) INTO TT;

    -- Verifica a variação do sulco interno com relação a todos os outros sulcos.
    SELECT ARRAY_APPEND(TT, FUNC_PNEU_GET_NIVEL_DESGASTE_IRREGULAR(F_SULCO_CENTRAL_EXTERNO - F_SULCO_INTERNO, 'DESGASTE_ACENTUADO_UM_OMBRO_PNEU')) INTO TT;
    SELECT ARRAY_APPEND(TT, FUNC_PNEU_GET_NIVEL_DESGASTE_IRREGULAR(F_SULCO_CENTRAL_INTERNO - F_SULCO_INTERNO, 'DESGASTE_ACENTUADO_UM_OMBRO_PNEU')) INTO TT;
    SELECT ARRAY_APPEND(TT, FUNC_PNEU_GET_NIVEL_DESGASTE_IRREGULAR(F_SULCO_EXTERNO - F_SULCO_INTERNO, 'DESGASTE_ACENTUADO_UM_OMBRO_PNEU')) INTO TT;

    RETURN QUERY
    SELECT
      F_COD_PNEU,
      TRUE,
      'DESGASTE_ACENTUADO_UM_OMBRO_PNEU' :: PNEU_DESGASTE_IRREGULAR_TYPE,
      (SELECT UNNEST(TT) AS NIVEL ORDER BY NIVEL DESC NULLS LAST LIMIT 1);
    RETURN;
  END IF;

  RETURN QUERY
  SELECT
    F_COD_PNEU,
    FALSE,
    NULL :: PNEU_DESGASTE_IRREGULAR_TYPE,
    NULL :: PNEU_DESGASTE_IRREGULAR_NIVEL_TYPE;
END;
$$;