-- Fecha as OSs.
WITH CTE AS (
    SELECT *
    FROM CHECKLIST_ORDEM_SERVICO COS
    WHERE COS.STATUS = 'A'
          AND ((SELECT COUNT(COSI.CODIGO)
                FROM CHECKLIST_ORDEM_SERVICO_ITENS COSI
                WHERE COSI.STATUS_RESOLUCAO = 'P'
                      AND COSI.COD_UNIDADE = COS.COD_UNIDADE
                      AND COSI.COD_OS = COS.CODIGO) = 0))


UPDATE CHECKLIST_ORDEM_SERVICO AS COSA
SET
  STATUS = 'F'
FROM CTE
WHERE COSA.CODIGO = CTE.CODIGO AND COSA.COD_UNIDADE = CTE.COD_UNIDADE;


-- Seta DATA_HORA_FECHAMENTO como o MAX da data/hora de resolução dos items.
UPDATE CHECKLIST_ORDEM_SERVICO AS COSA
SET
  DATA_HORA_FECHAMENTO = (SELECT MAX(COSI.DATA_HORA_CONSERTO)
                          FROM CHECKLIST_ORDEM_SERVICO_ITENS_DATA COSI
                          WHERE COSI.COD_OS = COSA.CODIGO
                                AND COSI.COD_UNIDADE = COSA.COD_UNIDADE
                                AND COSI.DELETADO = FALSE)
WHERE COSA.STATUS = 'F' AND DATA_HORA_FECHAMENTO IS NULL;

