CREATE OR REPLACE FUNCTION FUNC_VEICULO_GET_MARCAS_MODELOS_EMPRESA(
  F_COD_EMPRESA BIGINT)
  RETURNS TABLE(
    COD_MARCA   BIGINT,
    NOME_MARCA  TEXT,
    COD_MODELO  BIGINT,
    NOME_MODELO TEXT)
LANGUAGE SQL
AS $$
SELECT
  MAV.CODIGO AS COD_MARCA,
  MAV.NOME   AS NOME_MARCA,
  MOV.CODIGO AS COD_MODELO,
  MOV.NOME   AS NOME_MODELO
FROM MARCA_VEICULO MAV
  LEFT JOIN MODELO_VEICULO MOV
    ON MAV.CODIGO = MOV.COD_MARCA AND MOV.COD_EMPRESA = F_COD_EMPRESA
ORDER BY MAV.CODIGO ASC, MOV.CODIGO ASC;
$$;
COMMENT ON FUNCTION FUNC_VEICULO_GET_MARCAS_MODELOS_EMPRESA(BIGINT) IS 'Retorna as marcas e modelos de veículos de uma empresa. Caso a empresa não tenha modelos para uma marca qualquer, essa marca ainda será retornada.';
