CREATE OR REPLACE FUNCTION FUNC_VEICULO_GET_MARCAS_NIVEL_PROLOG()
  RETURNS TABLE(
    COD_MARCA   BIGINT,
    NOME_MARCA  TEXT)
LANGUAGE SQL
AS $$
SELECT
  MV.CODIGO AS COD_MARCA,
  MV.NOME   AS NOME_MARCA
FROM MARCA_VEICULO MV
ORDER BY MV.NOME ASC;
$$;
COMMENT ON FUNCTION FUNC_VEICULO_GET_MARCAS_NIVEL_PROLOG() IS 'As marcas de veículo são a nível ProLog. Essa function retorna todas as marcas disponíveis no BD.';