CREATE OR REPLACE FUNCTION FUNC_VEICULO_VERIFICA_POSSUI_VINCULO_MODELO_CHECKLIST(F_COD_VEICULO BIGINT)
  RETURNS BOOLEAN
LANGUAGE SQL
AS $$
SELECT EXISTS(
           SELECT
             V.CODIGO
           FROM VEICULO V
             JOIN CHECKLIST_MODELO_VEICULO_TIPO CMVT
               ON V.COD_TIPO = CMVT.COD_TIPO_VEICULO
                  AND V.COD_UNIDADE = CMVT.COD_UNIDADE
             JOIN CHECKLIST_MODELO CM
               ON CMVT.COD_MODELO = CM.CODIGO
                  AND CM.STATUS_ATIVO = TRUE
           WHERE V.CODIGO = F_COD_VEICULO) AS ESTA_VINCULADO_MODELO_CHECKLIST
$$;