CREATE OR REPLACE FUNCTION FUNC_CARGOS_GET_TODOS_CARGOS_EMPRESA(
  F_COD_EMPRESA BIGINT)
  RETURNS TABLE(
    COD_CARGO                    BIGINT,
    NOME_CARGO                   TEXT,
    QTD_COLABORADORES_VINCULADOS BIGINT)
LANGUAGE PLPGSQL
AS $$
BEGIN
  RETURN QUERY
  SELECT DISTINCT
    F.CODIGO                                  AS COD_CARGO,
    F.NOME :: TEXT                            AS NOME_CARGO,
    (SELECT COUNT(*)
     FROM COLABORADOR C
     WHERE C.COD_FUNCAO = F.CODIGO
           AND C.COD_EMPRESA = F_COD_EMPRESA) AS QTD_COLABORADORES_VINCULADOS
  FROM FUNCAO F
  WHERE F.COD_EMPRESA = F_COD_EMPRESA
  ORDER BY 2 ASC;
END;
$$;