CREATE OR REPLACE FUNCTION FUNC_CARGOS_GET_CARGO(
  F_COD_EMPRESA BIGINT,
  F_COD_CARGO   BIGINT)
  RETURNS TABLE(
    COD_EMPRESA  BIGINT,
    COD_CARGO  BIGINT,
    NOME_CARGO TEXT)
LANGUAGE PLPGSQL
AS $$
BEGIN
  RETURN QUERY
  SELECT F.COD_EMPRESA AS COD_EMPRESA,
         F.CODIGO AS COD_CARGO,
         F.NOME :: TEXT AS NOME_CARGO
  FROM FUNCAO F
  WHERE F.COD_EMPRESA = F_COD_EMPRESA
    AND F.CODIGO = F_COD_CARGO;
END;
$$;