CREATE OR REPLACE FUNCTION FUNC_CHECKLIST_OFFLINE_UPDATE_VERSAO_DADOS_UNIDADE_MODELO_CHECK(
  F_COD_MODELO_CHECKLIST BIGINT)
  RETURNS TABLE(
    EMPRESA_CHECKLIST_OFFLINE_BLOQUEADO BOOLEAN,
    VERSAO_DADOS_CHECKLIST_UNIDADE      BIGINT)
LANGUAGE PLPGSQL
AS $$
BEGIN
  RETURN QUERY
  SELECT *
  FROM FUNC_CHECKLIST_OFFLINE_UPDATE_VERSAO_DADOS_UNIDADE((SELECT CM.COD_UNIDADE
                                                           FROM CHECKLIST_MODELO CM
                                                           WHERE CM.CODIGO = F_COD_MODELO_CHECKLIST));
END;
$$;