CREATE OR REPLACE FUNCTION FUNC_CHECKLIST_OFFLINE_UPDATE_VERSAO_DADOS_UNIDADE(F_COD_UNIDADE BIGINT)
  RETURNS TABLE(
    EMPRESA_CHECKLIST_OFFLINE_BLOQUEADO BOOLEAN,
    VERSAO_DADOS_CHECKLIST_UNIDADE BIGINT)
LANGUAGE PLPGSQL
AS $$
DECLARE
  F_COD_EMPRESA BIGINT := (SELECT U.COD_EMPRESA FROM UNIDADE U WHERE U.CODIGO = F_COD_UNIDADE);
  VERSAO_DADOS_BD BIGINT;
BEGIN
  IF (SELECT EXISTS(SELECT COEB.COD_EMPRESA
                    FROM CHECKLIST_OFFLINE_EMPRESA_BLOQUEADA COEB
                    WHERE COEB.COD_EMPRESA = F_COD_EMPRESA))
  THEN
    RETURN QUERY
    SELECT
      TRUE           AS EMPRESA_CHECKLIST_OFFLINE_BLOQUEADO,
      NULL :: BIGINT AS VERSAO_DADOS_CHECKLIST_UNIDADE;
  ELSE
    IF (SELECT EXISTS(SELECT COD_UNIDADE FROM CHECKLIST_OFFLINE_DADOS_UNIDADE WHERE COD_UNIDADE = F_COD_UNIDADE))
    THEN
      UPDATE CHECKLIST_OFFLINE_DADOS_UNIDADE SET VERSAO_DADOS = VERSAO_DADOS + 1
      WHERE COD_UNIDADE = F_COD_UNIDADE RETURNING VERSAO_DADOS INTO VERSAO_DADOS_BD;
    ELSE
      INSERT INTO CHECKLIST_OFFLINE_DADOS_UNIDADE(COD_UNIDADE, TOKEN_SINCRONIZACAO_CHECKLIST)
      VALUES (F_COD_UNIDADE, F_RANDOM_STRING(64)) RETURNING VERSAO_DADOS INTO VERSAO_DADOS_BD;
    END IF;

    RETURN QUERY
    SELECT
        FALSE AS EMPRESA_CHECKLIST_OFFLINE_BLOQUEADO,
        VERSAO_DADOS_BD AS VERSAO_DADOS_CHECKLIST_UNIDADE;
  END IF;
END;
$$;