CREATE OR REPLACE FUNCTION FUNC_CHECKLIST_OFFLINE_EMPRESA_LIBERADA(F_COD_EMPRESA BIGINT)
  RETURNS BOOLEAN
LANGUAGE SQL
AS $$
SELECT NOT EXISTS(
    SELECT COEB.COD_EMPRESA
    FROM CHECKLIST_OFFLINE_EMPRESA_BLOQUEADA COEB
    WHERE COEB.COD_EMPRESA = F_COD_EMPRESA)
$$;