CREATE FUNCTION FUNC_CHECKLIST_OFFLINE_UPDATE_VERSAO_DADOS_UNIDADE_VEICULO(F_COD_VEICULO BIGINT)
  RETURNS TABLE(
    EMPRESA_CHECKLIST_OFFLINE_BLOQUEADO BOOLEAN,
    VERSAO_DADOS_CHECKLIST_UNIDADE      BIGINT)
LANGUAGE PLPGSQL
AS $$
BEGIN
  RETURN QUERY
  SELECT *
  FROM FUNC_CHECKLIST_OFFLINE_UPDATE_VERSAO_DADOS_UNIDADE((SELECT V.COD_UNIDADE
                                                           FROM VEICULO V
                                                           WHERE V.CODIGO = F_COD_VEICULO));
END;
$$;