-- ADICIONA A EMPRESA ADICIONADA À LISTA DE BLOQUEIO PARA CHECKLIST OFFLINE
CREATE OR REPLACE FUNCTION TG_FUNC_EMPRESA_BLOQUEIA_CHECKLIST_OFFLINE()
  RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO CHECKLIST_OFFLINE_EMPRESA_BLOQUEADA (COD_EMPRESA) VALUES (NEW.CODIGO);
  RETURN NEW;
END;
$$
LANGUAGE PLPGSQL SECURITY DEFINER ;

-- CRIA A TRIGGER
CREATE CONSTRAINT TRIGGER TG_BLOQUEIA_CHECKLIST_OFFLINE_EMPRESA_NOVA
  AFTER INSERT ON EMPRESA
  DEFERRABLE
  FOR EACH ROW
EXECUTE PROCEDURE TG_FUNC_EMPRESA_BLOQUEIA_CHECKLIST_OFFLINE();