CREATE OR REPLACE FUNCTION CHECK_NON_NUMERIC_CHARACTERS(F_TEXTO TEXT)
    RETURNS BOOLEAN
    IMMUTABLE STRICT
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    -- Verifica se a String possui apenas characteres numéricos.
    RETURN F_TEXTO ~ '^[0-9\.]+$';
END;
$$;