CREATE OR REPLACE FUNCTION COALESCE_PERCENTAGE(F_DIVIDENDO FLOAT, F_DIVISOR FLOAT)
  RETURNS TEXT
LANGUAGE PLPGSQL
AS $$
BEGIN
  RETURN COALESCE(TRUNC(F_DIVIDENDO/NULLIF(F_DIVISOR, 0) * 100) || '%', '0%');
END;
$$;