-- FUNCTION PARA FORMATAR CORRETAMENTE O CPF.
CREATE OR REPLACE FUNCTION FORMAT_CPF(CPF BIGINT)
  RETURNS TEXT
LANGUAGE PLPGSQL
AS $$
DECLARE
  _CPF TEXT;
BEGIN
  IF LENGTH(CPF::TEXT) > 11
  THEN RAISE EXCEPTION 'CPF % fora do padrão', CPF;
  END IF;

  SELECT REPLACE(TO_CHAR(CPF, '000:000:000-00'), ':', '.') INTO _CPF;
  RETURN _CPF;
END;
$$;