CREATE OR REPLACE FUNCTION FUNC_GERA_SIMILARIDADE(F_TEXTO1 TEXT,
                                                  F_TEXTO2 TEXT)
    RETURNS REAL
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    RETURN SIMILARITY(REMOVE_ESPACOS_E_CARACTERES_ESPECIAIS(F_TEXTO1),
                      REMOVE_ESPACOS_E_CARACTERES_ESPECIAIS(F_TEXTO2));
END;
$$;