CREATE OR REPLACE FUNCTION FUNC_CONVERTE_INTERVAL_HHMMSS(F_INTERVAL INTERVAL)
    RETURNS TEXT
    LANGUAGE PLPGSQL
    IMMUTABLE STRICT
AS
$$
DECLARE
	V_DATA_FORMATADA TEXT;
    V_HOURS CONSTANT TEXT := TRUNC(EXTRACT(EPOCH FROM (F_INTERVAL)) / 3600)::TEXT;
BEGIN
    IF F_INTERVAL IS NULL
    THEN
        RETURN NULL;
    END IF;

    SELECT CONCAT(
                   GREATEST(V_HOURS, LPAD(V_HOURS, 2, '0')),
                   ':',
                   TO_CHAR(TO_TIMESTAMP(
                                   EXTRACT(EPOCH FROM (F_INTERVAL))
                               ), 'MI:SS')
               ) INTO V_DATA_FORMATADA;
    RETURN  V_DATA_FORMATADA;
END;
$$;