CREATE OR REPLACE FUNCTION IS_TIMEZONE(TZ TEXT) RETURNS BOOLEAN AS
$$
DECLARE
    DATE TIMESTAMPTZ;
BEGIN
    DATE := NOW() AT TIME ZONE TZ;
    RETURN TRUE;
EXCEPTION
    WHEN OTHERS THEN
        RETURN FALSE;
END;
$$ LANGUAGE PLPGSQL STABLE;