CREATE OR REPLACE FUNCTION FUNC_PNEU_UPDATE_UNIDADE_ALOCACAO(
  F_COD_UNIDADE_ORIGEM  BIGINT,
  F_COD_UNIDADE_DESTINO BIGINT,
  F_COD_PNEUS           BIGINT []
)
  RETURNS BIGINT
LANGUAGE PLPGSQL
AS $$
DECLARE
  QTD_ROWS BIGINT;
BEGIN
  UPDATE PNEU
  SET COD_UNIDADE = F_COD_UNIDADE_DESTINO
  WHERE COD_UNIDADE = F_COD_UNIDADE_ORIGEM AND CODIGO = ANY (F_COD_PNEUS);
  GET DIAGNOSTICS QTD_ROWS = ROW_COUNT;
  RETURN QTD_ROWS;
END;
$$;