-- Sobre:
--
-- Esta function foi criada para a integração de aferições. foi desenhada para ser genérica e funcionar com qualquer
-- empresa que queira utilizar a integração de aferição de pneus do prolog.
--
-- Os dados retornados por essa function são as configurações que serão utilizadas para a realização de uma aferição
-- de placa.
--
-- Histórico:
-- 2020-03-24 -> Function criada (diogenesvanzella - pl-2563).
-- 2020-05-08 -> Modifica campos de retorno de liberação de aferição de boolean para text (gustavocnp95 - PL-2689)
CREATE OR REPLACE FUNCTION
    INTEGRACAO.FUNC_PNEU_AFERICAO_GET_CONFIG_NOVA_AFERICAO_PLACA(F_COD_UNIDADE BIGINT,
                                                                 F_COD_AUXILIAR_TIPO_VEICULO TEXT)
    RETURNS TABLE
            (
                SULCO_MINIMO_DESCARTE                  REAL,
                SULCO_MINIMO_RECAPAGEM                 REAL,
                TOLERANCIA_INSPECAO                    REAL,
                TOLERANCIA_CALIBRAGEM                  REAL,
                PERIODO_AFERICAO_SULCO                 INTEGER,
                PERIODO_AFERICAO_PRESSAO               INTEGER,
                FORMA_COLETA_DADOS_SULCO               TEXT,
                FORMA_COLETA_DADOS_PRESSAO             TEXT,
                FORMA_COLETA_DADOS_SULCO_PRESSAO       TEXT,
                PODE_AFERIR_ESTEPE                     BOOLEAN,
                VARIACAO_ACEITA_SULCO_MENOR_MILIMETROS DOUBLE PRECISION,
                VARIACAO_ACEITA_SULCO_MAIOR_MILIMETROS DOUBLE PRECISION,
                BLOQUEAR_VALORES_MENORES               BOOLEAN,
                BLOQUEAR_VALORES_MAIORES               BOOLEAN,
                VARIACOES_SULCO_DEFAULT_PROLOG         BOOLEAN
            )
    LANGUAGE SQL
AS
$$
WITH COD_AUXILIARES AS (
    SELECT VT.CODIGO                                   AS COD_TIPO_VEICULO,
           REGEXP_SPLIT_TO_TABLE(VT.COD_AUXILIAR, ',') AS COD_AUXILIAR
    FROM VEICULO_TIPO VT
    WHERE VT.COD_EMPRESA = (SELECT U.COD_EMPRESA FROM UNIDADE U WHERE U.CODIGO = F_COD_UNIDADE)
)

SELECT PRU.SULCO_MINIMO_DESCARTE                                  AS SULCO_MINIMO_DESCARTE,
       PRU.SULCO_MINIMO_RECAPAGEM                                 AS SULCO_MINIMO_RECAPAGEM,
       PRU.TOLERANCIA_INSPECAO                                    AS TOLERANCIA_INSPECAO,
       PRU.TOLERANCIA_CALIBRAGEM                                  AS TOLERANCIA_CALIBRAGEM,
       PRU.PERIODO_AFERICAO_SULCO                                 AS PERIODO_AFERICAO_SULCO,
       PRU.PERIODO_AFERICAO_PRESSAO                               AS PERIODO_AFERICAO_PRESSAO,
       CONFIG_PODE_AFERIR.FORMA_COLETA_DADOS_SULCO                AS PODE_AFERIR_SULCO,
       CONFIG_PODE_AFERIR.FORMA_COLETA_DADOS_PRESSAO              AS PODE_AFERIR_PRESSAO,
       CONFIG_PODE_AFERIR.FORMA_COLETA_DADOS_SULCO_PRESSAO        AS PODE_AFERIR_SULCO_PRESSAO,
       CONFIG_PODE_AFERIR.PODE_AFERIR_ESTEPE                      AS PODE_AFERIR_ESTEPE,
       CONFIG_ALERTA_SULCO.VARIACAO_ACEITA_SULCO_MENOR_MILIMETROS AS VARIACAO_ACEITA_SULCO_MENOR_MILIMETROS,
       CONFIG_ALERTA_SULCO.VARIACAO_ACEITA_SULCO_MAIOR_MILIMETROS AS VARIACAO_ACEITA_SULCO_MAIOR_MILIMETROS,
       CONFIG_ALERTA_SULCO.BLOQUEAR_VALORES_MENORES               AS BLOQUEAR_VALORES_MENORES,
       CONFIG_ALERTA_SULCO.BLOQUEAR_VALORES_MAIORES               AS BLOQUEAR_VALORES_MAIORES,
       CONFIG_ALERTA_SULCO.USA_DEFAULT_PROLOG                     AS VARIACOES_SULCO_DEFAULT_PROLOG
FROM FUNC_AFERICAO_GET_CONFIG_TIPO_AFERICAO_VEICULO(F_COD_UNIDADE) AS CONFIG_PODE_AFERIR
         JOIN VIEW_AFERICAO_CONFIGURACAO_ALERTA_SULCO AS CONFIG_ALERTA_SULCO
              ON CONFIG_PODE_AFERIR.COD_UNIDADE_CONFIGURACAO = CONFIG_ALERTA_SULCO.COD_UNIDADE
         JOIN PNEU_RESTRICAO_UNIDADE PRU
              ON PRU.COD_UNIDADE = CONFIG_PODE_AFERIR.COD_UNIDADE_CONFIGURACAO
         JOIN COD_AUXILIARES CA ON CA.COD_AUXILIAR = F_COD_AUXILIAR_TIPO_VEICULO
WHERE CONFIG_PODE_AFERIR.COD_UNIDADE_CONFIGURACAO = F_COD_UNIDADE
  AND CONFIG_PODE_AFERIR.COD_TIPO_VEICULO = CA.COD_TIPO_VEICULO
  AND PRU.COD_UNIDADE = F_COD_UNIDADE;
$$;